/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import test.FrmGl_currencyrated;
 * 
 * .......
 * 
 * 
 * FrmGl_currencyrated frmGl_currencyrated;
 * 
 * .......
 * 
 try {
        if (frmGl_currencyrated == null) {
            frmmGl_currencyrated = new FrmGl_currencyrated(this);
        }
        
        showForm(frmGl_currencyrated);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.gl;

import accapp.objectclasses.gl.Gl_currencyrated;
import accapp.objectclasses.gl.Gl_currencyrateds;
import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  Generator
 */

public class FrmGl_currencyrated extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmGl_currencyrated";
    
    FrmMainFrame mf ;
    
    
    public Gl_currencyrated obj = new Gl_currencyrated();
    
   
    /** Creates new form Area */
    public FrmGl_currencyrated() throws CodeException {
        initComponents();
    }
    
    public FrmGl_currencyrated(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblid = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jlblhomecur = new javax.swing.JLabel();
        jtxthomecur = new javax.swing.JTextField();
        jlblratetype = new javax.swing.JLabel();
        jtxtratetype = new javax.swing.JTextField();
        jlblsourcecur = new javax.swing.JLabel();
        jtxtsourcecur = new javax.swing.JTextField();
        jlblratedate = new javax.swing.JLabel();
        jtxtratedate = new javax.swing.JTextField();
        jlblrate = new javax.swing.JLabel();
        jtxtrate = new javax.swing.JTextField();
        jlblspread = new javax.swing.JLabel();
        jtxtspread = new javax.swing.JTextField();
        jlbldatematch = new javax.swing.JLabel();
        jtxtdatematch = new javax.swing.JTextField();
        jlblrateoper = new javax.swing.JLabel();
        jtxtrateoper = new javax.swing.JTextField();
        jlblentrydate = new javax.swing.JLabel();
        jtxtentrydate = new javax.swing.JTextField();
        jlblauditdate = new javax.swing.JLabel();
        jtxtauditdate = new javax.swing.JTextField();
        jlblaudituser = new javax.swing.JLabel();
        jtxtaudituser = new javax.swing.JTextField();
        jlblobjtype = new javax.swing.JLabel();
        jtxtobjtype = new javax.swing.JTextField();
        jlblcmpnyid = new javax.swing.JLabel();
        jtxtcmpnyid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gl_currencyrated");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Gl_currencyrated");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(430, 80, 30, 17);

        jlblid.setText("id");
        getContentPane().add(jlblid);
        jlblid.setBounds(70, 80, 140, 15);

        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(260, 80, 80, 19);

        jlblhomecur.setText("homecur");
        getContentPane().add(jlblhomecur);
        jlblhomecur.setBounds(70, 100, 140, 15);

        jtxthomecur.setText("homecur");
        getContentPane().add(jtxthomecur);
        jtxthomecur.setBounds(260, 100, 80, 19);

        jlblratetype.setText("ratetype");
        getContentPane().add(jlblratetype);
        jlblratetype.setBounds(70, 120, 140, 15);

        jtxtratetype.setText("ratetype");
        getContentPane().add(jtxtratetype);
        jtxtratetype.setBounds(260, 120, 80, 19);

        jlblsourcecur.setText("sourcecur");
        getContentPane().add(jlblsourcecur);
        jlblsourcecur.setBounds(70, 140, 140, 15);

        jtxtsourcecur.setText("sourcecur");
        getContentPane().add(jtxtsourcecur);
        jtxtsourcecur.setBounds(260, 140, 80, 19);

        jlblratedate.setText("ratedate");
        getContentPane().add(jlblratedate);
        jlblratedate.setBounds(70, 160, 140, 15);

        jtxtratedate.setText("ratedate");
        getContentPane().add(jtxtratedate);
        jtxtratedate.setBounds(260, 160, 80, 19);

        jlblrate.setText("rate");
        getContentPane().add(jlblrate);
        jlblrate.setBounds(70, 180, 140, 15);

        jtxtrate.setText("rate");
        getContentPane().add(jtxtrate);
        jtxtrate.setBounds(260, 180, 80, 19);

        jlblspread.setText("spread");
        getContentPane().add(jlblspread);
        jlblspread.setBounds(70, 200, 140, 15);

        jtxtspread.setText("spread");
        getContentPane().add(jtxtspread);
        jtxtspread.setBounds(260, 200, 80, 19);

        jlbldatematch.setText("datematch");
        getContentPane().add(jlbldatematch);
        jlbldatematch.setBounds(70, 220, 140, 15);

        jtxtdatematch.setText("datematch");
        getContentPane().add(jtxtdatematch);
        jtxtdatematch.setBounds(260, 220, 80, 19);

        jlblrateoper.setText("rateoper");
        getContentPane().add(jlblrateoper);
        jlblrateoper.setBounds(70, 240, 140, 15);

        jtxtrateoper.setText("rateoper");
        getContentPane().add(jtxtrateoper);
        jtxtrateoper.setBounds(260, 240, 80, 19);

        jlblentrydate.setText("entrydate");
        getContentPane().add(jlblentrydate);
        jlblentrydate.setBounds(70, 260, 140, 15);

        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 260, 80, 19);

        jlblauditdate.setText("auditdate");
        getContentPane().add(jlblauditdate);
        jlblauditdate.setBounds(70, 280, 140, 15);

        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(260, 280, 80, 19);

        jlblaudituser.setText("audituser");
        getContentPane().add(jlblaudituser);
        jlblaudituser.setBounds(70, 300, 140, 15);

        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(260, 300, 80, 19);

        jlblobjtype.setText("objtype");
        getContentPane().add(jlblobjtype);
        jlblobjtype.setBounds(70, 320, 140, 15);

        jtxtobjtype.setText("objtype");
        getContentPane().add(jtxtobjtype);
        jtxtobjtype.setBounds(260, 320, 80, 19);

        jlblcmpnyid.setText("cmpnyid");
        getContentPane().add(jlblcmpnyid);
        jlblcmpnyid.setBounds(70, 340, 140, 15);

        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(260, 340, 80, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Gl_currencyrateds brs = new Gl_currencyrateds();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtid);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmGl_currencyrated().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblauditdate;
    private javax.swing.JLabel jlblaudituser;
    private javax.swing.JLabel jlblcmpnyid;
    private javax.swing.JLabel jlbldatematch;
    private javax.swing.JLabel jlblentrydate;
    private javax.swing.JLabel jlblhomecur;
    private javax.swing.JLabel jlblid;
    private javax.swing.JLabel jlblobjtype;
    private javax.swing.JLabel jlblrate;
    private javax.swing.JLabel jlblratedate;
    private javax.swing.JLabel jlblrateoper;
    private javax.swing.JLabel jlblratetype;
    private javax.swing.JLabel jlblsourcecur;
    private javax.swing.JLabel jlblspread;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtdatematch;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxthomecur;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtobjtype;
    private javax.swing.JTextField jtxtrate;
    private javax.swing.JTextField jtxtratedate;
    private javax.swing.JTextField jtxtrateoper;
    private javax.swing.JTextField jtxtratetype;
    private javax.swing.JTextField jtxtsourcecur;
    private javax.swing.JTextField jtxtspread;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Gl_currencyrated(this.jtxtid.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Gl_currencyrated();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Gl_currencyrated.PROPERTY_ID));
             jtxthomecur.setText(obj.toString(Gl_currencyrated.PROPERTY_HOMECUR));
             jtxtratetype.setText(obj.toString(Gl_currencyrated.PROPERTY_RATETYPE));
             jtxtsourcecur.setText(obj.toString(Gl_currencyrated.PROPERTY_SOURCECUR));
             jtxtratedate.setText(obj.toString(Gl_currencyrated.PROPERTY_RATEDATE));
             jtxtrate.setText(obj.toString(Gl_currencyrated.PROPERTY_RATE));
             jtxtspread.setText(obj.toString(Gl_currencyrated.PROPERTY_SPREAD));
             jtxtdatematch.setText(obj.toString(Gl_currencyrated.PROPERTY_DATEMATCH));
             jtxtrateoper.setText(obj.toString(Gl_currencyrated.PROPERTY_RATEOPER));
             jtxtentrydate.setText(obj.toString(Gl_currencyrated.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Gl_currencyrated.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Gl_currencyrated.PROPERTY_AUDITUSER));
             jtxtobjtype.setText(obj.toString(Gl_currencyrated.PROPERTY_OBJTYPE));
             jtxtcmpnyid.setText(obj.toString(Gl_currencyrated.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Gl_currencyrated.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_HOMECUR, jtxthomecur.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_RATETYPE, jtxtratetype.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_SOURCECUR, jtxtsourcecur.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_RATEDATE, jtxtratedate.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_RATE, jtxtrate.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_SPREAD, jtxtspread.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_DATEMATCH, jtxtdatematch.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_RATEOPER, jtxtrateoper.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_OBJTYPE, jtxtobjtype.getText()) ;
          obj.fromString(Gl_currencyrated.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
