/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.gl.FrmGl_account;
 * 
 * .......
 * 
 * 
 * FrmGl_account frmGl_account;
 * 
 * .......
 * 
 try {
        if (frmGl_account == null) {
            frmmGl_account = new FrmGl_account(this);
        }
        
        showForm(frmGl_account);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.gl;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_account_structure;
import accapp.objectclasses.gl.Gl_account_structures;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_group;
import accapp.objectclasses.gl.Gl_groups;
import common.print.FrmPrintMasterGLAccountCode;
import javax.swing.JTextField;

/**
 *
 * @author  Generator
 */

public class FrmGl_account extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmGl_account";
    
    FrmMainFrame mf ;
    
    
    public Gl_account obj = new Gl_account();
    
   
    /** Creates new form Area */
    public FrmGl_account() throws CodeException {
        initComponents();
    }
    
    public FrmGl_account(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        jtxtid.setBounds(180, 30, 80, 20);
        jtxtentrydate.setBounds(260, 30, 160, 20);
        jtxtauditdate.setBounds(420, 30, 140, 20);
        jtxtaudituser.setBounds(560, 30, 110, 20);
        jtxtcmpnyid.setBounds(670, 30, 120, 20);

        jtxtid.setEditable(false);
        jtxtentrydate.setEditable(false);
        jtxtauditdate.setEditable(false);
        jtxtaudituser.setEditable(false);
        jtxtcmpnyid.setEditable(false);

        jchkboMultiCurrency.setVisible(false);
        jchkAutoAllocation.setVisible(false);
        jchkControlAccount.setVisible(false);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpStatus = new javax.swing.ButtonGroup();
        btngrpPostToAccount = new javax.swing.ButtonGroup();
        btngrpNormalBalance = new javax.swing.ButtonGroup();
        btngrpAccountType = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jtxtid = new javax.swing.JTextField();
        jlblacccode = new javax.swing.JLabel();
        jtxtacccode = new javax.swing.JTextField();
        jtxtaccdesc = new javax.swing.JTextField();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlblabrkcode = new javax.swing.JLabel();
        jtxtabrkcode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jrdrInactive = new javax.swing.JRadioButton();
        jrdrActive = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jrdrConsolidated = new javax.swing.JRadioButton();
        jrdrDetail = new javax.swing.JRadioButton();
        jchkboMultiCurrency = new javax.swing.JCheckBox();
        jchkControlAccount = new javax.swing.JCheckBox();
        jchkAutoAllocation = new javax.swing.JCheckBox();
        jbtnBrowse1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jrdrDebit = new javax.swing.JRadioButton();
        jrdrCredit = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jrdrIncome = new javax.swing.JRadioButton();
        jrdrBalanceSheet = new javax.swing.JRadioButton();
        jrdrRetainedEarning = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtaccountgroupcode = new javax.swing.JTextField();
        jbtnAccountGroup = new javax.swing.JButton();
        jtxtAccountGroupDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtaccfmttd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("G/L Chart Of Account");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Chart Of Account");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(170, 30, 80, 20);

        jlblacccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblacccode.setText("Account");
        getContentPane().add(jlblacccode);
        jlblacccode.setBounds(70, 100, 140, 13);

        jtxtacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtacccode.setText("acccode");
        jtxtacccode.setNextFocusableComponent(jtxtaccdesc);
        jtxtacccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtacccodeActionPerformed(evt);
            }
        });
        jtxtacccode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtacccodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtacccodeFocusLost(evt);
            }
        });
        jtxtacccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtacccodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtacccode);
        jtxtacccode.setBounds(220, 100, 190, 23);

        jtxtaccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccdesc.setText("accdesc");
        jtxtaccdesc.setNextFocusableComponent(jtxtaccfmttd);
        jtxtaccdesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaccdescFocusGained(evt);
            }
        });
        jtxtaccdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaccdescKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtaccdesc);
        jtxtaccdesc.setBounds(470, 100, 350, 23);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 30, 150, 20);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(420, 30, 150, 20);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(580, 30, 90, 20);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(680, 30, 130, 20);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel1.setLayout(null);

        jlblabrkcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblabrkcode.setText("Structure Code");
        jPanel1.add(jlblabrkcode);
        jlblabrkcode.setBounds(20, 20, 110, 13);

        jtxtabrkcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtabrkcode.setText("abrkcode");
        jtxtabrkcode.setNextFocusableComponent(jrdrDebit);
        jtxtabrkcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtabrkcodeFocusGained(evt);
            }
        });
        jPanel1.add(jtxtabrkcode);
        jtxtabrkcode.setBounds(140, 20, 130, 23);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
        jPanel3.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel3.setLayout(null);

        btngrpStatus.add(jrdrInactive);
        jrdrInactive.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrInactive.setText("In Active");
        jrdrInactive.setNextFocusableComponent(jrdrDetail);
        jPanel3.add(jrdrInactive);
        jrdrInactive.setBounds(140, 20, 100, 24);

        btngrpStatus.add(jrdrActive);
        jrdrActive.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrActive.setSelected(true);
        jrdrActive.setText("Active");
        jrdrActive.setNextFocusableComponent(jrdrInactive);
        jPanel3.add(jrdrActive);
        jrdrActive.setBounds(10, 20, 110, 24);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 110, 270, 50);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Post To Account"));
        jPanel4.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel4.setLayout(null);

        btngrpPostToAccount.add(jrdrConsolidated);
        jrdrConsolidated.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrConsolidated.setText("Consolidated");
        jrdrConsolidated.setNextFocusableComponent(jrdrIncome);
        jrdrConsolidated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdrConsolidatedActionPerformed(evt);
            }
        });
        jPanel4.add(jrdrConsolidated);
        jrdrConsolidated.setBounds(140, 20, 120, 24);

        btngrpPostToAccount.add(jrdrDetail);
        jrdrDetail.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrDetail.setSelected(true);
        jrdrDetail.setText("Detail");
        jrdrDetail.setNextFocusableComponent(jrdrConsolidated);
        jPanel4.add(jrdrDetail);
        jrdrDetail.setBounds(10, 20, 110, 24);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 170, 270, 60);

        jchkboMultiCurrency.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkboMultiCurrency.setText("Multi Currency");
        jPanel1.add(jchkboMultiCurrency);
        jchkboMultiCurrency.setBounds(610, 190, 140, 24);

        jchkControlAccount.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkControlAccount.setText("Control Account");
        jchkControlAccount.setNextFocusableComponent(jchkAutoAllocation);
        jPanel1.add(jchkControlAccount);
        jchkControlAccount.setBounds(310, 190, 140, 24);

        jchkAutoAllocation.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkAutoAllocation.setText("Auto Allocation");
        jchkAutoAllocation.setNextFocusableComponent(jchkboMultiCurrency);
        jPanel1.add(jchkAutoAllocation);
        jchkAutoAllocation.setBounds(460, 190, 140, 24);

        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBrowse1);
        jbtnBrowse1.setBounds(270, 20, 30, 17);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Normal Balance"));
        jPanel5.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel5.setLayout(null);

        btngrpNormalBalance.add(jrdrDebit);
        jrdrDebit.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrDebit.setSelected(true);
        jrdrDebit.setText("Debit");
        jrdrDebit.setNextFocusableComponent(jrdrCredit);
        jrdrDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdrDebitActionPerformed(evt);
            }
        });
        jPanel5.add(jrdrDebit);
        jrdrDebit.setBounds(10, 20, 90, 24);

        btngrpNormalBalance.add(jrdrCredit);
        jrdrCredit.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrCredit.setText("Credit");
        jrdrCredit.setNextFocusableComponent(jrdrActive);
        jPanel5.add(jrdrCredit);
        jrdrCredit.setBounds(140, 20, 114, 24);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 50, 270, 50);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Account Type"));
        jPanel6.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel6.setLayout(null);

        btngrpAccountType.add(jrdrIncome);
        jrdrIncome.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrIncome.setSelected(true);
        jrdrIncome.setText("Income");
        jrdrIncome.setNextFocusableComponent(jrdrBalanceSheet);
        jPanel6.add(jrdrIncome);
        jrdrIncome.setBounds(10, 20, 100, 24);

        btngrpAccountType.add(jrdrBalanceSheet);
        jrdrBalanceSheet.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrBalanceSheet.setText("Balance Sheet");
        jrdrBalanceSheet.setNextFocusableComponent(jrdrRetainedEarning);
        jPanel6.add(jrdrBalanceSheet);
        jrdrBalanceSheet.setBounds(120, 20, 130, 24);

        btngrpAccountType.add(jrdrRetainedEarning);
        jrdrRetainedEarning.setFont(new java.awt.Font("Dialog", 1, 10));
        jrdrRetainedEarning.setText("Retained Earning");
        jrdrRetainedEarning.setNextFocusableComponent(jbtnAccountGroup);
        jPanel6.add(jrdrRetainedEarning);
        jrdrRetainedEarning.setBounds(250, 20, 150, 24);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(310, 60, 410, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setText("Account Group");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 130, 110, 13);

        jtxtaccountgroupcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccountgroupcode.setText("jtxtaccountgroupcode");
        jtxtaccountgroupcode.setNextFocusableComponent(jchkControlAccount);
        jtxtaccountgroupcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtaccountgroupcodeKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtaccountgroupcode);
        jtxtaccountgroupcode.setBounds(450, 130, 60, 23);

        jbtnAccountGroup.setText("...");
        jbtnAccountGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAccountGroupActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAccountGroup);
        jbtnAccountGroup.setBounds(520, 130, 30, 17);

        jtxtAccountGroupDescription.setEditable(false);
        jtxtAccountGroupDescription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtAccountGroupDescription.setText("jtxtAccountGroupDescription");
        jPanel1.add(jtxtAccountGroupDescription);
        jtxtAccountGroupDescription.setBounds(560, 130, 190, 23);

        jTabbedPane1.addTab("Detail", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(70, 190, 780, 320);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel2.setText("Account Formated ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 140, 130, 13);

        jtxtaccfmttd.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccfmttd.setText("accfmttd");
        jtxtaccfmttd.setNextFocusableComponent(jtxtabrkcode);
        jtxtaccfmttd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaccfmttdKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtaccfmttd);
        jtxtaccfmttd.setBounds(220, 140, 190, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtacccodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtacccodeFocusGained
    // TODO add your handling code here:
    highlight((JTextField) evt.getComponent());
}//GEN-LAST:event_jtxtacccodeFocusGained

private void jtxtaccdescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtaccdescFocusGained
    // TODO add your handling code here:
    highlight((JTextField) evt.getComponent());
}//GEN-LAST:event_jtxtaccdescFocusGained

private void jtxtabrkcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtabrkcodeFocusGained
    // TODO add your handling code here:
    highlight((JTextField) evt.getComponent());
}//GEN-LAST:event_jtxtabrkcodeFocusGained

private void jtxtacccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtacccodeKeyPressed
    // TODO add your handling code here:
    
    if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        jtxtaccdesc.requestFocus();
    }
}//GEN-LAST:event_jtxtacccodeKeyPressed

private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
    // TODO add your handling code here:
    try {
          Gl_account_structures glacst = new Gl_account_structures();
          FrmBrowse bd = new FrmBrowse(glacst);
          bd.setFirstValue(jtxtabrkcode);
          bd.setModal(true);
          bd.setVisible(true);

      } catch (CodeException ex) {
          ex.printStackTrace();
      }
}//GEN-LAST:event_jbtnBrowse1ActionPerformed

private void jrdrConsolidatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdrConsolidatedActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jrdrConsolidatedActionPerformed

private void jrdrDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdrDebitActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jrdrDebitActionPerformed

private void jbtnAccountGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAccountGroupActionPerformed
      try {
	      Gl_groups glgrp = new Gl_groups();
	      FrmBrowse bd = new FrmBrowse(glgrp);
	      bd.setFirstValue(jtxtaccountgroupcode);
	      bd.setSecondValue(jtxtAccountGroupDescription);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
      
}//GEN-LAST:event_jbtnAccountGroupActionPerformed

private void jtxtaccountgroupcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccountgroupcodeKeyTyped

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setaccgrpcode(jtxtaccountgroupcode.getText());
            jtxtAccountGroupDescription.setText(obj.getAccountGroupDescription());
            
        }catch(Exception e) {}

        
    }

}//GEN-LAST:event_jtxtaccountgroupcodeKeyTyped

private void jtxtaccdescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccdescKeyPressed

   if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
       jtxtaccfmttd.requestFocus();
   }

}//GEN-LAST:event_jtxtaccdescKeyPressed

private void jtxtaccfmttdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccfmttdKeyPressed
    if (evt.getKeyCode() == evt.VK_ENTER) {
        jtxtabrkcode.requestFocus();
    }


   
}//GEN-LAST:event_jtxtaccfmttdKeyPressed

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    // TODO add your handling code here:
}//GEN-LAST:event_formKeyPressed

private void jtxtacccodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtacccodeFocusLost
        try {
            // TODO add your handling code here:
            if (!obj.cekkodeaccount(jtxtacccode.getText(), jtxtabrkcode.getText())) {
                jtxtabrkcode.requestFocus();
            } else {
                // jtxtaccfmttd.setText(obj.cekkodeaccountformated(jtxtacccode.getText(), jtxtabrkcode.getText()));
                jtxtaccfmttd.setText(jtxtacccode.getText().substring(0,2)+"-"+jtxtacccode.getText().substring(2,5)+"-"+jtxtacccode.getText().substring(5,7)+"-"+jtxtacccode.getText().substring(7,10)+"-"+jtxtacccode.getText().substring(10,13));
            }
        } catch (CodeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
}//GEN-LAST:event_jtxtacccodeFocusLost

private void jtxtacccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtacccodeActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtacccodeActionPerformed


public void highlight(JTextField otxt){
    otxt.setSelectionStart(0);
    otxt.setSelectionEnd(otxt.getText().length());
}

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtacccode);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmGl_account().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup btngrpAccountType;
    private javax.swing.ButtonGroup btngrpNormalBalance;
    private javax.swing.ButtonGroup btngrpPostToAccount;
    private javax.swing.ButtonGroup btngrpStatus;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnAccountGroup;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JCheckBox jchkAutoAllocation;
    private javax.swing.JCheckBox jchkControlAccount;
    private javax.swing.JCheckBox jchkboMultiCurrency;
    private javax.swing.JLabel jlblabrkcode;
    private javax.swing.JLabel jlblacccode;
    private javax.swing.JRadioButton jrdrActive;
    private javax.swing.JRadioButton jrdrBalanceSheet;
    private javax.swing.JRadioButton jrdrConsolidated;
    private javax.swing.JRadioButton jrdrCredit;
    private javax.swing.JRadioButton jrdrDebit;
    private javax.swing.JRadioButton jrdrDetail;
    private javax.swing.JRadioButton jrdrInactive;
    private javax.swing.JRadioButton jrdrIncome;
    private javax.swing.JRadioButton jrdrRetainedEarning;
    private javax.swing.JTextField jtxtAccountGroupDescription;
    private javax.swing.JTextField jtxtabrkcode;
    private javax.swing.JTextField jtxtacccode;
    private javax.swing.JTextField jtxtaccdesc;
    private javax.swing.JTextField jtxtaccfmttd;
    private javax.swing.JTextField jtxtaccountgroupcode;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtid;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {

        jtxtacccode.setText(jtxtacccode.getText().trim().replace("-", ""));
        
        obj = new Gl_account(this.jtxtacccode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Gl_account();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    private void validasi() throws CodeException {
        if (!jtxtaccountgroupcode.getText().equals("")) {
            Gl_group glp = new Gl_group(jtxtaccountgroupcode.getText());

            if(glp.getID() == Gl_group.NULLID) {
                throw new CodeException("Account Group " + jtxtaccountgroupcode.getText() + " Tidak Diketemukan");
            }

        }
        if (!jtxtaccountgroupcode.getText().equals("")) {
            Gl_account_structure glacst = new Gl_account_structure(jtxtabrkcode.getText());

            if(glacst.getID() == Gl_group.NULLID) {
                throw new CodeException("Account Structure " + jtxtabrkcode.getText() + " Tidak Diketemukan");
            }

        }
        if (!jtxtacccode.getText().equals("")) {
            Gl_account glacc = new Gl_account(jtxtacccode.getText());

            if(glacc.getID() == Gl_group.NULLID) {
                int jwb=JOptionPane.showConfirmDialog(this, "Account Code " + jtxtacccode.getText() + " Tidak Diketemukan, Tambah Baru?", "Save Data", JOptionPane.YES_NO_OPTION);
                if (jwb==JOptionPane.YES_OPTION){
                    obj.setID(obj.NULLID);
                } else {
                    undo();
                }
            }

        }

    }

    public void saveData() throws CodeException {
        
        validasi();
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
            setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Gl_account.PROPERTY_ID));
             jtxtacccode.setText(obj.toString(Gl_account.PROPERTY_ACCCODE));

             jtxtaccfmttd.setText(obj.toString(Gl_account.PROPERTY_ACCFMTTD));
             
             jtxtaccdesc.setText(obj.toString(Gl_account.PROPERTY_ACCDESC));
             
             if (obj.getaccbal() != null && obj.getaccbal().equals("1")) {
                 jrdrDebit.setSelected(true);
             }else{
                 jrdrCredit.setSelected(true);
             }

             jtxtabrkcode.setText(obj.toString(Gl_account.PROPERTY_ABRKCODE));
             
             if (obj.getacctype() != null && obj.getacctype().equals("I")) {
                 jrdrIncome.setSelected(true);
             }else if (obj.getacctype() != null && obj.getacctype().equals("B")) {
                 jrdrBalanceSheet.setSelected(true);
             }else{
                 jrdrRetainedEarning.setSelected(true);
             }

             jtxtaccountgroupcode.setText(obj.getaccgrpcode()+"");
             jtxtAccountGroupDescription.setText(obj.getAccountGroupDescription());
             
             jtxtentrydate.setText(obj.toString(Gl_account.PROPERTY_ENTRYDATE));

             if (obj.toString(Gl_account.PROPERTY_ACTIVEW) != null && obj.toString(Gl_account.PROPERTY_ACTIVEW).equalsIgnoreCase("1")){
                 jrdrActive.setSelected(true);
             } else {
                 jrdrInactive.setSelected(true);
             }
             jtxtauditdate.setText(obj.toString(Gl_account.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Gl_account.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Gl_account.PROPERTY_CMPNYID));

             setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Gl_account.PROPERTY_ACCCODE, jtxtacccode.getText()) ;
          obj.fromString(Gl_account.PROPERTY_ACCFMTTD, jtxtaccfmttd.getText()) ;

          obj.fromString(Gl_account.PROPERTY_ACCDESC, jtxtaccdesc.getText()) ;

          if (jrdrDebit.isSelected()) {
              obj.fromString(Gl_account.PROPERTY_ACCBAL, "1");
          }else{
              obj.fromString(Gl_account.PROPERTY_ACCBAL, "2");
          }

          obj.fromString(Gl_account.PROPERTY_ABRKCODE, jtxtabrkcode.getText()) ;

          if(jrdrIncome.isSelected()) {
              obj.fromString(Gl_account.PROPERTY_ACCTYPE, "I");
          }else if(jrdrBalanceSheet.isSelected()) {
              obj.fromString(Gl_account.PROPERTY_ACCTYPE, "B");
          }else {
              obj.fromString(Gl_account.PROPERTY_ACCTYPE, "R");
          }

          if (istatus==1){
              obj.fromString(Gl_account.PROPERTY_ENTRYDATE, GlobalUtils.getAuditDate()) ;
          }
          if (jrdrActive.isSelected()){
              obj.fromString(Gl_account.PROPERTY_ACTIVEW, "1") ;
          } else {
              obj.fromString(Gl_account.PROPERTY_ACTIVEW, "0") ;
          }

          obj.setaccgrpcode(jtxtaccountgroupcode.getText());

          obj.fromString(Gl_account.PROPERTY_AUDITDATE, GlobalUtils.getAuditDate()) ;
          obj.fromString(Gl_account.PROPERTY_AUDITUSER, GlobalUtils.userid) ;
          obj.fromString(Gl_account.PROPERTY_CMPNYID, GlobalUtils.company) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
//        Map parameter = new HashMap();
//        NavigatorObjectInt noi = (NavigatorObjectInt) obj;
//        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
//        GlobalUtils.printReport(file,  false);
        FrmPrintMasterGLAccountCode fprint = new FrmPrintMasterGLAccountCode();
        fprint.setVisible(true);
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
