/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.gl.FrmGl_segment;
 * 
 * .......
 * 
 * 
 * FrmGl_segment frmGl_segment;
 * 
 * .......
 * 
 try {
        if (frmGl_segment == null) {
            frmmGl_segment = new FrmGl_segment(this);
        }
        
        showForm(frmGl_segment);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.gl;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.gl.Gl_segment;
import accapp.objectclasses.gl.Gl_segments;

/**
 *
 * @author  Generator
 */

public class FrmGl_segment extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmGl_segment";
    
    FrmMainFrame mf ;
    
    
    public Gl_segment obj = new Gl_segment();
    
   
    /** Creates new form Area */
    public FrmGl_segment() throws CodeException {
        initComponents();
    }
    
    public FrmGl_segment(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();

        
         jlblid = new javax.swing.JLabel(); 
         jtxtid = new javax.swing.JTextField(); 
         jlblaccsgmncode = new javax.swing.JLabel(); 
         jtxtaccsgmncode = new javax.swing.JTextField(); 
         jlblactive = new javax.swing.JLabel(); 
         jtxtactive = new javax.swing.JTextField(); 
         jlblsgmntype = new javax.swing.JLabel(); 
         jtxtsgmntype = new javax.swing.JTextField(); 
         jlblsgmndesc = new javax.swing.JLabel(); 
         jtxtsgmndesc = new javax.swing.JTextField(); 
         jlblsgmnlen = new javax.swing.JLabel(); 
         jtxtsgmnlen = new javax.swing.JTextField(); 
         jlblablkdelm = new javax.swing.JLabel(); 
         jtxtablkdelm = new javax.swing.JTextField(); 
         jlblsgmnpost = new javax.swing.JLabel(); 
         jtxtsgmnpost = new javax.swing.JTextField(); 
         jlblentrydate = new javax.swing.JLabel(); 
         jtxtentrydate = new javax.swing.JTextField(); 
         jlblauditdate = new javax.swing.JLabel(); 
         jtxtauditdate = new javax.swing.JTextField(); 
         jlblaudituser = new javax.swing.JLabel(); 
         jtxtaudituser = new javax.swing.JTextField(); 
         jlblcmpnyid = new javax.swing.JLabel(); 
         jtxtcmpnyid = new javax.swing.JTextField(); 

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gl_segment");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Gl_segment");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(350, 100, 30, 20);

	
         jlblid.setText("id"); 
         getContentPane().add(jlblid); 
         jlblid.setBounds(70, 80, 140, 15); 
         jtxtid.setText("jtxtid"); 
         getContentPane().add(jtxtid); 
         jtxtid.setBounds(260, 80, 80, 19); 
         jlblaccsgmncode.setText("accsgmncode"); 
         getContentPane().add(jlblaccsgmncode); 
         jlblaccsgmncode.setBounds(70, 100, 140, 15); 
         jtxtaccsgmncode.setText("jtxtaccsgmncode"); 
         getContentPane().add(jtxtaccsgmncode); 
         jtxtaccsgmncode.setBounds(260, 100, 80, 19); 
         jlblactive.setText("active"); 
         getContentPane().add(jlblactive); 
         jlblactive.setBounds(70, 120, 140, 15); 
         jtxtactive.setText("jtxtactive"); 
         getContentPane().add(jtxtactive); 
         jtxtactive.setBounds(260, 120, 80, 19); 
         jlblsgmntype.setText("sgmntype"); 
         getContentPane().add(jlblsgmntype); 
         jlblsgmntype.setBounds(70, 140, 140, 15); 
         jtxtsgmntype.setText("jtxtsgmntype"); 
         getContentPane().add(jtxtsgmntype); 
         jtxtsgmntype.setBounds(260, 140, 80, 19); 
         jlblsgmndesc.setText("sgmndesc"); 
         getContentPane().add(jlblsgmndesc); 
         jlblsgmndesc.setBounds(70, 160, 140, 15); 
         jtxtsgmndesc.setText("jtxtsgmndesc"); 
         getContentPane().add(jtxtsgmndesc); 
         jtxtsgmndesc.setBounds(260, 160, 80, 19); 
         jlblsgmnlen.setText("sgmnlen"); 
         getContentPane().add(jlblsgmnlen); 
         jlblsgmnlen.setBounds(70, 180, 140, 15); 
         jtxtsgmnlen.setText("jtxtsgmnlen"); 
         getContentPane().add(jtxtsgmnlen); 
         jtxtsgmnlen.setBounds(260, 180, 80, 19); 
         jlblablkdelm.setText("ablkdelm"); 
         getContentPane().add(jlblablkdelm); 
         jlblablkdelm.setBounds(70, 200, 140, 15); 
         jtxtablkdelm.setText("jtxtablkdelm"); 
         getContentPane().add(jtxtablkdelm); 
         jtxtablkdelm.setBounds(260, 200, 80, 19); 
         jlblsgmnpost.setText("sgmnpost"); 
         getContentPane().add(jlblsgmnpost); 
         jlblsgmnpost.setBounds(70, 220, 140, 15); 
         jtxtsgmnpost.setText("jtxtsgmnpost"); 
         getContentPane().add(jtxtsgmnpost); 
         jtxtsgmnpost.setBounds(260, 220, 80, 19); 
         jlblentrydate.setText("entrydate"); 
         getContentPane().add(jlblentrydate); 
         jlblentrydate.setBounds(70, 240, 140, 15); 
         jtxtentrydate.setText("jtxtentrydate"); 
         getContentPane().add(jtxtentrydate); 
         jtxtentrydate.setBounds(260, 240, 80, 19); 
         jlblauditdate.setText("auditdate"); 
         getContentPane().add(jlblauditdate); 
         jlblauditdate.setBounds(70, 260, 140, 15); 
         jtxtauditdate.setText("jtxtauditdate"); 
         getContentPane().add(jtxtauditdate); 
         jtxtauditdate.setBounds(260, 260, 80, 19); 
         jlblaudituser.setText("audituser"); 
         getContentPane().add(jlblaudituser); 
         jlblaudituser.setBounds(70, 280, 140, 15); 
         jtxtaudituser.setText("jtxtaudituser"); 
         getContentPane().add(jtxtaudituser); 
         jtxtaudituser.setBounds(260, 280, 80, 19); 
         jlblcmpnyid.setText("cmpnyid"); 
         getContentPane().add(jlblcmpnyid); 
         jlblcmpnyid.setBounds(70, 300, 140, 15); 
         jtxtcmpnyid.setText("jtxtcmpnyid"); 
         getContentPane().add(jtxtcmpnyid); 
         jtxtcmpnyid.setBounds(260, 300, 80, 19); 

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Gl_segments brs = new Gl_segments();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtaccsgmncode);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmGl_segment().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3; 
    private javax.swing.JButton jbtnBrowse;

    
      private javax.swing.JLabel jlblid;  
      private javax.swing.JTextField jtxtid; 
      private javax.swing.JLabel jlblaccsgmncode;  
      private javax.swing.JTextField jtxtaccsgmncode; 
      private javax.swing.JLabel jlblactive;  
      private javax.swing.JTextField jtxtactive; 
      private javax.swing.JLabel jlblsgmntype;  
      private javax.swing.JTextField jtxtsgmntype; 
      private javax.swing.JLabel jlblsgmndesc;  
      private javax.swing.JTextField jtxtsgmndesc; 
      private javax.swing.JLabel jlblsgmnlen;  
      private javax.swing.JTextField jtxtsgmnlen; 
      private javax.swing.JLabel jlblablkdelm;  
      private javax.swing.JTextField jtxtablkdelm; 
      private javax.swing.JLabel jlblsgmnpost;  
      private javax.swing.JTextField jtxtsgmnpost; 
      private javax.swing.JLabel jlblentrydate;  
      private javax.swing.JTextField jtxtentrydate; 
      private javax.swing.JLabel jlblauditdate;  
      private javax.swing.JTextField jtxtauditdate; 
      private javax.swing.JLabel jlblaudituser;  
      private javax.swing.JTextField jtxtaudituser; 
      private javax.swing.JLabel jlblcmpnyid;  
      private javax.swing.JTextField jtxtcmpnyid; 

    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Gl_segment(this.jtxtaccsgmncode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Gl_segment();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Gl_segment.PROPERTY_ID));
             jtxtaccsgmncode.setText(obj.toString(Gl_segment.PROPERTY_ACCSGMNCODE));
             jtxtactive.setText(obj.toString(Gl_segment.PROPERTY_ACTIVE));
             jtxtsgmntype.setText(obj.toString(Gl_segment.PROPERTY_SGMNTYPE));
             jtxtsgmndesc.setText(obj.toString(Gl_segment.PROPERTY_SGMNDESC));
             jtxtsgmnlen.setText(obj.toString(Gl_segment.PROPERTY_SGMNLEN));
             jtxtablkdelm.setText(obj.toString(Gl_segment.PROPERTY_ABLKDELM));
             jtxtsgmnpost.setText(obj.toString(Gl_segment.PROPERTY_SGMNPOST));
             jtxtentrydate.setText(obj.toString(Gl_segment.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Gl_segment.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Gl_segment.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Gl_segment.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Gl_segment.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_ACCSGMNCODE, jtxtaccsgmncode.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_ACTIVE, jtxtactive.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_SGMNTYPE, jtxtsgmntype.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_SGMNDESC, jtxtsgmndesc.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_SGMNLEN, jtxtsgmnlen.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_ABLKDELM, jtxtablkdelm.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_SGMNPOST, jtxtsgmnpost.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Gl_segment.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
