/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import test.FrmSetting_financial_rpt_detail1;
 * 
 * .......
 * 
 * 
 * FrmSetting_financial_rpt_detail1 frmSetting_financial_rpt_detail1;
 * 
 * .......
 * 
 try {
        if (frmSetting_financial_rpt_detail1 == null) {
            frmmSetting_financial_rpt_detail1 = new FrmSetting_financial_rpt_detail1(this);
        }
        
        showForm(frmSetting_financial_rpt_detail1);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.gl;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.gl.Setting_financial_rpt_detail1;
import accapp.objectclasses.gl.Setting_financial_rpt_detail1;
import accapp.objectclasses.gl.Setting_financial_rpt_detail1s;
import accapp.objectclasses.gl.Setting_financial_rpt_detail1s;

/**
 *
 * @author  Generator
 */

public class FrmSetting_financial_rpt_detail1 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmSetting_financial_rpt_detail1";
    
    FrmMainFrame mf ;
    
    
    public Setting_financial_rpt_detail1 obj = new Setting_financial_rpt_detail1();
    
   
    /** Creates new form Area */
    public FrmSetting_financial_rpt_detail1() throws CodeException {
        initComponents();
    }
    
    public FrmSetting_financial_rpt_detail1(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblid = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jlbldocentry = new javax.swing.JLabel();
        jtxtdocentry = new javax.swing.JTextField();
        jlbllineno = new javax.swing.JLabel();
        jtxtlineno = new javax.swing.JTextField();
        jlblrowno = new javax.swing.JLabel();
        jtxtrowno = new javax.swing.JTextField();
        jlblcolumntype = new javax.swing.JLabel();
        jtxtcolumntype = new javax.swing.JTextField();
        jlbllevelno = new javax.swing.JLabel();
        jtxtlevelno = new javax.swing.JTextField();
        jlbltextheader = new javax.swing.JLabel();
        jtxttextheader = new javax.swing.JTextField();
        jlblallowformulation = new javax.swing.JLabel();
        jtxtallowformulation = new javax.swing.JTextField();
        jlblsummary = new javax.swing.JLabel();
        jtxtsummary = new javax.swing.JTextField();
        jlbltextformulation = new javax.swing.JLabel();
        jtxttextformulation = new javax.swing.JTextField();
        jlblvisorder = new javax.swing.JLabel();
        jtxtvisorder = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting_financial_rpt_detail1");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Setting_financial_rpt_detail1");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(430, 80, 30, 17);

        jlblid.setText("id");
        getContentPane().add(jlblid);
        jlblid.setBounds(70, 80, 140, 14);

        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(260, 80, 80, 20);

        jlbldocentry.setText("docentry");
        getContentPane().add(jlbldocentry);
        jlbldocentry.setBounds(70, 100, 140, 14);

        jtxtdocentry.setText("docentry");
        getContentPane().add(jtxtdocentry);
        jtxtdocentry.setBounds(260, 100, 80, 20);

        jlbllineno.setText("lineno");
        getContentPane().add(jlbllineno);
        jlbllineno.setBounds(70, 120, 140, 14);

        jtxtlineno.setText("lineno");
        getContentPane().add(jtxtlineno);
        jtxtlineno.setBounds(260, 120, 80, 20);

        jlblrowno.setText("rowno");
        getContentPane().add(jlblrowno);
        jlblrowno.setBounds(70, 140, 140, 14);

        jtxtrowno.setText("rowno");
        getContentPane().add(jtxtrowno);
        jtxtrowno.setBounds(260, 140, 80, 20);

        jlblcolumntype.setText("columntype");
        getContentPane().add(jlblcolumntype);
        jlblcolumntype.setBounds(70, 160, 140, 14);

        jtxtcolumntype.setText("columntype");
        getContentPane().add(jtxtcolumntype);
        jtxtcolumntype.setBounds(260, 160, 80, 20);

        jlbllevelno.setText("levelno");
        getContentPane().add(jlbllevelno);
        jlbllevelno.setBounds(70, 180, 140, 14);

        jtxtlevelno.setText("levelno");
        getContentPane().add(jtxtlevelno);
        jtxtlevelno.setBounds(260, 180, 80, 20);

        jlbltextheader.setText("textheader");
        getContentPane().add(jlbltextheader);
        jlbltextheader.setBounds(70, 200, 140, 14);

        jtxttextheader.setText("textheader");
        getContentPane().add(jtxttextheader);
        jtxttextheader.setBounds(260, 200, 80, 20);

        jlblallowformulation.setText("allowformulation");
        getContentPane().add(jlblallowformulation);
        jlblallowformulation.setBounds(70, 220, 140, 14);

        jtxtallowformulation.setText("allowformulation");
        getContentPane().add(jtxtallowformulation);
        jtxtallowformulation.setBounds(260, 220, 80, 20);

        jlblsummary.setText("summary");
        getContentPane().add(jlblsummary);
        jlblsummary.setBounds(70, 240, 140, 14);

        jtxtsummary.setText("summary");
        getContentPane().add(jtxtsummary);
        jtxtsummary.setBounds(260, 240, 80, 20);

        jlbltextformulation.setText("textformulation");
        getContentPane().add(jlbltextformulation);
        jlbltextformulation.setBounds(70, 260, 140, 14);

        jtxttextformulation.setText("textformulation");
        getContentPane().add(jtxttextformulation);
        jtxttextformulation.setBounds(260, 260, 80, 20);

        jlblvisorder.setText("visorder");
        getContentPane().add(jlblvisorder);
        jlblvisorder.setBounds(70, 280, 140, 14);

        jtxtvisorder.setText("visorder");
        getContentPane().add(jtxtvisorder);
        jtxtvisorder.setBounds(260, 280, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Setting_financial_rpt_detail1s brs = new Setting_financial_rpt_detail1s();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtlineno);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmSetting_financial_rpt_detail1().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblallowformulation;
    private javax.swing.JLabel jlblcolumntype;
    private javax.swing.JLabel jlbldocentry;
    private javax.swing.JLabel jlblid;
    private javax.swing.JLabel jlbllevelno;
    private javax.swing.JLabel jlbllineno;
    private javax.swing.JLabel jlblrowno;
    private javax.swing.JLabel jlblsummary;
    private javax.swing.JLabel jlbltextformulation;
    private javax.swing.JLabel jlbltextheader;
    private javax.swing.JLabel jlblvisorder;
    private javax.swing.JTextField jtxtallowformulation;
    private javax.swing.JTextField jtxtcolumntype;
    private javax.swing.JTextField jtxtdocentry;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtlevelno;
    private javax.swing.JTextField jtxtlineno;
    private javax.swing.JTextField jtxtrowno;
    private javax.swing.JTextField jtxtsummary;
    private javax.swing.JTextField jtxttextformulation;
    private javax.swing.JTextField jtxttextheader;
    private javax.swing.JTextField jtxtvisorder;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Setting_financial_rpt_detail1(this.jtxtlineno.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Setting_financial_rpt_detail1();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_ID));
             jtxtdocentry.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_DOCENTRY));
             jtxtlineno.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_LINENO));
             jtxtrowno.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_ROWNO));
             jtxtcolumntype.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_COLUMNTYPE));
             jtxtlevelno.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_LEVELNO));
             jtxttextheader.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_TEXTHEADER));
             jtxtallowformulation.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_ALLOWFORMULATION));
             jtxtsummary.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_SUMMARY));
             jtxttextformulation.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_TEXTFORMULATION));
             jtxtvisorder.setText(obj.toString(Setting_financial_rpt_detail1.PROPERTY_VISORDER));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_DOCENTRY, jtxtdocentry.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_LINENO, jtxtlineno.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_ROWNO, jtxtrowno.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_COLUMNTYPE, jtxtcolumntype.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_LEVELNO, jtxtlevelno.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_TEXTHEADER, jtxttextheader.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_ALLOWFORMULATION, jtxtallowformulation.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_SUMMARY, jtxtsummary.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_TEXTFORMULATION, jtxttextformulation.getText()) ;
          obj.fromString(Setting_financial_rpt_detail1.PROPERTY_VISORDER, jtxtvisorder.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
