/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.objectclasses.gl.Setting_financial_rpts;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;


/**
 *
 * @author  wgata
 */
public class FrmPrintMasterGLFinancialSettingReport extends javax.swing.JDialog {
    
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintMasterGLFinancialSettingReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintMasterGLFinancialSettingReport() {
        initComponents();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblHeader = new javax.swing.JLabel();
        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtNoBatchFr = new javax.swing.JTextField();
        jbtnBatchFr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRINT GL -FINANCIAL MASTER SETTING  REPORT");
        getContentPane().setLayout(null);

        jlblHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("GL - FINANCIAL MASTER SETTING REPORT");
        jlblHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlblHeader);
        jlblHeader.setBounds(30, 20, 360, 30);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnCetak.setText("Print");
        jbtnCetak.setName("FrmPrintTransaksiGLJournal"); // NOI18N
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(140, 110, 70, 20);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(220, 110, 70, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel5.setText("Laporan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 70, 50, 20);

        jtxtNoBatchFr.setFont(new java.awt.Font("Dialog", 0, 10));
        getContentPane().add(jtxtNoBatchFr);
        jtxtNoBatchFr.setBounds(90, 70, 280, 20);

        jbtnBatchFr.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBatchFr.setText("...");
        jbtnBatchFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBatchFrActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBatchFr);
        jbtnBatchFr.setBounds(370, 70, 20, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-422)/2, (screenSize.height-186)/2, 422, 186);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed


                    try{
                        String file   = "" ;
                        Map parameter = new HashMap();

                        parameter.put("jdlrpt",jtxtNoBatchFr.getText());
                        parameter.put("operator",GlobalUtils.userid);

                        System.out.println(jtxtNoBatchFr.getText());
                        System.out.println(GlobalUtils.userid);


                        file = GlobalUtils.getCurrentDir() +"/Reports/MasterGLFinancialSettingReport.jrxml";
                        GlobalUtils.printReport(file, parameter, false);

                    }catch (Exception e) {
                        e.printStackTrace();
                    }


   
    
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jbtnBatchFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBatchFrActionPerformed
    try {
	    Setting_financial_rpts brs = new Setting_financial_rpts();
	    FrmBrowse bd = new FrmBrowse(brs);
            bd.setFirstValue(jtxtNoBatchFr);
            bd.setModal(true);
            bd.setVisible(true);


    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBatchFrActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintMasterGLFinancialSettingReport dialog = new FrmPrintMasterGLFinancialSettingReport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnBatchFr;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    public javax.swing.JLabel jlblHeader;
    public javax.swing.JTextField jtxtNoBatchFr;
    // End of variables declaration//GEN-END:variables

}
