/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.component.browse.FrmBrowseAPVendor;
import accapp.objectclasses.ap.Ap_accsets;
import accapp.objectclasses.ap.Ap_vendors;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;


/**
 *
 * @author  wgata
 */
public class FrmPrintTransaksiAPAged extends javax.swing.JDialog {
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");

    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintTransaksiAPAged(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintTransaksiAPAged() {

        initComponents();
        jcmbBulan.setVisible(false);
        jtxtyopfr.setVisible(false);
        jtxtyopfr.setText((new Date()).getYear() + 1900 +"");

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtNoBatchFr = new javax.swing.JTextField();
        jlblHeader = new javax.swing.JLabel();
        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtxtNoBatchTo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtyopfr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcmbjenislaporan = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jcmbBulan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jtxtaccsetfr = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtxtaccsetto = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jcmbFormat = new javax.swing.JComboBox();
        kDateAgeAsOf = new org.kazao.calendar.KazaoCalendarDate();
        jLabel7 = new javax.swing.JLabel();
        jcmbCuttOf = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        kDateCuttOf = new org.kazao.calendar.KazaoCalendarDate();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcmbstatusvendor = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AP Aging Report");
        getContentPane().setLayout(null);

        jtxtNoBatchFr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtNoBatchFr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtNoBatchFr);
        jtxtNoBatchFr.setBounds(150, 210, 100, 20);

        jlblHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("AP - AGING REPORT");
        jlblHeader.setToolTipText("FrmPrintTransaksiAPAged");
        jlblHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlblHeader);
        jlblHeader.setBounds(10, 10, 490, 50);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnCetak.setText("Print");
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(80, 350, 90, 23);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(310, 350, 90, 23);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 10));
        jButton1.setText("...");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 210, 20, 20);

        jtxtNoBatchTo.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtNoBatchTo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtNoBatchTo);
        jtxtNoBatchTo.setBounds(310, 210, 100, 20);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 10));
        jButton2.setText("...");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 210, 20, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Age As Of");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 110, 20);

        jtxtyopfr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyopfr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtyopfr);
        jtxtyopfr.setBounds(150, 180, 50, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Report Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 270, 110, 20);

        jcmbjenislaporan.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbjenislaporan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Detail", "Summary" }));
        jcmbjenislaporan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcmbjenislaporan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbjenislaporanItemStateChanged(evt);
            }
        });
        jcmbjenislaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbjenislaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbjenislaporan);
        jcmbjenislaporan.setBounds(150, 270, 120, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel9.setText("To");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 210, 20, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcmbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBulanItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(210, 180, 50, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Accset Code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 240, 110, 20);

        jtxtaccsetfr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccsetfr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtaccsetfr);
        jtxtaccsetfr.setBounds(150, 240, 100, 20);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 10));
        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 240, 20, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel10.setText("To");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 240, 20, 20);

        jtxtaccsetto.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccsetto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtaccsetto);
        jtxtaccsetto.setBounds(310, 240, 100, 20);

        jButton4.setFont(new java.awt.Font("Dialog", 0, 10));
        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 240, 20, 20);

        jcmbFormat.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aged Payable by Doc. Date", "Aged Payable by DueDate", "Aged Payable by Over Doc. Date", "Aged Payable by Over Due Date" }));
        getContentPane().add(jcmbFormat);
        jcmbFormat.setBounds(150, 80, 240, 22);
        getContentPane().add(kDateAgeAsOf);
        kDateAgeAsOf.setBounds(150, 120, 120, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Vendor Code");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 210, 110, 20);

        jcmbCuttOf.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbCuttOf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doc. Date", "Periode (mm/yyyy)" }));
        jcmbCuttOf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbCuttOfItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbCuttOf);
        jcmbCuttOf.setBounds(150, 150, 120, 22);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cutt Of by");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 110, 14);
        getContentPane().add(kDateCuttOf);
        kDateCuttOf.setBounds(290, 150, 96, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Format");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 110, 14);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Vendor Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 300, 110, 20);

        jcmbstatusvendor.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbstatusvendor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Active", "Non Active" }));
        jcmbstatusvendor.setSelectedIndex(1);
        jcmbstatusvendor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcmbstatusvendor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbstatusvendorItemStateChanged(evt);
            }
        });
        jcmbstatusvendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbstatusvendorActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbstatusvendor);
        jcmbstatusvendor.setBounds(150, 300, 120, 20);

        jButton5.setFont(new java.awt.Font("Dialog", 0, 10));
        jButton5.setText("Exp.csv");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 350, 100, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-520)/2, (screenSize.height-442)/2, 520, 442);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed
        
    try{
        setCursor(GlobalUtils.HOURGLASSCURSOR);
        String mop=(jcmbBulan.getSelectedIndex()+1 <10 ? "0"+(jcmbBulan.getSelectedIndex()+1)+"" : (jcmbBulan.getSelectedIndex()+1) +"");
        String format=(jcmbFormat.getSelectedIndex()+"");
        Map parameter = new HashMap();
        parameter.put("operator", (GlobalUtils.getUserId()));
        parameter.put("namaPT", (GlobalUtils.getNamaPT()));

        String vendfr=jtxtNoBatchFr.getText();
        String vendto=jtxtNoBatchTo.getText();
        if(jtxtNoBatchFr.getText().isEmpty()){
            vendfr="0";
        }
        if(jtxtNoBatchTo.getText().isEmpty()){
            vendto="ZZZZZZZ";
        }
        parameter.put("vendnofr", vendfr);
        parameter.put("vendnoto", vendto);
        String accsetfr= jtxtaccsetfr.getText();
        String accsetto= jtxtaccsetto.getText();
        if(jtxtaccsetfr.getText().isEmpty()){
            accsetfr="0";
        }
        if(jtxtaccsetto.getText().isEmpty()){
            accsetto="ZZZZZZZ";
        }
        parameter.put("accsetcodefr",accsetfr);
        parameter.put("accsetcodeto",accsetto);
        parameter.put("yop", jtxtyopfr.getText());
        parameter.put("mop", mop);
        parameter.put("format", format);
        parameter.put("docdate",dateformatprint.format(dateformat.parse(kDateCuttOf.getDate())));
        parameter.put("cutoffby",jcmbCuttOf.getSelectedIndex()+"");
        parameter.put("ageasof", dateformatprint.format(dateformat.parse(kDateAgeAsOf.getDate())));

        String act  = " ";
        String non = " " ;
        if(jcmbstatusvendor.getSelectedIndex()==0){
                non="0";
                act="1";
        }else {
                   if(jcmbstatusvendor.getSelectedIndex()==1){
                            non="N";
                            act="1";
                   }else {
                             non="0";
                             act="A";
                   }
        }
        parameter.put("aktifsts",act);
        parameter.put("nonaktifsts",non);
        System.out.print(parameter);
        String file   = "";

        
        if(jcmbFormat.getSelectedIndex()==0 ||jcmbFormat.getSelectedIndex()==1){
            if(jcmbjenislaporan.getSelectedIndex()==0){
                file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedDetail.jrxml";
                System.out.print(file);
            }else{
                file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedSummary.jrxml";
                System.out.print(file);
            }
        }else{
            if(jcmbjenislaporan.getSelectedIndex()==0){
                 file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedDetailOverdue.jrxml";
                 System.out.print(file);
            }else{
                file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedSummaryOverdue.jrxml";
                System.out.print(file);
            }
        }

        GlobalUtils.printReport(file, parameter, false);
    }catch (Exception e) {
        e.printStackTrace();
    }
    setCursor(GlobalUtils.NORMALCURSOR);
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
	      Ap_vendors brs = new Ap_vendors();
	      FrmBrowseAPVendor bd = new FrmBrowseAPVendor(brs);
	      bd.setFirstValue(jtxtNoBatchFr);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
	      Ap_vendors brs = new Ap_vendors();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtNoBatchTo);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jButton2ActionPerformed

private void jcmbjenislaporanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbjenislaporanItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbjenislaporanItemStateChanged

private void jcmbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBulanItemStateChanged

}//GEN-LAST:event_jcmbBulanItemStateChanged

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
        Ap_accsets brs = new Ap_accsets();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtaccsetfr);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
        Ap_accsets brs = new Ap_accsets();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtaccsetto);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jcmbCuttOfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbCuttOfItemStateChanged

    if(jcmbCuttOf.getSelectedIndex()==0){
        jcmbBulan.setVisible(false);
        jtxtyopfr.setVisible(false);
        kDateCuttOf.setVisible(true);

    }else{
        jcmbBulan.setVisible(true);
        jtxtyopfr.setVisible(true);
        kDateCuttOf.setVisible(false);
    }
}//GEN-LAST:event_jcmbCuttOfItemStateChanged

private void jcmbstatusvendorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbstatusvendorItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbstatusvendorItemStateChanged

private void jcmbjenislaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbjenislaporanActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbjenislaporanActionPerformed

private void jcmbstatusvendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbstatusvendorActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbstatusvendorActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try{
        setCursor(GlobalUtils.HOURGLASSCURSOR);
        String mop=(jcmbBulan.getSelectedIndex()+1 <10 ? "0"+(jcmbBulan.getSelectedIndex()+1)+"" : (jcmbBulan.getSelectedIndex()+1) +"");
        String format=(jcmbFormat.getSelectedIndex()+"");
        Map parameter = new HashMap();
        parameter.put("operator", (GlobalUtils.getUserId()));
        parameter.put("namaPT", (GlobalUtils.getNamaPT()));

        String vendfr=jtxtNoBatchFr.getText();
        String vendto=jtxtNoBatchTo.getText();
        if(jtxtNoBatchFr.getText().isEmpty()){
            vendfr="0";
        }
        if(jtxtNoBatchTo.getText().isEmpty()){
            vendto="ZZZZZZZ";
        }
        parameter.put("vendnofr", vendfr);
        parameter.put("vendnoto", vendto);
        String accsetfr= jtxtaccsetfr.getText();
        String accsetto= jtxtaccsetto.getText();
        if(jtxtNoBatchFr.getText().isEmpty()){
            accsetfr="0";
        }
        if(jtxtNoBatchTo.getText().isEmpty()){
            accsetto="ZZZZZZZ";
        }
        parameter.put("accsetcodefr",accsetfr);
        parameter.put("accsetcodeto",accsetto);
        parameter.put("yop", jtxtyopfr.getText());
        parameter.put("mop", mop);
        parameter.put("format", format);
        parameter.put("docdate",dateformatprint.format(dateformat.parse(kDateCuttOf.getDate())));
        parameter.put("cutoffby",jcmbCuttOf.getSelectedIndex()+"");
        parameter.put("ageasof", dateformatprint.format(dateformat.parse(kDateAgeAsOf.getDate())));

        String act  = " ";
        String non = " " ;
        if(jcmbstatusvendor.getSelectedIndex()==0){
                non="0";
                act="1";
        }else {
                   if(jcmbstatusvendor.getSelectedIndex()==1){
                            non="N";
                            act="1";
                   }else {
                             non="0";
                             act="A";
                   }
        }
        parameter.put("aktifsts",act);
        parameter.put("nonaktifsts",non);
        System.out.print(parameter);
        String file   = "";

        if(jcmbFormat.getSelectedIndex()==0 ||jcmbFormat.getSelectedIndex()==1){
            if(jcmbjenislaporan.getSelectedIndex()==0){
                file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedDetailExp.jrxml";
                System.out.print(file);
            }else{
                file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedSummaryExp.jrxml";
                System.out.print(file);
            }
        }else{
            if(jcmbjenislaporan.getSelectedIndex()==0){
                 file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedDetailOverdueExp.jrxml";
                 System.out.print(file);
            }else{
                file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiAPAgedSummaryOverdueExp.jrxml";
                System.out.print(file);
            }
        }

        GlobalUtils.printReport(file, parameter, false);
    }catch (Exception e) {
        e.printStackTrace();
    }
    setCursor(GlobalUtils.NORMALCURSOR);
}//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintTransaksiAPAged dialog = new FrmPrintTransaksiAPAged(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbCuttOf;
    private javax.swing.JComboBox jcmbFormat;
    private javax.swing.JComboBox jcmbjenislaporan;
    private javax.swing.JComboBox jcmbstatusvendor;
    public javax.swing.JLabel jlblHeader;
    public javax.swing.JTextField jtxtNoBatchFr;
    public javax.swing.JTextField jtxtNoBatchTo;
    public javax.swing.JTextField jtxtaccsetfr;
    public javax.swing.JTextField jtxtaccsetto;
    public javax.swing.JTextField jtxtyopfr;
    private org.kazao.calendar.KazaoCalendarDate kDateAgeAsOf;
    private org.kazao.calendar.KazaoCalendarDate kDateCuttOf;
    // End of variables declaration//GEN-END:variables

}
