/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.objectclasses.gl.Gl_batchlists;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Calendar;


/**
 *
 * @author  wgata
 */
public class FrmPrintTransaksiGLJournal extends javax.swing.JDialog {
    
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintTransaksiGLJournal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintTransaksiGLJournal() {
        initComponents();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jcmbSourceLedgerto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jcmbSourceLedgerfr = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcmbHavingStatusfr = new javax.swing.JComboBox();
        jcmbHavingStatusto = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcmbBatchTypefr = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jcmbBatchTypeto = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jtxtNoBatchFr = new javax.swing.JTextField();
        jbtnBatchFr = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxtNoBatchTo = new javax.swing.JTextField();
        jbtnBatchTo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcmbCuttOf = new javax.swing.JComboBox();
        jtxtyopfr = new javax.swing.JTextField();
        jcmbBulan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report: GL-Transaction Batch Listing");
        setResizable(false);
        getContentPane().setLayout(null);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jbtnCetak.setText("Print");
        jbtnCetak.setToolTipText("Print (tanpa halaman)");
        jbtnCetak.setName("FrmPrintTransaksiGLJournal"); // NOI18N
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(140, 330, 80, 24);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 0, 11));
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(270, 330, 80, 24);

        jLabel8.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel8.setText("To");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 220, 20, 20);

        jcmbSourceLedgerto.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbSourceLedgerto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AP", "AR", "CB", "GL" }));
        jcmbSourceLedgerto.setSelectedIndex(3);
        jcmbSourceLedgerto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbSourceLedgerto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbSourceLedgertoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbSourceLedgerto);
        jcmbSourceLedgerto.setBounds(310, 220, 110, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setText("Period");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 180, 100, 20);

        jcmbSourceLedgerfr.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbSourceLedgerfr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AP", "AR", "CB", "GL" }));
        jcmbSourceLedgerfr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbSourceLedgerfr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbSourceLedgerfrItemStateChanged(evt);
            }
        });
        jcmbSourceLedgerfr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbSourceLedgerfrActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbSourceLedgerfr);
        jcmbSourceLedgerfr.setBounds(140, 220, 130, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setText("Having Of Status");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 100, 20);

        jcmbHavingStatusfr.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbHavingStatusfr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open", "Posted", "Error", "Deleted", "Prov. Posted" }));
        jcmbHavingStatusfr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbHavingStatusfr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbHavingStatusfrItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbHavingStatusfr);
        jcmbHavingStatusfr.setBounds(140, 250, 130, 20);

        jcmbHavingStatusto.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbHavingStatusto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open", "Posted", "Error", "Deleted", "Prov. Posted" }));
        jcmbHavingStatusto.setSelectedIndex(4);
        jcmbHavingStatusto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbHavingStatusto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbHavingStatustoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbHavingStatusto);
        jcmbHavingStatusto.setBounds(310, 250, 110, 20);

        jLabel10.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel10.setText("To");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 250, 20, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel5.setText("Batch Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 280, 100, 20);

        jcmbBatchTypefr.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbBatchTypefr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entered", "Subledger", "Imported", "Generated" }));
        jcmbBatchTypefr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbBatchTypefr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBatchTypefrItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBatchTypefr);
        jcmbBatchTypefr.setBounds(140, 280, 130, 20);

        jLabel11.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel11.setText("To");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 280, 20, 20);

        jcmbBatchTypeto.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbBatchTypeto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entered", "Subledger", "Imported", "Generated" }));
        jcmbBatchTypeto.setSelectedIndex(3);
        jcmbBatchTypeto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbBatchTypeto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBatchTypetoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBatchTypeto);
        jcmbBatchTypeto.setBounds(310, 280, 110, 20);

        jLabel6.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel6.setText("Cut Of By");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 90, 100, 20);

        jtxtNoBatchFr.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        getContentPane().add(jtxtNoBatchFr);
        jtxtNoBatchFr.setBounds(140, 120, 110, 20);

        jbtnBatchFr.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jbtnBatchFr.setText("...");
        jbtnBatchFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBatchFrActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBatchFr);
        jbtnBatchFr.setBounds(250, 120, 20, 20);

        jLabel12.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel12.setText("To");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 120, 20, 20);

        jtxtNoBatchTo.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        getContentPane().add(jtxtNoBatchTo);
        jtxtNoBatchTo.setBounds(310, 120, 90, 20);

        jbtnBatchTo.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jbtnBatchTo.setText("...");
        jbtnBatchTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBatchToActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBatchTo);
        jbtnBatchTo.setBounds(400, 120, 20, 20);

        jLabel7.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel7.setText("Batch");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 120, 100, 20);

        jcmbCuttOf.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbCuttOf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Batch Number", "Periode" }));
        jcmbCuttOf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbCuttOfItemStateChanged(evt);
            }
        });
        jcmbCuttOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCuttOfActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbCuttOf);
        jcmbCuttOf.setBounds(140, 90, 150, 20);

        jtxtyopfr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyopfr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtyopfr);
        jtxtyopfr.setBounds(200, 180, 60, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcmbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBulanItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(140, 180, 50, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel2.setText("Source Ledger");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 220, 100, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("GL - TRANSACTION BATCH LISTING");
        jLabel13.setToolTipText("FrmPrintTransaksiGLJournal:TransaksiGLBatchList.jrxml");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 20, 440, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-462)/2, (screenSize.height-402)/2, 462, 402);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed
        
    try{
        setCursor(GlobalUtils.HOURGLASSCURSOR);
        String file = "" ;
        String mop=(jcmbBulan.getSelectedIndex()+1 <10 ? "0"+(jcmbBulan.getSelectedIndex()+1)+"" : (jcmbBulan.getSelectedIndex()+1) +"");
        Map parameter = new HashMap();

        parameter.put("namaPT", (GlobalUtils.getNamaPT()));
        int cutoffby= 0 ;
        if(jcmbCuttOf.getSelectedIndex()==0){
               parameter.put("batchnofr", jtxtNoBatchFr.getText());
               parameter.put("batchnoto", jtxtNoBatchTo.getText());
               parameter.put("yop","2012");
               parameter.put("mop", "7");
        }else if(jcmbCuttOf.getSelectedIndex()==1){
               parameter.put("batchnofr", "1");
               parameter.put("batchnoto", "999999999999");
               parameter.put("yop",jtxtyopfr.getText());
               parameter.put("mop",mop);
        }

       parameter.put("cutoffby",jcmbCuttOf.getSelectedIndex());
       parameter.put("operator",GlobalUtils.userid);

       String slfr="";
        if(jcmbSourceLedgerfr.getSelectedIndex()==0 ){
            slfr="AP";
        }else if(jcmbSourceLedgerfr.getSelectedIndex()==1){
            slfr="AR";
        }
        parameter.put("srceledgrfr", slfr);

        String slto="";
        if(jcmbSourceLedgerto.getSelectedIndex()==0 ){
            slto="AP";
        }else if(jcmbSourceLedgerto.getSelectedIndex()==1){
            slto="AR";
        }
        parameter.put("srceledgrto", slto);

        String hsfr="";
        if(jcmbHavingStatusfr.getSelectedIndex()==0 ){
            hsfr="1";
        }else if(jcmbHavingStatusfr.getSelectedIndex()==1){
        }
        parameter.put("stsbatchfr", hsfr);

        String hsto="";
        if(jcmbHavingStatusto.getSelectedIndex()==0 ){
            hsto="1";
        }else if(jcmbHavingStatusto.getSelectedIndex()==1){
            hsto="2";
        }
        parameter.put("stsbatchto", hsto);

        String btfr="";
        if(jcmbBatchTypefr.getSelectedIndex()==0 ){
            btfr="1";
        }else if(jcmbBatchTypefr.getSelectedIndex()==1){
            btfr="2";
        }
        parameter.put("stbatchfr", btfr);

        String btto="";
        if(jcmbBatchTypeto.getSelectedIndex()==0 ){
            btto="1";
        }else if(jcmbBatchTypeto.getSelectedIndex()==1){
            btto="2";
        }
        parameter.put("stbatchto", btto);

        System.out.println(cutoffby);
        System.out.println(slfr);
        System.out.println(slto);
        System.out.println(hsfr);
        System.out.println(hsto);
        System.out.println(btfr);
        System.out.println(btto);

        if(jcmbCuttOf.getSelectedIndex()==0){
           file = GlobalUtils.getCurrentDir() +"/Reports/gl_batch_listing_batch.jrxml"; }
        else{
            if(jcmbCuttOf.getSelectedIndex()==1){
                   file = GlobalUtils.getCurrentDir() +"/Reports/gl_batch_listing_periode.jrxml"; }
            }

        GlobalUtils.printReport(file, parameter, false);
        }catch  (Exception e) {
        e.printStackTrace();
    }
    setCursor(GlobalUtils.NORMALCURSOR);
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jcmbSourceLedgertoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbSourceLedgertoItemStateChanged

}//GEN-LAST:event_jcmbSourceLedgertoItemStateChanged

private void jcmbSourceLedgerfrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbSourceLedgerfrItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbSourceLedgerfrItemStateChanged

private void jcmbHavingStatusfrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbHavingStatusfrItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbHavingStatusfrItemStateChanged

private void jcmbHavingStatustoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbHavingStatustoItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbHavingStatustoItemStateChanged

private void jcmbBatchTypefrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBatchTypefrItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbBatchTypefrItemStateChanged

private void jcmbBatchTypetoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBatchTypetoItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbBatchTypetoItemStateChanged

private void jbtnBatchFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBatchFrActionPerformed
    try {

            Gl_batchlists brs = new Gl_batchlists();
            FrmBrowse bd = new FrmBrowse(brs);
            bd.setFirstValue(jtxtNoBatchFr);
            bd.setModal(true);
            bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBatchFrActionPerformed

private void jbtnBatchToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBatchToActionPerformed
    try {

            Gl_batchlists brs = new Gl_batchlists();
            FrmBrowse bd = new FrmBrowse(brs);
            bd.setFirstValue(jtxtNoBatchTo);
            bd.setModal(true);
            bd.setVisible(true);


    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBatchToActionPerformed

private void jcmbSourceLedgerfrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbSourceLedgerfrActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbSourceLedgerfrActionPerformed

private void jcmbCuttOfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbCuttOfItemStateChanged
int year = Calendar.getInstance().get(Calendar.YEAR);
int bulan = Calendar.getInstance().get(Calendar.MONTH);

    if(jcmbCuttOf.getSelectedIndex()==0){
        jtxtNoBatchFr.setVisible(true);
        jtxtNoBatchTo.setVisible(true);
        jLabel7.setVisible(true);
        jLabel12.setVisible(true);
        jbtnBatchFr.setVisible(true);
        jbtnBatchTo.setVisible(true);
        jLabel1.setVisible(false);
        jcmbBulan.setVisible(false);
        jtxtyopfr.setVisible(false);
    }else{
        if(jcmbCuttOf.getSelectedIndex()==1){
            jtxtNoBatchFr.setVisible(false);
            jtxtNoBatchTo.setVisible(false);
            jLabel7.setVisible(false);
            jLabel12.setVisible(false);

            jbtnBatchFr.setVisible(false);
            jbtnBatchTo.setVisible(false);
            jLabel1.setVisible(true);
            jcmbBulan.setVisible(true);
            jcmbBulan.setSelectedIndex(bulan-1);
            jtxtyopfr.setVisible(true);
            jtxtyopfr.setText(year+"");
        }
    }
}//GEN-LAST:event_jcmbCuttOfItemStateChanged

private void jcmbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBulanItemStateChanged

}//GEN-LAST:event_jcmbBulanItemStateChanged

private void jcmbCuttOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCuttOfActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbCuttOfActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintTransaksiGLJournal dialog = new FrmPrintTransaksiGLJournal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtnBatchFr;
    private javax.swing.JButton jbtnBatchTo;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    private javax.swing.JComboBox jcmbBatchTypefr;
    private javax.swing.JComboBox jcmbBatchTypeto;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbCuttOf;
    private javax.swing.JComboBox jcmbHavingStatusfr;
    private javax.swing.JComboBox jcmbHavingStatusto;
    private javax.swing.JComboBox jcmbSourceLedgerfr;
    private javax.swing.JComboBox jcmbSourceLedgerto;
    public javax.swing.JTextField jtxtNoBatchFr;
    public javax.swing.JTextField jtxtNoBatchTo;
    public javax.swing.JTextField jtxtyopfr;
    // End of variables declaration//GEN-END:variables

}
