/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.objectclasses.ap.Ap_vendors;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_batchlists;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author  wgata
 */
public class FrmPrintTransaksiGLEkporDataNeraca extends javax.swing.JDialog {
    
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintTransaksiGLEkporDataNeraca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintTransaksiGLEkporDataNeraca() {
        initComponents();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblHeader = new javax.swing.JLabel();
        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcmbBulan = new javax.swing.JComboBox();
        jtxtyop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcmbHavingStatusfr = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jcmbHavingStatusto = new javax.swing.JComboBox();
        jtxtakun1fr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtakun1to = new javax.swing.JTextField();
        jtxtakun2to = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtakun2fr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtakun3fr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtakun3to = new javax.swing.JTextField();
        jtxtpstbeato = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtpstbeafr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtkodebrdfr = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtkodebrdto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtjdllap = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRINT GL - Rincian Neraca Bulanan");
        getContentPane().setLayout(null);

        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("GL - Laporan Lain-Lain");
        jlblHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlblHeader);
        jlblHeader.setBounds(30, 20, 440, 30);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 1, 10));
        jbtnCetak.setText("Print");
        jbtnCetak.setName("FrmPrintTransaksiGLJournal"); // NOI18N
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(130, 370, 70, 20);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 1, 10));
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(210, 370, 70, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel4.setText("Periode");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 50, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcmbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBulanItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(90, 80, 50, 20);

        jtxtyop.setFont(new java.awt.Font("SansSerif", 1, 10));
        jtxtyop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtyop);
        jtxtyop.setBounds(150, 80, 60, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setText("Status");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 50, 20);

        jcmbHavingStatusfr.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbHavingStatusfr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Posted", "Prov. Posted" }));
        jcmbHavingStatusfr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbHavingStatusfr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbHavingStatusfrItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbHavingStatusfr);
        jcmbHavingStatusfr.setBounds(90, 110, 120, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel10.setText("To");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 110, 20, 20);

        jcmbHavingStatusto.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbHavingStatusto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Posted", "Prov. Posted" }));
        jcmbHavingStatusto.setSelectedIndex(1);
        jcmbHavingStatusto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbHavingStatusto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbHavingStatustoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbHavingStatusto);
        jcmbHavingStatusto.setBounds(240, 110, 140, 20);

        jtxtakun1fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtakun1fr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun1fr);
        jtxtakun1fr.setBounds(140, 150, 90, 20);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel12.setText(" To");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 150, 20, 20);

        jtxtakun1to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtakun1to.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun1to);
        jtxtakun1to.setBounds(290, 150, 90, 20);

        jtxtakun2to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtakun2to.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun2to);
        jtxtakun2to.setBounds(290, 180, 90, 20);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel11.setText(" To");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(250, 180, 20, 20);

        jtxtakun2fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtakun2fr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun2fr);
        jtxtakun2fr.setBounds(140, 180, 90, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel5.setText("Akun2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 100, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel7.setText("Akun 3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 210, 100, 20);

        jtxtakun3fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtakun3fr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun3fr);
        jtxtakun3fr.setBounds(140, 210, 90, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel9.setText(" To");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 210, 20, 20);

        jtxtakun3to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtakun3to.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun3to);
        jtxtakun3to.setBounds(290, 210, 90, 20);

        jtxtpstbeato.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpstbeato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtpstbeato);
        jtxtpstbeato.setBounds(290, 240, 90, 20);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel13.setText(" To");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 240, 20, 20);

        jtxtpstbeafr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpstbeafr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtpstbeafr);
        jtxtpstbeafr.setBounds(140, 240, 90, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel8.setText("Akun Pusat Biaya");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 240, 100, 20);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel14.setText("Akun Kode Brand");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 270, 100, 20);

        jtxtkodebrdfr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkodebrdfr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtkodebrdfr);
        jtxtkodebrdfr.setBounds(140, 270, 90, 20);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel15.setText(" To");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(250, 270, 20, 20);

        jtxtkodebrdto.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkodebrdto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtkodebrdto);
        jtxtkodebrdto.setBounds(290, 270, 90, 20);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel17.setText("Judul Laporan");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 310, 100, 20);

        jtxtjdllap.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjdllap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtjdllap);
        jtxtjdllap.setBounds(140, 310, 350, 20);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel18.setText("Akun1");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 150, 100, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-517)/2, (screenSize.height-456)/2, 517, 456);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed

        
    try{
        String file   = "" ;
        Map parameter = new HashMap();

        String mope=(jcmbBulan.getSelectedIndex()+1+"" );
        String mopsbl="";
        parameter.put("mop", mope);
        parameter.put("yop", jtxtyop.getText());
        parameter.put("operator",GlobalUtils.userid);
        String yopsbl="";
        if (mope.equals("1")){
            mopsbl="12";
            parameter.put("mopsbl", mopsbl);
            Integer yope=Integer.parseInt(jtxtyop.getText())-1;
            yopsbl=yope.toString()  ;
            parameter.put("yopsbl", yopsbl);
        }else{
            mopsbl=(jcmbBulan.getSelectedIndex()+"" );
            parameter.put("mopsbl", mopsbl);
            yopsbl=jtxtyop.getText() ;
            parameter.put("yopsbl", yopsbl);
        }
       String hsfr="";
        if(jcmbHavingStatusfr.getSelectedIndex()==0 ){
            hsfr="2";
        }else {
            hsfr="5";
        }

        parameter.put("batchstsfr", hsfr);

        String hsto="";
        if(jcmbHavingStatusto.getSelectedIndex()==0 ){
               hsto="2";
        }else {
            hsto="5";
        }
        parameter.put("batchststo", hsto);

        System.out.println(mope);
        System.out.println(jtxtyop.getText());       
        System.out.println(mopsbl);
        System.out.println(yopsbl);
        System.out.println(hsfr);
        System.out.println(hsto);

        String nakun1fr = " " ;
        String nakun1to = "ZZZ" ;
        String nakun2fr = " " ;
        String nakun2to = "ZZZ" ;
        String nakun3fr = " " ;
        String nakun3to = "ZZ" ;
        String npstbeafr = " " ;
        String npstbeato = "ZZZ " ;
        String nkodebrdfr = " " ;
        String nkodebrdto = "ZZZ";

        if( jtxtakun1fr.getText().equals("")){
            parameter.put("akun1fr", nakun1fr);
        }else{
            parameter.put("akun1fr",  jtxtakun1fr.getText());
        }
        if( jtxtakun1to.getText().equals("")){
            parameter.put("akun1to", nakun1to);
        }else{
            parameter.put("akun1to",  jtxtakun1to.getText());
        }
        if( jtxtakun2fr.getText().equals("")){
            parameter.put("akun2fr", nakun2fr);
        }else{
            parameter.put("akun2fr",  jtxtakun2fr.getText());
        }
        if( jtxtakun2to.getText().equals("")){
            parameter.put("akun2to", nakun2to);
        }else{
            parameter.put("akun2to",  jtxtakun2to.getText());
        }
        if( jtxtpstbeafr.getText().equals("")){
            parameter.put("pstbeafr", npstbeafr);
        }else{
            parameter.put("pstbeafr",  jtxtpstbeafr.getText());
        }
        if( jtxtpstbeato.getText().equals("")){
            parameter.put("pstbeato", npstbeato);
        }else{
            parameter.put("pstbeato",  jtxtpstbeato.getText());
        }
        if( jtxtpstbeafr.getText().equals("")){
            parameter.put("kodebrdfr", nkodebrdfr);
        }else{
            parameter.put("kodebrdfr",  jtxtkodebrdfr.getText());
        }
        if( jtxtpstbeato.getText().equals("")){
            parameter.put("kodebrdto", nkodebrdto);
        }else{
            parameter.put("kodebrdto",  jtxtkodebrdto.getText());
        }
        parameter.put("jdllap", jtxtjdllap.getText());

        file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiGLEksporDataNeraca.jrxml";
        GlobalUtils.printReport(file, parameter, false);

    }catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jcmbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBulanItemStateChanged

}//GEN-LAST:event_jcmbBulanItemStateChanged

private void jcmbHavingStatusfrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbHavingStatusfrItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbHavingStatusfrItemStateChanged

private void jcmbHavingStatustoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbHavingStatustoItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbHavingStatustoItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintTransaksiGLEkporDataNeraca dialog = new FrmPrintTransaksiGLEkporDataNeraca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbHavingStatusfr;
    private javax.swing.JComboBox jcmbHavingStatusto;
    public javax.swing.JLabel jlblHeader;
    public javax.swing.JTextField jtxtakun1fr;
    public javax.swing.JTextField jtxtakun1to;
    public javax.swing.JTextField jtxtakun2fr;
    public javax.swing.JTextField jtxtakun2to;
    public javax.swing.JTextField jtxtakun3fr;
    public javax.swing.JTextField jtxtakun3to;
    public javax.swing.JTextField jtxtjdllap;
    public javax.swing.JTextField jtxtkodebrdfr;
    public javax.swing.JTextField jtxtkodebrdto;
    public javax.swing.JTextField jtxtpstbeafr;
    public javax.swing.JTextField jtxtpstbeato;
    public javax.swing.JTextField jtxtyop;
    // End of variables declaration//GEN-END:variables

}
