/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.objectclasses.ap.Ap_vendors;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_batchlists;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author  wgata
 */
public class FrmPrintTransaksiGLNeracaLabaRugiBulanan extends javax.swing.JDialog {
    
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintTransaksiGLNeracaLabaRugiBulanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintTransaksiGLNeracaLabaRugiBulanan() {
        initComponents();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblHeader = new javax.swing.JLabel();
        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcmbBulan = new javax.swing.JComboBox();
        jtxtyop = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcmbHavingStatusfr = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jcmbHavingStatusto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRINT GL - Neraca Laba Rugi Bulanan");
        getContentPane().setLayout(null);

        jlblHeader.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("GL - Neraca Laba Rugi Bulanan");
        jlblHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlblHeader);
        jlblHeader.setBounds(30, 20, 360, 30);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnCetak.setText("Print");
        jbtnCetak.setName("FrmPrintTransaksiGLJournal"); // NOI18N
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(130, 150, 70, 20);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(210, 150, 70, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setText("Periode");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 110, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcmbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBulanItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(150, 80, 50, 20);

        jtxtyop.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtyop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtyop);
        jtxtyop.setBounds(220, 80, 60, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setText("Having Of Status");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 90, 20);

        jcmbHavingStatusfr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbHavingStatusfr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Posted", "Prov. Posted" }));
        jcmbHavingStatusfr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbHavingStatusfr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbHavingStatusfrItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbHavingStatusfr);
        jcmbHavingStatusfr.setBounds(150, 110, 90, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel10.setText("To");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 110, 20, 20);

        jcmbHavingStatusto.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbHavingStatusto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Posted", "Prov. Posted" }));
        jcmbHavingStatusto.setSelectedIndex(1);
        jcmbHavingStatusto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcmbHavingStatusto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbHavingStatustoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbHavingStatusto);
        jcmbHavingStatusto.setBounds(280, 110, 90, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-422)/2, (screenSize.height-229)/2, 422, 229);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed

        
    try{
        String file   = "" ;
        Map parameter = new HashMap();

        String mope=(jcmbBulan.getSelectedIndex()+1+"" );
        String mopsbl="";
        parameter.put("mop", mope);
        parameter.put("yop", jtxtyop.getText());
        String yopsbl="";
        if (mope.equals("1")){
            mopsbl="12";
            parameter.put("mopsbl", mopsbl);
            Integer yope=Integer.parseInt(jtxtyop.getText())-1;
            yopsbl=yope.toString()  ;
            parameter.put("yopsbl", yopsbl);
        }else{
            mopsbl=(jcmbBulan.getSelectedIndex()+"" );
            parameter.put("mopsbl", mopsbl);
            yopsbl=jtxtyop.getText() ;
            parameter.put("yopsbl", yopsbl);
        }
       String hsfr="";
        if(jcmbHavingStatusfr.getSelectedIndex()==0 ){
            hsfr="2";
        }else {
            hsfr="5";
        }

        parameter.put("batchstsfr", hsfr);
        parameter.put("operator",GlobalUtils.userid);
        String hsto="";
        if(jcmbHavingStatusto.getSelectedIndex()==0 ){
               hsto="2";
        }else {
            hsto="5";
        }
        parameter.put("batchststo", hsto);

        System.out.println(mope);
        System.out.println(jtxtyop.getText());       
        System.out.println(mopsbl);
        System.out.println(yopsbl);
        System.out.println(hsfr);
        System.out.println(hsto);

        file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiGLRugiLaba.jrxml";
        GlobalUtils.printReport(file, parameter, false);

    }catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jcmbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBulanItemStateChanged

}//GEN-LAST:event_jcmbBulanItemStateChanged

private void jcmbHavingStatusfrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbHavingStatusfrItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbHavingStatusfrItemStateChanged

private void jcmbHavingStatustoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbHavingStatustoItemStateChanged
    // TODO add your handling code here:
}//GEN-LAST:event_jcmbHavingStatustoItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintTransaksiGLNeracaLabaRugiBulanan dialog = new FrmPrintTransaksiGLNeracaLabaRugiBulanan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbHavingStatusfr;
    private javax.swing.JComboBox jcmbHavingStatusto;
    public javax.swing.JLabel jlblHeader;
    public javax.swing.JTextField jtxtyop;
    // End of variables declaration//GEN-END:variables

}
