/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.objectclasses.ap.Ap_vendors;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_batchlists;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author  wgata
 */
public class FrmPrintTrialBalance extends javax.swing.JDialog {
    
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintTrialBalance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintTrialBalance() {
        initComponents();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblHeader = new javax.swing.JLabel();
        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtAccCodeFr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtAccCodeTo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcmbBulan = new javax.swing.JComboBox();
        jtxtyop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtakun2to = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtakun2fr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtakun1fr = new javax.swing.JTextField();
        jtxtakun1to = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtakun3fr = new javax.swing.JTextField();
        jtxtakun3to = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtpstbeafr = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtpstbeato = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtkodebrdfr = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtkodebrdto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRINT GL - Trial Balance");
        getContentPane().setLayout(null);

        jlblHeader.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("GL - Trial Balance Listing");
        jlblHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlblHeader);
        jlblHeader.setBounds(90, 20, 470, 30);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnCetak.setText("Print");
        jbtnCetak.setName("FrmPrintTransaksiGLJournal"); // NOI18N
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(250, 310, 70, 20);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(360, 310, 70, 20);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("Account Code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 90, 14);

        jtxtAccCodeFr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(jtxtAccCodeFr);
        jtxtAccCodeFr.setBounds(150, 110, 180, 20);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 110, 20, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setText(" To");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 200, 20, 20);

        jtxtAccCodeTo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(jtxtAccCodeTo);
        jtxtAccCodeTo.setBounds(400, 110, 180, 20);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 110, 20, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setText("Periode");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 80, 100, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcmbBulan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbBulanItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(150, 80, 50, 20);

        jtxtyop.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtyop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtyop);
        jtxtyop.setBounds(220, 80, 60, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setText("Akun2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 100, 20);

        jtxtakun2to.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtakun2to.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun2to);
        jtxtakun2to.setBounds(400, 170, 90, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel10.setText(" To");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 110, 20, 20);

        jtxtakun2fr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtakun2fr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun2fr);
        jtxtakun2fr.setBounds(150, 170, 70, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setText("( Maks. 3 digit )");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 260, 100, 20);

        jtxtakun1fr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtakun1fr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun1fr);
        jtxtakun1fr.setBounds(150, 140, 70, 20);

        jtxtakun1to.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtakun1to.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun1to);
        jtxtakun1to.setBounds(400, 140, 90, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel7.setText("Akun 3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 200, 100, 20);

        jtxtakun3fr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtakun3fr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun3fr);
        jtxtakun3fr.setBounds(150, 200, 70, 20);

        jtxtakun3to.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtakun3to.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtakun3to);
        jtxtakun3to.setBounds(400, 200, 90, 20);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setText(" To");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 170, 20, 20);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel12.setText(" To");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 140, 20, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel8.setText("Akun Pusat Biaya");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 230, 100, 20);

        jtxtpstbeafr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtpstbeafr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtpstbeafr);
        jtxtpstbeafr.setBounds(150, 230, 70, 20);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel13.setText(" To");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(360, 230, 20, 20);

        jtxtpstbeato.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtpstbeato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtpstbeato);
        jtxtpstbeato.setBounds(400, 230, 90, 20);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel14.setText("Akun Kode Brand");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 260, 100, 20);

        jtxtkodebrdfr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtkodebrdfr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtkodebrdfr);
        jtxtkodebrdfr.setBounds(150, 260, 70, 20);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel15.setText(" To");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(360, 260, 20, 20);

        jtxtkodebrdto.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtkodebrdto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jtxtkodebrdto);
        jtxtkodebrdto.setBounds(400, 260, 90, 20);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel16.setText("Akun1");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 140, 100, 20);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel17.setText("( Maks. 2 digit )");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 140, 100, 20);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel18.setText("( Maks. 2 digit )");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(230, 200, 100, 20);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel19.setText("( Maks. 2 digit )");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(500, 140, 100, 20);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel20.setText("( Maks. 2 digit )");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(500, 200, 100, 20);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel21.setText("( Maks. 3 digit )");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(230, 170, 100, 20);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel22.setText("( Maks. 3 digit )");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(500, 170, 100, 20);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel23.setText("( Maks. 3 digit )");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(230, 230, 100, 20);

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel24.setText("( Maks. 3 digit )");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(230, 260, 100, 20);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel25.setText("( Maks. 3 digit )");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(500, 230, 100, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-648)/2, (screenSize.height-388)/2, 648, 388);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed

        
    try{
        String file   = "" ;
        Map parameter = new HashMap();

        String mope=(jcmbBulan.getSelectedIndex()+1+"" );
        parameter.put("mop", mope);
        parameter.put("yop", jtxtyop.getText());
        System.out.println(mope);
        System.out.println(jtxtyop.getText());       

        String afr=(jtxtAccCodeFr.getText());
        String ato=(jtxtAccCodeTo.getText());
        String a1fr="" ;
        String a2fr="" ;
        String a3fr="" ;
        String a4fr="" ;
        String a5fr="" ;
        String a1to="";
        String a2to="" ;
        String a3to="";
        String a4to="" ;
        String a5to="" ;
        String a6fr="" ;
        String a6to="" ;
        String nakun1fr = " " ;
        String nakun1to = "ZZ " ;
        String nakun2fr = " " ;
        String nakun2to = "ZZZ " ;
        String nakun3fr = " " ;
        String nakun3to = "ZZ " ;
        String npstbeafr = " " ;
        String npstbeato = "ZZZ " ;
        String nkodebrdfr = " " ;
        String nkodebrdto = "ZZZ " ;

        if(afr.equals("") && ato.equals("")){
                    System.out.println("Kode Akun Kosong");
                    if (jtxtakun1fr.getText().equals("")){
                         nakun1fr = "  " ;
                    }else{
                        nakun1fr = jtxtakun1fr.getText() ;
                    }

                    if (jtxtakun1to.getText().equals("")){
                         nakun1to = "ZZ " ;
                    }else{
                        nakun1to = jtxtakun1to.getText() ;
                    }

                    if (jtxtakun2fr.getText().equals("")){
                         nakun2fr = "  " ;
                    }else{
                        nakun2fr = jtxtakun2fr.getText() ;
                    }

                    if (jtxtakun2to.getText().equals("")){
                         nakun2to = "ZZZ " ;
                    }else{
                        nakun2to = jtxtakun2to.getText() ;
                    }

                    if (jtxtakun3fr.getText().equals("")){
                         nakun3fr = "  " ;
                    }else{
                        nakun3fr = jtxtakun3fr.getText() ;
                    }

                    if (jtxtakun3to.getText().equals("")){
                         nakun3to = "ZZ" ;
                    }else{
                        nakun3to = jtxtakun3to.getText() ;
                    }

                    if (jtxtpstbeafr.getText().equals("")){
                         npstbeafr = "  " ;
                    }else{
                        npstbeafr = jtxtpstbeafr.getText() ;
                    }
                    if (jtxtpstbeato.getText().equals("")){
                         npstbeato = "ZZZ " ;
                    }else{
                        npstbeato = jtxtpstbeato.getText() ;
                    }
                    
                    if (jtxtkodebrdfr.getText().equals("")){
                         nkodebrdfr = "  " ;
                    }else{
                        nkodebrdfr = jtxtkodebrdfr.getText() ;
                    }
                    if (jtxtkodebrdto.getText().equals("")){
                         nkodebrdto = "ZZZ " ;
                    }else{
                        nkodebrdto = jtxtkodebrdto.getText() ;
                    }
                    parameter.put("akun1fr", nakun1fr);
                    parameter.put("akun1to", nakun1to);
                    parameter.put("akun2fr", nakun2fr);
                    parameter.put("akun2to", nakun2to);
                    parameter.put("akun3fr", nakun3fr);
                    parameter.put("akun3to", nakun3to);
                    parameter.put("pstbeafr", npstbeafr);
                    parameter.put("pstbeato", npstbeato);
                    parameter.put("kodebrdfr", nkodebrdfr);
                    parameter.put("kodebrdto", nkodebrdto);
        }
        else {
                    a1fr=afr.substring(0, 2) ;
                    a2fr=afr.substring(3, 6) ;
                    a3fr=afr.substring(7, 9) ;
                    a4fr=afr.substring(10, 13) ;
                    a5fr=afr.substring(14, 17) ;
                    a1to=ato.substring(0, 2) ;
                    a2to=ato.substring(3, 6) ;
                    a3to=ato.substring(7, 9) ;
                    a4to=ato.substring(10, 13) ;
                    a5to=ato.substring(14, 17) ;
                    a6fr=a1fr+a2fr+a3fr+a4fr+a5fr;
                    a6to=a1to+a2to+a3to+a4to+a5to;
                    System.out.println(afr);
                    System.out.println(a1fr);
                    System.out.println(a2fr);
                    System.out.println(a3fr);
                    System.out.println(a4fr);
                    System.out.println(a5fr);
                    System.out.println(ato);
                    System.out.println(a1to);
                    System.out.println(a2to);
                    System.out.println(a3to);
                    System.out.println(a4to);
                    System.out.println(a5to);
                    parameter.put("acccodefr", a6fr);
                    parameter.put("acccodeto", a6to);
                    parameter.put("akun1fr", a1fr);
                    parameter.put("akun1to", a1to);
                    parameter.put("akun2fr", a2fr);
                    parameter.put("akun2to", a2to);
                    parameter.put("akun3fr", a3fr);
                    parameter.put("akun3to", a3to);
                    parameter.put("pstbeafr", a4fr);
                    parameter.put("pstbeato", a4to);
                    parameter.put("kodebrdfr", a5fr);
                    parameter.put("kodebrdto", a5to);
        }

        file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiGLTrialBalance.jrxml";
        GlobalUtils.printReport(file, parameter, false);

    }catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        Gl_accounts brs = new Gl_accounts();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtAccCodeFr);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        Gl_accounts brs = new Gl_accounts();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtAccCodeTo);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jcmbBulanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbBulanItemStateChanged

}//GEN-LAST:event_jcmbBulanItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintTrialBalance dialog = new FrmPrintTrialBalance(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    private javax.swing.JComboBox jcmbBulan;
    public javax.swing.JLabel jlblHeader;
    public javax.swing.JTextField jtxtAccCodeFr;
    public javax.swing.JTextField jtxtAccCodeTo;
    public javax.swing.JTextField jtxtakun1fr;
    public javax.swing.JTextField jtxtakun1to;
    public javax.swing.JTextField jtxtakun2fr;
    public javax.swing.JTextField jtxtakun2to;
    public javax.swing.JTextField jtxtakun3fr;
    public javax.swing.JTextField jtxtakun3to;
    public javax.swing.JTextField jtxtkodebrdfr;
    public javax.swing.JTextField jtxtkodebrdto;
    public javax.swing.JTextField jtxtpstbeafr;
    public javax.swing.JTextField jtxtpstbeato;
    public javax.swing.JTextField jtxtyop;
    // End of variables declaration//GEN-END:variables

}
