/*
 * FrmPrintMasterBahanBaku.java
 *
 * Created on September 8, 2009, 4:18 PM
 */

package common.print;

import accapp.objectclasses.cashbook.Cb_batchcontrols;
import common.component.FrmBrowse;
import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;


/**
 *
 * @author  wgata
 */
public class FrmPrintTransaksiCBBatchList extends javax.swing.JDialog {
    
    DateFormat dateformat=new SimpleDateFormat("MM/dd/yyyy");
    DateFormat dateformatprint =new SimpleDateFormat("yyyy-MM-dd");


    /** Creates new form FrmPrintMasterBahanBaku */
    public FrmPrintTransaksiCBBatchList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public FrmPrintTransaksiCBBatchList() {
        initComponents();

    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtNoBatchFr = new javax.swing.JTextField();
        jlblHeader = new javax.swing.JLabel();
        jbtnCetak = new javax.swing.JButton();
        jbtnSelesai = new javax.swing.JButton();
        jbtnBatchFr = new javax.swing.JButton();
        jtxtNoBatchTo = new javax.swing.JTextField();
        jbtnBatchTo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jchkcb = new javax.swing.JCheckBox();
        jchkar = new javax.swing.JCheckBox();
        jchkap = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jchkopen = new javax.swing.JCheckBox();
        jchkposted = new javax.swing.JCheckBox();
        jchkclosed = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jchkin = new javax.swing.JCheckBox();
        jchkit = new javax.swing.JCheckBox();
        jchkcn = new javax.swing.JCheckBox();
        jchkdn = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jchkbtne = new javax.swing.JCheckBox();
        jchkbttr = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jchkbtofentered = new javax.swing.JCheckBox();
        jchkbtofgenerated = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRINT CB - BATCH LIST");
        getContentPane().setLayout(null);

        jtxtNoBatchFr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtNoBatchFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNoBatchFrActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNoBatchFr);
        jtxtNoBatchFr.setBounds(140, 70, 100, 20);

        jlblHeader.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("CB - Batch Listing Report");
        getContentPane().add(jlblHeader);
        jlblHeader.setBounds(80, 20, 260, 30);

        jbtnCetak.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnCetak.setText("Print");
        jbtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCetak);
        jbtnCetak.setBounds(80, 390, 90, 23);

        jbtnSelesai.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnSelesai.setText("End");
        jbtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSelesai);
        jbtnSelesai.setBounds(240, 390, 90, 23);

        jbtnBatchFr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBatchFr.setText("...");
        jbtnBatchFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBatchFrActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBatchFr);
        jbtnBatchFr.setBounds(240, 70, 20, 20);

        jtxtNoBatchTo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(jtxtNoBatchTo);
        jtxtNoBatchTo.setBounds(300, 70, 100, 19);

        jbtnBatchTo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBatchTo.setText("...");
        jbtnBatchTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBatchToActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBatchTo);
        jbtnBatchTo.setBounds(400, 70, 20, 20);

        jLabel5.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel5.setText("Batch");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 70, 100, 20);

        jLabel9.setFont(new java.awt.Font("Adobe Sans MM", 1, 10));
        jLabel9.setText("To");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 70, 20, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entry Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel1.setLayout(null);

        jchkcb.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkcb.setSelected(true);
        jchkcb.setText("CB");
        jchkcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcbActionPerformed(evt);
            }
        });
        jPanel1.add(jchkcb);
        jchkcb.setBounds(10, 20, 110, 23);

        jchkar.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkar.setSelected(true);
        jchkar.setText("AR");
        jchkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkarActionPerformed(evt);
            }
        });
        jPanel1.add(jchkar);
        jchkar.setBounds(10, 60, 80, 23);

        jchkap.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkap.setSelected(true);
        jchkap.setText("AP");
        jchkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkapActionPerformed(evt);
            }
        });
        jPanel1.add(jchkap);
        jchkap.setBounds(10, 40, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 270, 190, 90);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batch Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel2.setLayout(null);

        jchkopen.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jchkopen.setSelected(true);
        jchkopen.setText("Open");
        jchkopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkopenActionPerformed(evt);
            }
        });
        jPanel2.add(jchkopen);
        jchkopen.setBounds(10, 20, 58, 13);

        jchkposted.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkposted.setSelected(true);
        jchkposted.setText("Posted");
        jchkposted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkpostedActionPerformed(evt);
            }
        });
        jPanel2.add(jchkposted);
        jchkposted.setBounds(10, 35, 150, 13);

        jchkclosed.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkclosed.setSelected(true);
        jchkclosed.setText("Closed");
        jPanel2.add(jchkclosed);
        jchkclosed.setBounds(10, 50, 150, 13);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 170, 200, 90);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Document Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel3.setLayout(null);

        jchkin.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkin.setSelected(true);
        jchkin.setText("Invoice");
        jchkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkinActionPerformed(evt);
            }
        });
        jPanel3.add(jchkin);
        jchkin.setBounds(10, 20, 150, 13);

        jchkit.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkit.setSelected(true);
        jchkit.setText("Interest");
        jchkit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkitActionPerformed(evt);
            }
        });
        jPanel3.add(jchkit);
        jchkit.setBounds(10, 65, 150, 13);

        jchkcn.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkcn.setSelected(true);
        jchkcn.setText("Credit Note");
        jchkcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcnActionPerformed(evt);
            }
        });
        jPanel3.add(jchkcn);
        jchkcn.setBounds(10, 35, 150, 13);

        jchkdn.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkdn.setSelected(true);
        jchkdn.setText("Debit Note");
        jchkdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkdnActionPerformed(evt);
            }
        });
        jPanel3.add(jchkdn);
        jchkdn.setBounds(10, 50, 150, 13);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(230, 270, 200, 90);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batch Type ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel4.setLayout(null);

        jchkbtne.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkbtne.setSelected(true);
        jchkbtne.setText("Normal Entry");
        jchkbtne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkbtneActionPerformed(evt);
            }
        });
        jPanel4.add(jchkbtne);
        jchkbtne.setBounds(10, 20, 110, 23);

        jchkbttr.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkbttr.setSelected(true);
        jchkbttr.setText("Tranfered");
        jchkbttr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkbttrActionPerformed(evt);
            }
        });
        jPanel4.add(jchkbttr);
        jchkbttr.setBounds(210, 20, 90, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 100, 400, 60);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batch Type Of Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel5.setLayout(null);

        jchkbtofentered.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkbtofentered.setSelected(true);
        jchkbtofentered.setText("Entered");
        jchkbtofentered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkbtofenteredActionPerformed(evt);
            }
        });
        jPanel5.add(jchkbtofentered);
        jchkbtofentered.setBounds(10, 20, 110, 23);

        jchkbtofgenerated.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkbtofgenerated.setSelected(true);
        jchkbtofgenerated.setText("Generated");
        jchkbtofgenerated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkbtofgeneratedActionPerformed(evt);
            }
        });
        jPanel5.add(jchkbtofgenerated);
        jchkbtofgenerated.setBounds(10, 40, 80, 23);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 170, 190, 90);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-462)/2, (screenSize.height-459)/2, 462, 459);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSelesaiActionPerformed

    this.dispose();
}//GEN-LAST:event_jbtnSelesaiActionPerformed

private void jbtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCetakActionPerformed

        
    try{
        setCursor(GlobalUtils.HOURGLASSCURSOR);
        Map parameter = new HashMap();    
        parameter.put("nobatchfr", jtxtNoBatchFr.getText());
        parameter.put("nobatchto", jtxtNoBatchTo.getText());

        parameter.put("btnormal", jchkbtne.isSelected() ? "N" : "1");
        parameter.put("bttranfer", jchkbttr.isSelected() ? "T" :"2");
        parameter.put("betentered", jchkbtofentered.isSelected() ? "E" : "1");
        parameter.put("betgenerated", jchkbtofgenerated.isSelected() ? "G" :"2");
        parameter.put("operator",GlobalUtils.userid);
        String buka="";
        String kirim="";
        String tutup="";
        
        if(jchkopen.isSelected()){
             buka="O";
        }else{
             buka="1";
        }
        if(jchkposted.isSelected()){
             kirim="P";
        }else{
             kirim="2";
        }
        if(jchkclosed.isSelected()){
            tutup="C";
        }else{
            tutup="3";
        }

        parameter.put("status1", buka);
        parameter.put("status2", kirim);
        parameter.put("status3", tutup);
        parameter.put("entrytypecb", jchkcb.isSelected() ? "C" :"1");
        parameter.put("entrytypeap", jchkap.isSelected() ? "P" :"2");
        parameter.put("entrytypear", jchkar.isSelected() ? "R" :"3");
        parameter.put("doctypein", jchkin.isSelected() ? "4" :"I");
        parameter.put("doctypecn", jchkcn.isSelected() ? "5" :"C");
        parameter.put("doctypedn", jchkdn.isSelected() ? "6" :"D");
        parameter.put("doctypeit", jchkit.isSelected() ? "7" :"T");

        System.out.println(jtxtNoBatchFr.getText());
        System.out.println(jtxtNoBatchTo.getText());
        System.out.println(jchkbtne.isSelected() ? "N" : "1");
        System.out.println(jchkbttr.isSelected() ? "T" :"2");
        System.out.println(jchkbtofentered.isSelected() ? "E" : "1");
        System.out.println(jchkbtofgenerated.isSelected() ? "G" :"2");
        System.out.println(buka);
        System.out.println(kirim);
        System.out.println(tutup);
        System.out.println(jchkcb.isSelected() ? "C" : "1");
        System.out.println(jchkap.isSelected() ? "P" : "2");
        System.out.println(jchkar.isSelected() ? "R" : "3");
        System.out.println(jchkin.isSelected() ? "4" :"I");
        System.out.println(jchkcn.isSelected() ? "5" :"C");
        System.out.println(jchkdn.isSelected() ? "6" :"D");
        System.out.println(jchkit.isSelected() ? "7" :"T");

        String file   = "" ;
        file = GlobalUtils.getCurrentDir() +"/Reports/TransaksiCBBatchList.jrxml";
        GlobalUtils.printReport(file, parameter, false);
    }catch (Exception e) {
        e.printStackTrace();
    }
    setCursor(GlobalUtils.NORMALCURSOR);
}//GEN-LAST:event_jbtnCetakActionPerformed

private void jmbModelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jmbModelPropertyChange

}//GEN-LAST:event_jmbModelPropertyChange

private void jbtnBatchFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBatchFrActionPerformed
    try {
       
            Cb_batchcontrols brs = new Cb_batchcontrols();
	    FrmBrowse bd = new FrmBrowse(brs);
            bd.setFirstValue(jtxtNoBatchFr);
            bd.setModal(true);
            bd.setVisible(true);
    
	   } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBatchFrActionPerformed

private void jbtnBatchToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBatchToActionPerformed
try {
	  
            Cb_batchcontrols brs = new Cb_batchcontrols();
	    FrmBrowse bd = new FrmBrowse(brs);
            bd.setFirstValue(jtxtNoBatchTo);
            bd.setModal(true);
            bd.setVisible(true);


	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBatchToActionPerformed

private void jchkopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkopenActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkopenActionPerformed

private void jchkpostedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkpostedActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkpostedActionPerformed

private void jchkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkarActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkarActionPerformed

private void jchkcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcbActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkcbActionPerformed

private void jchkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkinActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkinActionPerformed

private void jchkitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkitActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkitActionPerformed

private void jchkbtneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkbtneActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkbtneActionPerformed

private void jchkbttrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkbttrActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkbttrActionPerformed

private void jchkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkapActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkapActionPerformed

private void jchkbtofenteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkbtofenteredActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkbtofenteredActionPerformed

private void jchkbtofgeneratedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkbtofgeneratedActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkbtofgeneratedActionPerformed

private void jchkcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcnActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkcnActionPerformed

private void jtxtNoBatchFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNoBatchFrActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtNoBatchFrActionPerformed

private void jchkdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkdnActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkdnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrintTransaksiCBBatchList dialog = new FrmPrintTransaksiCBBatchList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbtnBatchFr;
    private javax.swing.JButton jbtnBatchTo;
    private javax.swing.JButton jbtnCetak;
    private javax.swing.JButton jbtnSelesai;
    private javax.swing.JCheckBox jchkap;
    private javax.swing.JCheckBox jchkar;
    private javax.swing.JCheckBox jchkbtne;
    private javax.swing.JCheckBox jchkbtofentered;
    private javax.swing.JCheckBox jchkbtofgenerated;
    private javax.swing.JCheckBox jchkbttr;
    private javax.swing.JCheckBox jchkcb;
    private javax.swing.JCheckBox jchkclosed;
    private javax.swing.JCheckBox jchkcn;
    private javax.swing.JCheckBox jchkdn;
    private javax.swing.JCheckBox jchkin;
    private javax.swing.JCheckBox jchkit;
    private javax.swing.JCheckBox jchkopen;
    private javax.swing.JCheckBox jchkposted;
    public javax.swing.JLabel jlblHeader;
    public javax.swing.JTextField jtxtNoBatchFr;
    public javax.swing.JTextField jtxtNoBatchTo;
    // End of variables declaration//GEN-END:variables

}
