/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accapp.component.costapp;

/**
 *
 * @author skurniawan
 */
public class FrmCostAcc_Setting_Company_Brand extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCostAcc_Setting_Company_Brand
     */
    public FrmCostAcc_Setting_Company_Brand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jtxtBrowseCompany = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtBrowseCompany1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtBrowseCompany2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jtxtBrowseCompany3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 420));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MASTER COMPANY & BRAND");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 11, 215, 40);

        jLabel2.setText("Company");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(37, 63, 91, 21);

        jLabel3.setText("Company Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(37, 91, 91, 23);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(132, 91, 214, 23);
        getContentPane().add(jtxtBrowseCompany);
        jtxtBrowseCompany.setBounds(132, 62, 168, 23);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(306, 62, 40, 23);

        jLabel4.setText("Group Code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(431, 63, 91, 21);
        getContentPane().add(jtxtBrowseCompany1);
        jtxtBrowseCompany1.setBounds(526, 63, 168, 20);

        jButton2.setText("jButton1");
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 62, 40, 23);

        jTextField2.setText("jTextField1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(526, 91, 214, 23);

        jLabel5.setText("Group Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(431, 91, 91, 23);

        jCheckBox1.setText("Is Product");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(37, 198, 75, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(37, 223, 703, 170);

        jLabel6.setText("Customer Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(37, 161, 91, 23);

        jLabel7.setText("Customer Code");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(37, 133, 91, 21);
        getContentPane().add(jtxtBrowseCompany2);
        jtxtBrowseCompany2.setBounds(132, 132, 168, 23);

        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(132, 161, 214, 23);

        jButton3.setText("jButton1");
        getContentPane().add(jButton3);
        jButton3.setBounds(306, 132, 40, 23);

        jTextField4.setText("jTextField1");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(526, 173, 214, 23);

        jButton4.setText("jButton1");
        getContentPane().add(jButton4);
        jButton4.setBounds(700, 132, 40, 23);
        getContentPane().add(jtxtBrowseCompany3);
        jtxtBrowseCompany3.setBounds(526, 132, 168, 35);

        jLabel8.setText("PPN Account");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(431, 133, 91, 21);

        jLabel9.setText("Account Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(431, 173, 91, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jtxtBrowseCompany;
    private javax.swing.JTextField jtxtBrowseCompany1;
    private javax.swing.JTextField jtxtBrowseCompany2;
    private javax.swing.JTextField jtxtBrowseCompany3;
    // End of variables declaration//GEN-END:variables
}
