/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import test.FrmAr_distcode;
 * 
 * .......
 * 
 * 
 * FrmAr_distcode frmAr_distcode;
 * 
 * .......
 * 
 try {
        if (frmAr_distcode == null) {
            frmmAr_distcode = new FrmAr_distcode(this);
        }
        
        showForm(frmAr_distcode);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.ar;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.ar.Ar_distcode;
import accapp.objectclasses.ar.Ar_distcodes;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_accounts;
import common.print.FrmPrintMasterARDistributionCode;
import java.awt.event.KeyEvent;

/**
 *
 * @author  Generator
 */

public class FrmAr_distcode extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmAr_distcode";
    
    FrmMainFrame mf ;
    
    
    public Ar_distcode obj = new Ar_distcode();
    
   
    /** Creates new form Area */
    public FrmAr_distcode() throws CodeException {
        initComponents();
    }
    
    public FrmAr_distcode(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        jtxtid.setBounds(180, 30, 80, 20);
        jtxtentrydate.setBounds(260, 30, 160, 20);
        jtxtauditdate.setBounds(420, 30, 160, 20);
        jtxtaudituser.setBounds(580, 30, 110, 20);
        jtxtcmpnyid.setBounds(690, 30, 120, 20);

        jtxtid.setEditable(false);
        jtxtentrydate.setEditable(false);
        jtxtauditdate.setEditable(false);
        jtxtaudituser.setEditable(false);
        jtxtcmpnyid.setEditable(false);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jtxtid = new javax.swing.JTextField();
        jlbldistcode = new javax.swing.JLabel();
        jtxtdistcode = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlblactive = new javax.swing.JLabel();
        jlblaccrevcode = new javax.swing.JLabel();
        jtxtaccrevcode = new javax.swing.JTextField();
        jlblaccinvcode = new javax.swing.JLabel();
        jtxtaccinvcode = new javax.swing.JTextField();
        jlblacccogscode = new javax.swing.JLabel();
        jtxtacccogscode = new javax.swing.JTextField();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jbtnBrowseCost = new javax.swing.JButton();
        jbtnBrowseRevenue = new javax.swing.JButton();
        jbtnBrowseInventory = new javax.swing.JButton();
        jtxtaccrevdesc = new javax.swing.JTextField();
        jtxtaccinvdesc = new javax.swing.JTextField();
        jtxtacccogsdesc = new javax.swing.JTextField();
        jchkActive = new javax.swing.JCheckBox();
        jtxtentrydate1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A/R Distribution Code");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Distribution Code");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(400, 100, 30, 17);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(250, 30, 80, 16);

        jlbldistcode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldistcode.setText("Distribution Code");
        getContentPane().add(jlbldistcode);
        jlbldistcode.setBounds(70, 100, 140, 14);

        jtxtdistcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdistcode.setText("distcode");
        jtxtdistcode.setToolTipText("Distribution Code");
        jtxtdistcode.setNextFocusableComponent(jtxtdscription);
        jtxtdistcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdistcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtdistcode);
        jtxtdistcode.setBounds(260, 100, 140, 20);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldscription.setText("Description");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 120, 140, 14);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdscription.setText("dscription");
        jtxtdscription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdscriptionKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 120, 390, 20);

        jlblactive.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblactive.setText("Last Maintain");
        getContentPane().add(jlblactive);
        jlblactive.setBounds(70, 145, 140, 14);

        jlblaccrevcode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblaccrevcode.setText("Revenue");
        getContentPane().add(jlblaccrevcode);
        jlblaccrevcode.setBounds(70, 170, 140, 14);

        jtxtaccrevcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtaccrevcode.setText("accrevcode");
        jtxtaccrevcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaccrevcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtaccrevcode);
        jtxtaccrevcode.setBounds(260, 170, 140, 20);

        jlblaccinvcode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblaccinvcode.setText("Inventory");
        getContentPane().add(jlblaccinvcode);
        jlblaccinvcode.setBounds(70, 190, 140, 14);

        jtxtaccinvcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtaccinvcode.setText("accinvcode");
        jtxtaccinvcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaccinvcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtaccinvcode);
        jtxtaccinvcode.setBounds(260, 190, 140, 20);

        jlblacccogscode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblacccogscode.setText("Cost Of Goods Sold");
        getContentPane().add(jlblacccogscode);
        jlblacccogscode.setBounds(70, 210, 140, 14);

        jtxtacccogscode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtacccogscode.setText("acccogscode");
        jtxtacccogscode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtacccogscodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtacccogscode);
        jtxtacccogscode.setBounds(260, 210, 140, 20);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(330, 30, 80, 16);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(410, 30, 80, 16);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(490, 30, 80, 16);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(570, 30, 80, 16);

        jbtnBrowseCost.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseCost.setText("...");
        jbtnBrowseCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseCostActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseCost);
        jbtnBrowseCost.setBounds(400, 210, 30, 17);

        jbtnBrowseRevenue.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseRevenue.setText("...");
        jbtnBrowseRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseRevenueActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseRevenue);
        jbtnBrowseRevenue.setBounds(400, 170, 30, 17);

        jbtnBrowseInventory.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseInventory.setText("...");
        jbtnBrowseInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseInventory);
        jbtnBrowseInventory.setBounds(400, 190, 30, 17);

        jtxtaccrevdesc.setEditable(false);
        jtxtaccrevdesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtaccrevdesc.setText("jtxtaccrevdesc");
        getContentPane().add(jtxtaccrevdesc);
        jtxtaccrevdesc.setBounds(430, 170, 270, 20);

        jtxtaccinvdesc.setEditable(false);
        jtxtaccinvdesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtaccinvdesc.setText("jtxtaccinvdesc");
        getContentPane().add(jtxtaccinvdesc);
        jtxtaccinvdesc.setBounds(430, 190, 270, 20);

        jtxtacccogsdesc.setEditable(false);
        jtxtacccogsdesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtacccogsdesc.setText("jtxtacccogsdesc");
        getContentPane().add(jtxtacccogsdesc);
        jtxtacccogsdesc.setBounds(430, 210, 270, 20);

        jchkActive.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jchkActive.setText("In Active");
        jchkActive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchkActiveKeyPressed(evt);
            }
        });
        getContentPane().add(jchkActive);
        jchkActive.setBounds(450, 142, 98, 23);

        jtxtentrydate1.setEditable(false);
        jtxtentrydate1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtentrydate1.setText("entrydate");
        getContentPane().add(jtxtentrydate1);
        jtxtentrydate1.setBounds(260, 145, 170, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseCostActionPerformed
    // TODO add your handling code here:
    try {
        Gl_accounts brs = new Gl_accounts();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtacccogscode);
        bd.setSecondValue(jtxtacccogsdesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseCostActionPerformed

private void jbtnBrowseRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseRevenueActionPerformed
    // TODO add your handling code here:
    try {
        Gl_accounts brs = new Gl_accounts();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtaccrevcode);
        bd.setSecondValue(jtxtaccrevdesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseRevenueActionPerformed

private void jbtnBrowseInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseInventoryActionPerformed
    // TODO add your handling code here:
    try {
        Gl_accounts brs = new Gl_accounts();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtaccinvcode);
        bd.setSecondValue(jtxtaccinvdesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseInventoryActionPerformed

private void jtxtdistcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdistcodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtdscription.requestFocus();
    }

}//GEN-LAST:event_jtxtdistcodeKeyPressed

private void jtxtdscriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdscriptionKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jchkActive.requestFocus();
    }
    
}//GEN-LAST:event_jtxtdscriptionKeyPressed

private void jchkActiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkActiveKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtaccrevcode.requestFocus();
    }
}//GEN-LAST:event_jchkActiveKeyPressed

private void jtxtaccrevcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccrevcodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setaccrevcode(jtxtaccrevcode.getText().replace("-", ""));
            jtxtaccrevdesc.setText(obj.getAccRevDesc());
        }catch(Exception e) {}
        jtxtaccinvcode.requestFocus();
    }
}//GEN-LAST:event_jtxtaccrevcodeKeyPressed

private void jtxtaccinvcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccinvcodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        try{
            obj.setaccinvcode(jtxtaccinvcode.getText().replace("-", ""));
            jtxtaccinvdesc.setText(obj.getAccInvDesc());
        }catch(Exception e){}
        jtxtacccogscode.requestFocus();
    }
}//GEN-LAST:event_jtxtaccinvcodeKeyPressed

private void jtxtacccogscodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtacccogscodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setacccogscode(jtxtacccogscode.getText().replace("-", ""));
            jtxtacccogsdesc.setText(obj.getAccCostDesc());
        }catch(Exception e){}

    }
}//GEN-LAST:event_jtxtacccogscodeKeyPressed


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Ar_distcodes brs = new Ar_distcodes();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtdistcode);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmAr_distcode().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowseCost;
    private javax.swing.JButton jbtnBrowseInventory;
    private javax.swing.JButton jbtnBrowseRevenue;
    private javax.swing.JCheckBox jchkActive;
    private javax.swing.JLabel jlblacccogscode;
    private javax.swing.JLabel jlblaccinvcode;
    private javax.swing.JLabel jlblaccrevcode;
    private javax.swing.JLabel jlblactive;
    private javax.swing.JLabel jlbldistcode;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JTextField jtxtacccogscode;
    private javax.swing.JTextField jtxtacccogsdesc;
    private javax.swing.JTextField jtxtaccinvcode;
    private javax.swing.JTextField jtxtaccinvdesc;
    private javax.swing.JTextField jtxtaccrevcode;
    private javax.swing.JTextField jtxtaccrevdesc;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtdistcode;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtentrydate1;
    private javax.swing.JTextField jtxtid;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Ar_distcode(this.jtxtdistcode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Ar_distcode();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);

	
             jtxtid.setText(obj.toString(Ar_distcode.PROPERTY_ID));
             jtxtdistcode.setText(obj.toString(Ar_distcode.PROPERTY_DISTCODE));
             jtxtdscription.setText(obj.toString(Ar_distcode.PROPERTY_DSCRIPTION));
             jtxtentrydate1.setText(obj.toString(Ar_distcode.PROPERTY_AUDITDATE));
             if (obj.getactive()==1){
                 jchkActive.setSelected(false);
             } else {
                 jchkActive.setSelected(true);
             }
             jtxtaccrevcode.setText(Gl_account.getAccFormat(obj.toString(Ar_distcode.PROPERTY_ACCREVCODE)));
             jtxtaccrevdesc.setText(obj.getAccRevDesc());

             jtxtaccinvcode.setText(Gl_account.getAccFormat(obj.toString(Ar_distcode.PROPERTY_ACCINVCODE)));
             jtxtaccinvdesc.setText(obj.getAccInvDesc());

             jtxtacccogscode.setText(Gl_account.getAccFormat(obj.toString(Ar_distcode.PROPERTY_ACCCOGSCODE)));
             jtxtacccogsdesc.setText(obj.getAccCostDesc());

             jtxtentrydate.setText(obj.toString(Ar_distcode.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Ar_distcode.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Ar_distcode.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Ar_distcode.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Ar_distcode.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Ar_distcode.PROPERTY_DISTCODE, jtxtdistcode.getText()) ;
          obj.fromString(Ar_distcode.PROPERTY_DSCRIPTION, jtxtdscription.getText()) ;

            if (jchkActive.isSelected()){
                obj.fromString(Ar_distcode.PROPERTY_ACTIVE, "0") ;
            } else {
                obj.fromString(Ar_distcode.PROPERTY_ACTIVE, "1") ;
            }
          
          obj.fromString(Ar_distcode.PROPERTY_ACCREVCODE, jtxtaccrevcode.getText().replace("-", "")) ;
          obj.fromString(Ar_distcode.PROPERTY_ACCINVCODE, jtxtaccinvcode.getText().replace("-", "")) ;
          obj.fromString(Ar_distcode.PROPERTY_ACCCOGSCODE, jtxtacccogscode.getText().replace("-", "")) ;
          obj.fromString(Ar_distcode.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Ar_distcode.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Ar_distcode.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Ar_distcode.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        FrmPrintMasterARDistributionCode fprint = new FrmPrintMasterARDistributionCode();
        fprint.jtxtDistCode.setText(jtxtdistcode.getText());
        fprint.setVisible(true);
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
