/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.ar.FrmAr_interest;
 * 
 * .......
 * 
 * 
 * FrmAr_interest frmAr_interest;
 * 
 * .......
 * 
 try {
        if (frmAr_interest == null) {
            frmmAr_interest = new FrmAr_interest(this);
        }
        
        showForm(frmAr_interest);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.ar;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.ar.Ar_interest;
import accapp.objectclasses.ar.Ar_interests;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_accounts;
import java.awt.event.KeyEvent;

/**
 *
 * @author  Generator
 */

public class FrmAr_interest extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmAr_interest";
    
    FrmMainFrame mf ;
    
    
    public Ar_interest obj = new Ar_interest();
    
   
    /** Creates new form Area */
    public FrmAr_interest() throws CodeException {
        initComponents();
    }
    
    public FrmAr_interest(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jtxtid = new javax.swing.JTextField();
        jlblintrschrcode = new javax.swing.JLabel();
        jtxtintrschrcode = new javax.swing.JTextField();
        jtxtdscription = new javax.swing.JTextField();
        jlblacccode = new javax.swing.JLabel();
        jtxtacccode = new javax.swing.JTextField();
        jlblduedays = new javax.swing.JLabel();
        jtxtduedays = new javax.swing.JTextField();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jchkActive = new javax.swing.JCheckBox();
        jbtnBrowseInterest = new javax.swing.JButton();
        jtxtAccDesc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A/R Interest");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Interest");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(330, 70, 30, 17);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(180, 30, 80, 16);

        jlblintrschrcode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblintrschrcode.setText("Interest Code");
        getContentPane().add(jlblintrschrcode);
        jlblintrschrcode.setBounds(50, 70, 140, 14);

        jtxtintrschrcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtintrschrcode.setText("intrschrcode");
        jtxtintrschrcode.setNextFocusableComponent(jtxtdscription);
        jtxtintrschrcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtintrschrcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtintrschrcode);
        jtxtintrschrcode.setBounds(240, 70, 90, 20);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdscription.setText("dscription");
        jtxtdscription.setNextFocusableComponent(jtxtacccode);
        jtxtdscription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdscriptionKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(370, 70, 280, 20);

        jlblacccode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblacccode.setText("Account Code");
        getContentPane().add(jlblacccode);
        jlblacccode.setBounds(50, 100, 140, 14);

        jtxtacccode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtacccode.setText("acccode");
        jtxtacccode.setNextFocusableComponent(jtxtduedays);
        jtxtacccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtacccodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtacccode);
        jtxtacccode.setBounds(240, 100, 150, 20);

        jlblduedays.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblduedays.setText("Due Days");
        getContentPane().add(jlblduedays);
        jlblduedays.setBounds(50, 130, 140, 14);

        jtxtduedays.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtduedays.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtduedays.setText("duedays");
        getContentPane().add(jtxtduedays);
        jtxtduedays.setBounds(240, 130, 80, 20);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 30, 140, 16);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(410, 30, 170, 16);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(580, 30, 140, 16);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(730, 30, 80, 16);

        jchkActive.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jchkActive.setText("Active");
        jchkActive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchkActiveKeyPressed(evt);
            }
        });
        getContentPane().add(jchkActive);
        jchkActive.setBounds(660, 70, 110, 23);

        jbtnBrowseInterest.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseInterest.setText("...");
        jbtnBrowseInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseInterestActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseInterest);
        jbtnBrowseInterest.setBounds(390, 100, 30, 17);

        jtxtAccDesc.setEditable(false);
        jtxtAccDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtAccDesc.setText("AccDesc");
        getContentPane().add(jtxtAccDesc);
        jtxtAccDesc.setBounds(420, 100, 350, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseInterestActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtacccode);
              bd.setSecondValue(jtxtAccDesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseInterestActionPerformed

private void jtxtintrschrcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtintrschrcodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        
        jtxtdscription.requestFocus();
    }

}//GEN-LAST:event_jtxtintrschrcodeKeyPressed

private void jtxtdscriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdscriptionKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jchkActive.requestFocus();
    }
}//GEN-LAST:event_jtxtdscriptionKeyPressed

private void jchkActiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkActiveKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtacccode.requestFocus();
    }
    
}//GEN-LAST:event_jchkActiveKeyPressed

private void jtxtacccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtacccodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setacccode(jtxtacccode.getText().replace("-", ""));
            jtxtAccDesc.setText(obj.getAccountDesc());
        }catch(Exception e){}
        
        jtxtduedays.requestFocus();
    }


}//GEN-LAST:event_jtxtacccodeKeyPressed


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Ar_interests brs = new Ar_interests();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtintrschrcode);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmAr_interest().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowseInterest;
    private javax.swing.JCheckBox jchkActive;
    private javax.swing.JLabel jlblacccode;
    private javax.swing.JLabel jlblduedays;
    private javax.swing.JLabel jlblintrschrcode;
    private javax.swing.JTextField jtxtAccDesc;
    private javax.swing.JTextField jtxtacccode;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtduedays;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtintrschrcode;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Ar_interest(this.jtxtintrschrcode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Ar_interest();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Ar_interest.PROPERTY_ID));
             jtxtintrschrcode.setText(obj.toString(Ar_interest.PROPERTY_INTRSCHRCODE));
             jtxtdscription.setText(obj.toString(Ar_interest.PROPERTY_DSCRIPTION));
             jchkActive.setSelected(obj.getactive() == 1);
             jtxtacccode.setText(Gl_account.getAccFormat(obj.toString(Ar_interest.PROPERTY_ACCCODE)));
             jtxtAccDesc.setText(obj.getAccountDesc());
             jtxtduedays.setText(obj.toString(Ar_interest.PROPERTY_DUEDAYS));
             jtxtentrydate.setText(obj.toString(Ar_interest.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Ar_interest.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Ar_interest.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Ar_interest.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Ar_interest.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Ar_interest.PROPERTY_INTRSCHRCODE, jtxtintrschrcode.getText()) ;
          obj.fromString(Ar_interest.PROPERTY_DSCRIPTION, jtxtdscription.getText()) ;

          obj.setactive(jchkActive.isSelected()? 1 : 0);
          
          obj.fromString(Ar_interest.PROPERTY_ACCCODE, jtxtacccode.getText().replace("-", "")) ;
          obj.fromString(Ar_interest.PROPERTY_DUEDAYS, jtxtduedays.getText()) ;
          obj.fromString(Ar_interest.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Ar_interest.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Ar_interest.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Ar_interest.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
