/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.ar.FrmAp_vendor;
 * 
 * .......
 * 
 * 
 * FrmAp_vendor frmAp_vendor;
 * 
 * .......
 * 
 try {
        if (frmAp_vendor == null) {
            frmmAp_vendor = new FrmAp_vendor(this);
        }
        
        showForm(frmAp_vendor);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.ap;

import accapp.component.browse.FrmBrowseAccountActive;
import accapp.objectclasses.ap.Ap_accset;
import accapp.objectclasses.ap.Ap_accsets;
import accapp.objectclasses.ap.Ap_distcode;
import accapp.objectclasses.ap.Ap_distcodes;
import accapp.objectclasses.ap.Ap_distseth;
import accapp.objectclasses.ap.Ap_distseths;
import accapp.objectclasses.ap.Ap_vendgrp;
import accapp.objectclasses.ap.Ap_vendgrps;
import accapp.objectclasses.ap.Ap_vendor;
import accapp.objectclasses.ap.Ap_vendors;
import accapp.objectclasses.ap.Ap_vendorsts;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_currency;
import accapp.objectclasses.gl.Gl_currencys;
import accapp.objectclasses.gl.Gl_ratetype;
import accapp.objectclasses.gl.Gl_ratetypes;
import accapp.objectclasses.op.Op_address;
import accapp.objectclasses.op.Op_addrtype;
import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.op.Op_addrtypes;
import accapp.objectclasses.op.Op_paymentterm;
import accapp.objectclasses.op.Op_paymentterms;
import accapp.objectclasses.op.Op_phone;
import accapp.objectclasses.op.Op_phones;
import accapp.objectclasses.op.Op_phonetype;
import accapp.objectclasses.op.Op_phonetypes;
import accapp.objectclasses.op.Op_tax;
import accapp.objectclasses.op.Op_taxs;
import common.classinterface.CodeObjectInt;
import common.classinterface.NavigatorBrowseDataInt;
import common.print.FrmPrintMasterAPVendor;
import common.tablemodels.GlobalModel;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Generator
 */

public class FrmAp_vendor extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmAp_vendor";
    FrmMainFrame mf ;
    
    int posttableaddress = 0;

    public Ap_vendor obj = new Ap_vendor();
    
    Object[] dataaddress;
    DefaultTableModel tmodeladdress;


    int posttablephone = 0;
    Object[] dataphone;
    DefaultTableModel tmodelphone;

    boolean onload = false;
    private Date date = new Date();
    DefaultTableModel tmodel=null;

    /** Creates new form Area */
    public FrmAp_vendor() throws CodeException {
        initComponents();
    }
    
    public FrmAp_vendor(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        tmodel=(DefaultTableModel) jtblStatistic.getModel();

        tmodeladdress =  (DefaultTableModel) jtblAddress.getModel();
        dataaddress = new Object[tmodeladdress.getColumnCount()];

        tmodelphone =  (DefaultTableModel) jtblPhone.getModel();
        dataphone = new Object[jtblPhone.getColumnCount()];

        setMonth();

        jtxtyop.setText((date.getYear() + 1900)+"");

    }
    private void setMonth() {

        for(int i = 0; i < 12; i++) {
            jcmbMonth.addItem((i+1));
        }

    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpDistCode = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtid = new javax.swing.JTextField();
        jlblcustmrcode = new javax.swing.JLabel();
        jtxtvendcode = new javax.swing.JTextField();
        jtxtvendorname = new javax.swing.JTextField();
        jlblregdate = new javax.swing.JLabel();
        kdateregdate = new org.kazao.calendar.KazaoCalendarDate();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jchkActive = new javax.swing.JCheckBox();
        jchkHold = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtgrpcode = new javax.swing.JTextField();
        jbtnBrowseGrpCode = new javax.swing.JButton();
        jtxtGrpDescription = new javax.swing.JTextField();
        jtbAddress = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAddress = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtAddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jtxtCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtState = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtZipCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblPhone = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtAddrType = new javax.swing.JTextField();
        jtxtAddrDescription = new javax.swing.JTextField();
        jpanelProcessing = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jbtnBrowseAccountSet = new javax.swing.JButton();
        jtxtAccountSetDesc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jbtnBrowseTermCode = new javax.swing.JButton();
        jtxtTermDesc = new javax.swing.JTextField();
        jtxtaccsetcode = new javax.swing.JTextField();
        jtxttermcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtCredLimitAmt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jcmbDistBy = new javax.swing.JComboBox();
        jtxtDistributedBy = new javax.swing.JTextField();
        jbtnBrowseDist = new javax.swing.JButton();
        jtxtDistributedByDesc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtratetype = new javax.swing.JTextField();
        jbtnBrowseRateType = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtxtcurnccode = new javax.swing.JTextField();
        jbtnBrowseCurr = new javax.swing.JButton();
        jtxtCurncdesc = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jtxttaxcode = new javax.swing.JTextField();
        jbtnBrowseTax = new javax.swing.JButton();
        jtxttaxdescription = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jcmbMonth = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jtxtyop = new javax.swing.JTextField();
        jbtnFind = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblStatistic = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jtxtinvosamt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxtinvoscnt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtppmoamt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtxtppmocnt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtrNotes = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jbtnBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A/P Vendor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Vendor");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(170, 30, 80, 20);

        jlblcustmrcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcustmrcode.setText("Vendor  Code");
        getContentPane().add(jlblcustmrcode);
        jlblcustmrcode.setBounds(60, 70, 140, 13);

        jtxtvendcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtvendcode.setText("vendorcode");
        jtxtvendcode.setNextFocusableComponent(jtxtvendorname);
        jtxtvendcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtvendcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtvendcode);
        jtxtvendcode.setBounds(250, 70, 80, 23);

        jtxtvendorname.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtvendorname.setText("vendorname");
        jtxtvendorname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtvendornameKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtvendorname);
        jtxtvendorname.setBounds(370, 70, 320, 23);

        jlblregdate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregdate.setText("Registration Date");
        getContentPane().add(jlblregdate);
        jlblregdate.setBounds(60, 100, 140, 13);

        kdateregdate.setFont(new java.awt.Font("Dialog", 0, 10));
        kdateregdate.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kdateregdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kdateregdateKeyPressed(evt);
            }
        });
        getContentPane().add(kdateregdate);
        kdateregdate.setBounds(250, 100, 94, 19);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 30, 150, 20);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(420, 30, 150, 20);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(580, 30, 90, 20);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(680, 30, 130, 20);

        jchkActive.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkActive.setText("Active");
        jchkActive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchkActiveKeyPressed(evt);
            }
        });
        getContentPane().add(jchkActive);
        jchkActive.setBounds(380, 100, 120, 24);

        jchkHold.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkHold.setText("Hold");
        jchkHold.setNextFocusableComponent(jtxtgrpcode);
        getContentPane().add(jchkHold);
        jchkHold.setBounds(520, 100, 130, 24);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 10));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel2.setText("Group Code");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 140, 13);

        jtxtgrpcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtgrpcode.setText("grpcode");
        jtxtgrpcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtgrpcodeKeyPressed(evt);
            }
        });
        jPanel1.add(jtxtgrpcode);
        jtxtgrpcode.setBounds(180, 10, 80, 23);

        jbtnBrowseGrpCode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseGrpCode.setText("...");
        jbtnBrowseGrpCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseGrpCodeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBrowseGrpCode);
        jbtnBrowseGrpCode.setBounds(260, 10, 30, 17);

        jtxtGrpDescription.setEditable(false);
        jtxtGrpDescription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtGrpDescription.setText("GroupDescription");
        jPanel1.add(jtxtGrpDescription);
        jtxtGrpDescription.setBounds(300, 10, 290, 23);

        jtbAddress.setFont(new java.awt.Font("Dialog", 0, 10));
        jtbAddress.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbAddressStateChanged(evt);
            }
        });

        jPanel8.setLayout(null);

        jtblAddress.setFont(new java.awt.Font("Dialog", 0, 10));
        jtblAddress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Addr Code", "Addr Type", "Description", "Address", "City", "State", "Zip Code"
            }
        ));
        jtblAddress.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtblAddress.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtblAddressPropertyChange(evt);
            }
        });
        jtblAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblAddressKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblAddress);
        jtblAddress.getColumnModel().getColumn(0).setMinWidth(0);
        jtblAddress.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblAddress.getColumnModel().getColumn(0).setMaxWidth(0);
        jtblAddress.getColumnModel().getColumn(1).setMinWidth(100);
        jtblAddress.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtblAddress.getColumnModel().getColumn(1).setMaxWidth(100);
        jtblAddress.getColumnModel().getColumn(2).setMinWidth(100);
        jtblAddress.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtblAddress.getColumnModel().getColumn(2).setMaxWidth(100);
        jtblAddress.getColumnModel().getColumn(3).setPreferredWidth(120);
        jtblAddress.getColumnModel().getColumn(4).setPreferredWidth(400);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 820, 270);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel8.setText("F5 -> Browse Add type, {tbl Insert} -> Tambah Baris, {tbl Delete} -> Delete Baris");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(0, 270, 710, 13);

        jtbAddress.addTab("Address", jPanel8);

        jPanel9.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setText("Address");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(10, 30, 100, 13);

        jtxtAddress.setColumns(20);
        jtxtAddress.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtAddress.setRows(5);
        jtxtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtAddressKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtxtAddress);

        jPanel9.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 440, 70);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel4.setText("City");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(10, 130, 60, 13);

        jtxtCity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCityActionPerformed(evt);
            }
        });
        jtxtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCityKeyReleased(evt);
            }
        });
        jPanel9.add(jtxtCity);
        jtxtCity.setBounds(100, 130, 350, 23);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel5.setText("State");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(10, 160, 60, 13);

        jtxtState.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtState.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtStateKeyReleased(evt);
            }
        });
        jPanel9.add(jtxtState);
        jtxtState.setBounds(100, 160, 350, 23);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel6.setText("Zip Code");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(10, 190, 70, 13);

        jtxtZipCode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtZipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtZipCodeKeyReleased(evt);
            }
        });
        jPanel9.add(jtxtZipCode);
        jtxtZipCode.setBounds(100, 190, 350, 23);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel7.setText("Phone");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(470, 20, 90, 13);

        jtblPhone.setFont(new java.awt.Font("Dialog", 0, 10));
        jtblPhone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Type Code", "Description", "Phone"
            }
        ));
        jtblPhone.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtblPhonePropertyChange(evt);
            }
        });
        jtblPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblPhoneKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jtblPhone);
        jtblPhone.getColumnModel().getColumn(0).setMinWidth(0);
        jtblPhone.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblPhone.getColumnModel().getColumn(0).setMaxWidth(0);

        jPanel9.add(jScrollPane3);
        jScrollPane3.setBounds(470, 40, 350, 170);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 8));
        jLabel9.setText("F5 -> Browse Account,  {tbl Insert} -> Tambah Baris ,  {tbl Delete} -> Delete Baris");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(470, 220, 350, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel10.setText("Address Type");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(10, 10, 100, 13);

        jtxtAddrType.setEditable(false);
        jtxtAddrType.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtAddrType.setText("addrType");
        jPanel9.add(jtxtAddrType);
        jtxtAddrType.setBounds(110, 10, 80, 23);

        jtxtAddrDescription.setEditable(false);
        jtxtAddrDescription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtAddrDescription.setText("addrDescription");
        jPanel9.add(jtxtAddrDescription);
        jtxtAddrDescription.setBounds(200, 10, 250, 23);

        jtbAddress.addTab("Detail", jPanel9);

        jPanel1.add(jtbAddress);
        jtbAddress.setBounds(20, 40, 830, 310);

        jTabbedPane1.addTab("Address", jPanel1);

        jpanelProcessing.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel13.setForeground(new java.awt.Color(249, 18, 18));
        jLabel13.setText("Account Set *");
        jpanelProcessing.add(jLabel13);
        jLabel13.setBounds(30, 40, 120, 13);

        jbtnBrowseAccountSet.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseAccountSet.setText("...");
        jbtnBrowseAccountSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseAccountSetActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseAccountSet);
        jbtnBrowseAccountSet.setBounds(310, 40, 30, 17);

        jtxtAccountSetDesc.setEditable(false);
        jtxtAccountSetDesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtAccountSetDesc.setText("jtxtAccountSetDesc");
        jpanelProcessing.add(jtxtAccountSetDesc);
        jtxtAccountSetDesc.setBounds(350, 40, 360, 23);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel16.setForeground(new java.awt.Color(249, 18, 18));
        jLabel16.setText("Term Code*");
        jpanelProcessing.add(jLabel16);
        jLabel16.setBounds(30, 70, 110, 13);

        jbtnBrowseTermCode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseTermCode.setText("...");
        jbtnBrowseTermCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseTermCodeActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseTermCode);
        jbtnBrowseTermCode.setBounds(310, 70, 30, 17);

        jtxtTermDesc.setEditable(false);
        jtxtTermDesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtTermDesc.setText("jtxtTermCodeDesc");
        jpanelProcessing.add(jtxtTermDesc);
        jtxtTermDesc.setBounds(350, 70, 360, 23);

        jtxtaccsetcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccsetcode.setText("jtxtaccsetcode");
        jtxtaccsetcode.setNextFocusableComponent(jtxttermcode);
        jtxtaccsetcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaccsetcodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtaccsetcode);
        jtxtaccsetcode.setBounds(180, 40, 120, 23);

        jtxttermcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttermcode.setText("jtxttermcode");
        jtxttermcode.setNextFocusableComponent(jtxtCredLimitAmt);
        jtxttermcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttermcodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxttermcode);
        jtxttermcode.setBounds(180, 70, 120, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 8, 8));
        jLabel1.setText("Credit Limit ");
        jpanelProcessing.add(jLabel1);
        jLabel1.setBounds(30, 110, 130, 13);

        jtxtCredLimitAmt.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtCredLimitAmt.setText("CredLimitAmt");
        jtxtCredLimitAmt.setNextFocusableComponent(jtxtDistributedBy);
        jtxtCredLimitAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCredLimitAmtKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtCredLimitAmt);
        jtxtCredLimitAmt.setBounds(180, 110, 160, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Distributed By*", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(243, 4, 4))); // NOI18N
        jPanel2.setLayout(null);

        jcmbDistBy.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbDistBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distribute Set", "Distribute Code", "GL Account" }));
        jcmbDistBy.setSelectedIndex(2);
        jPanel2.add(jcmbDistBy);
        jcmbDistBy.setBounds(10, 30, 160, 23);

        jtxtDistributedBy.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtDistributedBy.setText("jtxtDistributedBy");
        jtxtDistributedBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDistributedByKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtDistributedBy);
        jtxtDistributedBy.setBounds(180, 30, 190, 23);

        jbtnBrowseDist.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseDist.setText("...");
        jbtnBrowseDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseDistActionPerformed(evt);
            }
        });
        jbtnBrowseDist.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jbtnBrowseDistAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jbtnBrowseDist);
        jbtnBrowseDist.setBounds(380, 30, 30, 20);

        jtxtDistributedByDesc.setEditable(false);
        jtxtDistributedByDesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtDistributedByDesc.setText("jtxtDistributedByDesc");
        jPanel2.add(jtxtDistributedByDesc);
        jtxtDistributedByDesc.setBounds(420, 30, 380, 23);

        jpanelProcessing.add(jPanel2);
        jPanel2.setBounds(30, 140, 810, 70);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel14.setForeground(new java.awt.Color(249, 18, 18));
        jLabel14.setText("Rate Type*");
        jpanelProcessing.add(jLabel14);
        jLabel14.setBounds(30, 220, 130, 13);

        jtxtratetype.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtratetype.setText("ratetype");
        jtxtratetype.setNextFocusableComponent(jtxtcurnccode);
        jtxtratetype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtratetypeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtratetype);
        jtxtratetype.setBounds(180, 220, 70, 23);

        jbtnBrowseRateType.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseRateType.setText("...");
        jbtnBrowseRateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseRateTypeActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseRateType);
        jbtnBrowseRateType.setBounds(260, 220, 30, 17);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(249, 18, 18));
        jLabel15.setText("Currency*");
        jpanelProcessing.add(jLabel15);
        jLabel15.setBounds(30, 250, 100, 13);

        jtxtcurnccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcurnccode.setText("curnccode");
        jtxtcurnccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcurnccodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtcurnccode);
        jtxtcurnccode.setBounds(180, 250, 59, 23);

        jbtnBrowseCurr.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseCurr.setText("...");
        jbtnBrowseCurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseCurrActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseCurr);
        jbtnBrowseCurr.setBounds(260, 250, 30, 20);

        jtxtCurncdesc.setEditable(false);
        jtxtCurncdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtCurncdesc.setText("jtxtCurncdesc");
        jpanelProcessing.add(jtxtCurncdesc);
        jtxtCurncdesc.setBounds(300, 250, 410, 23);

        jTabbedPane1.addTab("Processing", jpanelProcessing);

        jPanel3.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(239, 20, 20));
        jLabel17.setText("Tax Group*");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(20, 20, 100, 13);

        jtxttaxcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttaxcode.setText("jtxttaxcode");
        jtxttaxcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttaxcodeKeyPressed(evt);
            }
        });
        jPanel3.add(jtxttaxcode);
        jtxttaxcode.setBounds(160, 20, 66, 23);

        jbtnBrowseTax.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseTax.setText("...");
        jbtnBrowseTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseTaxActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBrowseTax);
        jbtnBrowseTax.setBounds(230, 20, 30, 20);

        jtxttaxdescription.setEditable(false);
        jtxttaxdescription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttaxdescription.setText("jtxttaxdescription");
        jPanel3.add(jtxttaxdescription);
        jtxttaxdescription.setBounds(270, 20, 380, 23);

        jTabbedPane1.addTab("Taxes", jPanel3);

        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel11.setText("Month");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 10, 80, 13);

        jcmbMonth.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel5.add(jcmbMonth);
        jcmbMonth.setBounds(100, 10, 50, 15);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel12.setText("Year");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(160, 10, 70, 13);

        jtxtyop.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyop.setText("yop");
        jPanel5.add(jtxtyop);
        jtxtyop.setBounds(230, 10, 70, 23);

        jbtnFind.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnFind.setText("Find");
        jbtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFindActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnFind);
        jbtnFind.setBounds(310, 10, 32, 25);

        jtblStatistic.setFont(new java.awt.Font("Dialog", 0, 10));
        jtblStatistic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Invoices", null, null},
                {"Reciepts", null, null},
                {"Discounts", null, null},
                {"Credit Notes", null, null},
                {"Debit Notes", null, null},
                {"Adjustments", null, null},
                {"Write Offs", null, null},
                {"Interest Charges", null, null},
                {"Return Checks", null, null},
                {"Total Invoices Paid", null, null}
            },
            new String [] {
                "Transaction Type", "Amount", "Count"
            }
        ));
        jScrollPane4.setViewportView(jtblStatistic);
        jtblStatistic.getColumnModel().getColumn(0).setPreferredWidth(200);

        jPanel5.add(jScrollPane4);
        jScrollPane4.setBounds(20, 50, 830, 300);

        jTabbedPane1.addTab("Statistics", jPanel5);

        jPanel6.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel20.setText("Outstanding Balance");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(30, 20, 190, 13);

        jtxtinvosamt.setEditable(false);
        jtxtinvosamt.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtinvosamt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtinvosamt.setText("jtxtinvosamt");
        jPanel6.add(jtxtinvosamt);
        jtxtinvosamt.setBounds(230, 20, 150, 23);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel21.setText("No. of Open Invoice");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(410, 20, 170, 13);

        jtxtinvoscnt.setEditable(false);
        jtxtinvoscnt.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtinvoscnt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtinvoscnt.setText("jtxtinvoscnt");
        jPanel6.add(jtxtinvoscnt);
        jtxtinvoscnt.setBounds(600, 20, 150, 23);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel18.setText("Prepayment Amount");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(30, 60, 190, 13);

        jtxtppmoamt.setEditable(false);
        jtxtppmoamt.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtppmoamt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtppmoamt.setText("jtxtppmoamt");
        jPanel6.add(jtxtppmoamt);
        jtxtppmoamt.setBounds(230, 60, 150, 23);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel22.setText("Prepayment Count");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(410, 60, 170, 13);

        jtxtppmocnt.setEditable(false);
        jtxtppmocnt.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtppmocnt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtppmocnt.setText("jtxtppmocnt");
        jPanel6.add(jtxtppmocnt);
        jtxtppmocnt.setBounds(600, 60, 150, 23);

        jTabbedPane1.addTab("Activity", jPanel6);

        jPanel7.setLayout(null);

        jtxtrNotes.setColumns(20);
        jtxtrNotes.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtrNotes.setRows(5);
        jScrollPane5.setViewportView(jtxtrNotes);

        jPanel7.add(jScrollPane5);
        jScrollPane5.setBounds(40, 50, 630, 160);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel19.setText("Comment ");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(40, 20, 120, 13);

        jTabbedPane1.addTab("Comment", jPanel7);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(60, 130, 870, 390);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(330, 70, 30, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveLast();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    try {
	      Ap_vendors brs = new Ap_vendors();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtvendcode);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowseActionPerformed




private void jtxtvendcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvendcodeKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtvendorname.requestFocus();
    }
}//GEN-LAST:event_jtxtvendcodeKeyPressed

private void jbtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFindActionPerformed
    findStatistic();
}//GEN-LAST:event_jbtnFindActionPerformed

private void jbtnBrowseTermCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseTermCodeActionPerformed
    try {
        Op_paymentterms brs = new Op_paymentterms();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxttermcode);
        bd.setSecondValue(jtxtTermDesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseTermCodeActionPerformed

private void jbtnBrowseAccountSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseAccountSetActionPerformed
    try {
        Ap_accsets brs = new Ap_accsets();
        FrmBrowse bd = new FrmBrowse( brs);
        bd.setFirstValue(jtxtaccsetcode);
        bd.setSecondValue(jtxtAccountSetDesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseAccountSetActionPerformed

private void jtbAddressStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbAddressStateChanged

    int row = jtblAddress.getSelectedRow();
    int col = jtblAddress.getSelectedColumn();

    if (row > -1 ) {

        try {
            Op_address address = (Op_address) obj.getOp_Addresss().list().get(row);

            jtxtAddrType.setText(address.getaddrtypecode());
            jtxtAddrDescription.setText(address.getOP_AddrTypeDescription());
            jtxtAddress.setText(address.getaddress());
            jtxtCity.setText(address.getcity());
            jtxtState.setText(address.getstate());
            jtxtZipCode.setText(address.getzipcode());

            showPhones();

        }catch(Exception e) {
            e.printStackTrace();
        }



    }
}//GEN-LAST:event_jtbAddressStateChanged

private void jtblPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblPhoneKeyPressed
    int rowaddress = jtblAddress.getSelectedRow();
    int coladdress = jtblAddress.getSelectedColumn();

    int row = jtblPhone.getSelectedRow();
    int col = jtblPhone.getSelectedColumn();

    if (evt.getKeyCode() == KeyEvent.VK_F5 ){
        try {

            Op_phonetypes brs = new Op_phonetypes(0);

            FrmBrowse bd = new FrmBrowse(tmodelphone, brs, row, 1);
            bd.retrieveData();
            bd.setModal(true);
            bd.setVisible(true);

            Op_phonetype opphone = new Op_phonetype(tmodelphone.getValueAt(row, 1)+"");
            tmodelphone.setValueAt(opphone.getdscription(), row, 2);


        } catch (CodeException ex) {
            ex.printStackTrace();
        }

    }

    if (evt.getKeyCode() == KeyEvent.VK_INSERT) {
        tmodelphone.addRow(dataphone);
        tmodelphone.setValueAt("0", tmodelphone.getRowCount() - 1, 0);
        GlobalUtils.selectCellTable(jtblPhone, tmodelphone.getRowCount() - 1, 1);
    }

    if (evt.getKeyCode() == KeyEvent.VK_DELETE) {

        int iquestion = JOptionPane.showConfirmDialog(null, "Anda Ingin Menghapus Phone Baris Ke " + (row+1), "Hapus ", JOptionPane.YES_NO_OPTION);
        if ( iquestion == JOptionPane.YES_OPTION) {

            try{

                Op_address address = (Op_address) obj.getOp_Addresss().list().get(rowaddress);

                address.removeOp_Phone(row);

            }catch(Exception e){e.printStackTrace();}

            tmodelphone.removeRow(row);

            if (row+1 < tmodelphone.getRowCount()) {
                GlobalUtils.selectCellTable(jtblPhone, row, 1);
            }else{
                GlobalUtils.selectCellTable(jtblPhone, tmodelphone.getRowCount()-1, 1);
            }

        }
    }
}//GEN-LAST:event_jtblPhoneKeyPressed

private void jtblPhonePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtblPhonePropertyChange

    int row = jtblPhone.getSelectedRow();
    int col = jtblPhone.getSelectedColumn();

    if (row > -1) {

        if (col == 1) {

            try{
                Op_phonetype opphone = new Op_phonetype(tmodelphone.getValueAt(row, 1)+"");
                tmodelphone.setValueAt(opphone.getdscription(), row, 2);
            }catch(Exception e) {}

        }

        try{
            cekOpPhone();

        }catch(Exception e) {}

    }
}//GEN-LAST:event_jtblPhonePropertyChange

private void jtxtZipCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtZipCodeKeyReleased
    int row = jtblAddress.getSelectedRow();

    if (row > -1 ) {
        tmodeladdress.setValueAt(jtxtZipCode.getText(), row, 7);
        try {
            cekOpAddress();
        }catch(Exception e) {}

    }
}//GEN-LAST:event_jtxtZipCodeKeyReleased

private void jtxtStateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtStateKeyReleased
    int row = jtblAddress.getSelectedRow();

    if (row > -1 ) {
        tmodeladdress.setValueAt(jtxtState.getText(), row, 6);
        try {
            cekOpAddress();
        }catch(Exception e) {}

    }
}//GEN-LAST:event_jtxtStateKeyReleased

private void jtxtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCityKeyReleased
    int row = jtblAddress.getSelectedRow();

    if (row > -1 ) {
        tmodeladdress.setValueAt(jtxtCity.getText(), row, 5);
        try {
            cekOpAddress();
        }catch(Exception e) {}

    }
}//GEN-LAST:event_jtxtCityKeyReleased

private void jtxtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCityActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtCityActionPerformed

private void jtxtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAddressKeyReleased
    int row = jtblAddress.getSelectedRow();

    if (row > -1 ) {
        tmodeladdress.setValueAt(jtxtAddress.getText(), row, 4);
        try {
            cekOpAddress();
        }catch(Exception e) {}
    }
}//GEN-LAST:event_jtxtAddressKeyReleased

private void jtblAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblAddressKeyPressed

    int row = jtblAddress.getSelectedRow();
    int col = jtblAddress.getSelectedColumn();


    if (evt.getKeyCode() == KeyEvent.VK_F5 ){
        try {

            Op_addrtypes brs = new Op_addrtypes(0);
            FrmBrowse bd = new FrmBrowse(tmodeladdress, brs, row, 2);
            bd.retrieveData();
            bd.setModal(true);
            bd.setVisible(true);

            Op_addrtype opadd = new Op_addrtype(tmodeladdress.getValueAt(row, 2)+"");
            tmodeladdress.setValueAt(opadd.getdscription(), row, 3);

            cekOpAddress();

        } catch (CodeException ex) {
            ex.printStackTrace();
        }

    }

    if (evt.getKeyCode() == KeyEvent.VK_INSERT) {
        tmodeladdress.addRow(dataaddress);
        tmodeladdress.setValueAt("0", tmodeladdress.getRowCount() - 1, 0);
        GlobalUtils.selectCellTable(jtblAddress, tmodeladdress.getRowCount() - 1, 1);
    }

    if (evt.getKeyCode() == KeyEvent.VK_DELETE) {

        int iquestion = JOptionPane.showConfirmDialog(null, "Anda Ingin Menghapus Baris Ke " + (row+1), "Hapus ", JOptionPane.YES_NO_OPTION);
        if ( iquestion == JOptionPane.YES_OPTION) {

            try{
                obj.removeOp_Address(row);
            }catch(Exception e){e.printStackTrace();}

            tmodeladdress.removeRow(row);

            if (row+1 < tmodeladdress.getRowCount()) {
                GlobalUtils.selectCellTable(jtblAddress, row, 1);
            }else{
                GlobalUtils.selectCellTable(jtblAddress, tmodeladdress.getRowCount()-1, 1);
            }

        }
    }
}//GEN-LAST:event_jtblAddressKeyPressed

private void jtblAddressPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtblAddressPropertyChange
    int row = jtblAddress.getSelectedRow();
    int col = jtblAddress.getSelectedColumn();

    if (row > -1) {

        if (col == 2) {

            try{
                Op_addrtype opadd = new Op_addrtype(tmodeladdress.getValueAt(row, 2)+"");


                tmodeladdress.setValueAt(opadd.getdscription(), row, 3);
            }catch(Exception e) {
                e.printStackTrace();

            }

        }



        try{

            cekOpAddress();

        }catch(Exception e) {e.printStackTrace();}

    }
}//GEN-LAST:event_jtblAddressPropertyChange

private void jbtnBrowseGrpCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseGrpCodeActionPerformed

    try {
        Ap_vendgrps brs = new Ap_vendgrps();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxtgrpcode);
        bd.setSecondValue(jtxtGrpDescription);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseGrpCodeActionPerformed

private void jtxtgrpcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtgrpcodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try {
            findGroup();
        }catch(Exception e) {}
        jtblAddress.requestFocus();
    }
}//GEN-LAST:event_jtxtgrpcodeKeyPressed

private void jbtnBrowseDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseDistActionPerformed
    NavigatorBrowseDataInt brs;
    FrmBrowse bd;

    try {
        if (jcmbDistBy.getSelectedIndex() == 0) {
            brs = new Ap_distseths(0);
            bd = new FrmBrowse(brs);
         }else if (jcmbDistBy.getSelectedIndex() == 1) {
            brs = new Ap_distcodes(0);
            bd = new FrmBrowse(brs);
        }else{
            brs = new Gl_accounts(0);
            bd = new FrmBrowseAccountActive(brs);
        }

      bd.setFirstValue(jtxtDistributedBy);
      bd.setSecondValue(jtxtDistributedByDesc);
      bd.setModal(true);
      bd.setVisible(true);

    }catch (Exception e) {    }
}//GEN-LAST:event_jbtnBrowseDistActionPerformed

private void jbtnBrowseRateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseRateTypeActionPerformed

       try {
	      Gl_ratetypes brs = new Gl_ratetypes();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtratetype);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowseRateTypeActionPerformed

private void jbtnBrowseCurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseCurrActionPerformed
       try {
	      Gl_currencys brs = new Gl_currencys();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtcurnccode);
	      bd.setSecondValue(jtxtCurncdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowseCurrActionPerformed

private void jbtnBrowseTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseTaxActionPerformed
       try {
	      Op_taxs brs = new Op_taxs();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxttaxcode);
	      bd.setSecondValue(jtxttaxdescription);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseTaxActionPerformed

private void jtxtvendornameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvendornameKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        kdateregdate.requestFocus();
    }
}//GEN-LAST:event_jtxtvendornameKeyPressed

private void kdateregdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdateregdateKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jchkActive.requestFocus();
    }
}//GEN-LAST:event_kdateregdateKeyPressed

private void jchkActiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkActiveKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jchkHold.requestFocus();
    }
}//GEN-LAST:event_jchkActiveKeyPressed

private void jtxtaccsetcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccsetcodeKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try {
            Ap_accset brs = new Ap_accset(jtxtaccsetcode.getText());
            jtxtAccountSetDesc.setText(brs.getdscription());


        }catch(Exception e) {

        }
        jtxttermcode.requestFocus();
        
    }

}//GEN-LAST:event_jtxtaccsetcodeKeyPressed

private void jtxttermcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttermcodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            Op_paymentterm brs = new Op_paymentterm();

            jtxtTermDesc.setText(brs.getdscription());

            
        }catch (Exception e) {}

        jtxtCredLimitAmt.requestFocus();
    }

}//GEN-LAST:event_jtxttermcodeKeyPressed

private void jtxtCredLimitAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCredLimitAmtKeyPressed


    if(evt.getKeyCode() == evt.VK_ENTER) {
        jtxtDistributedBy.requestFocus();
    }
}//GEN-LAST:event_jtxtCredLimitAmtKeyPressed

private void jbtnBrowseDistAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jbtnBrowseDistAncestorAdded
    // TODO add your handling code here:
}//GEN-LAST:event_jbtnBrowseDistAncestorAdded

private void jtxtDistributedByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDistributedByKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        CodeObjectInt brs;

        try {

            if (jcmbDistBy.getSelectedIndex() == 0) {
                brs = new Ap_distseth(jtxtDistributedBy.getText());
                jtxtDistributedByDesc.setText(brs.toString(Ap_distseth.PROPERTY_DSCRIPTION));
            }else if (jcmbDistBy.getSelectedIndex() == 0) {
                brs = new Ap_distcode(jtxtDistributedBy.getText());
                jtxtDistributedByDesc.setText(brs.toString(Ap_distcode.PROPERTY_DSCRIPTION));
            }else{
                brs = new Gl_account(jtxtDistributedBy.getText());
                jtxtDistributedByDesc.setText(brs.toString(Gl_account.PROPERTY_ACCDESC));
            }

        }catch(Exception e) {}
        jtxtratetype.requestFocus();
    }
}//GEN-LAST:event_jtxtDistributedByKeyPressed

private void jtxtratetypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtratetypeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtcurnccode.requestFocus();
    }
}//GEN-LAST:event_jtxtratetypeKeyPressed

private void jtxtcurnccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcurnccodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            Gl_currency brs = new Gl_currency(jtxtcurnccode.getText());
            jtxtCurncdesc.setText(brs.getcurncdesc());


        }catch(Exception e) {}

        jtxttaxcode.requestFocus();
    }
}//GEN-LAST:event_jtxtcurnccodeKeyPressed

private void jtxttaxcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttaxcodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        try{
           Op_tax brs = new Op_tax(jtxttaxcode.getText());
           jtxttaxdescription.setText(brs.getdscription());

        }catch(Exception e) {}
    }
}//GEN-LAST:event_jtxttaxcodeKeyPressed


private void findGroup() throws CodeException {
    Ap_vendgrp vendgrp = new Ap_vendgrp(jtxtgrpcode.getText());
    if (vendgrp.getID() != Ap_vendgrp.NULLID) {
        jtxtaccsetcode.setText(vendgrp.getaccsetcode());
        jtxtAccountSetDesc.setText(vendgrp.getAP_accsetDesc());

        jtxttermcode.setText(vendgrp.gettermcode());
        jtxtTermDesc.setText(vendgrp.getOp_PaymentTermDesc());

    }

}


private void findStatistic() {
     setCursor(GlobalUtils.HOURGLASSCURSOR);

    try{

        Ap_vendorsts vrc = new Ap_vendorsts();
        vrc.searchData(jtxtyop.getText(), jcmbMonth.getSelectedItem()+"", jtxtgrpcode.getText());


        tmodel.setValueAt(vrc.getinvamt(), 0, 1);
        tmodel.setValueAt(vrc.getinvcnt(), 0, 2);

        tmodel.setValueAt(vrc.getpayamt(), 1, 1);
        tmodel.setValueAt(vrc.getpaycnt(), 1, 2);

        tmodel.setValueAt(vrc.getdiscamt(), 2, 1);
        tmodel.setValueAt(vrc.getdisccnt(), 2, 2);

        tmodel.setValueAt(vrc.getcnamt(), 3, 1);
        tmodel.setValueAt(vrc.getcncnt(), 3, 2);

        tmodel.setValueAt(vrc.getdnamt(), 4, 1);
        tmodel.setValueAt(vrc.getdncnt(), 4, 2);

        tmodel.setValueAt(vrc.getadjamt(), 5, 1);
        tmodel.setValueAt(vrc.getadjcnt(), 5, 2);

        tmodel.setValueAt(vrc.getwroffamt(), 6, 1);
        tmodel.setValueAt(vrc.getwroffcnt(), 6, 2);

        tmodel.setValueAt(vrc.getinttamt(), 7, 1);
        tmodel.setValueAt(vrc.getinttcnt(), 7, 2);

        tmodel.setValueAt(vrc.getrtrchckamt(), 8, 1);
        tmodel.setValueAt(vrc.getrtrchckcnt(), 8, 2);

        tmodel.setValueAt(vrc.getinvpaidamt(), 9, 1);
        tmodel.setValueAt(vrc.getinvpaidcnt(), 9, 2);


    }catch(Exception e) {}
    setCursor(GlobalUtils.NORMALCURSOR);

}

private void cekOpPhone() throws CodeException {
    int rowaddress = jtblAddress.getSelectedRow();
    int coladdress = jtblAddress.getSelectedColumn();

    int row = jtblPhone.getSelectedRow();
    int col = jtblPhone.getSelectedColumn();


    Op_address address = (Op_address) obj.getOp_Addresss().list().get(rowaddress);
    Op_phone opphone;

    if (row > address.getOP_Phones().size() - 1) {
        opphone = new Op_phone();
        address.getOP_Phones().add(opphone);
    }else{
        opphone = (Op_phone) address.getOP_Phones().list().get(row);
    }

    long idopphone = 0 ;
    try{
        idopphone = Long.parseLong(tmodelphone.getValueAt(row, 0)+"");
    }catch (Exception e){}

    opphone.setID(idopphone);
    opphone.setownercode(address.getownercode());
    opphone.setaddrcode(address.getaddrcode());
    opphone.setaddrtypecode(address.getaddrtypecode());
    opphone.setphonetypecode(tmodelphone.getValueAt(row, 1) +"");
    opphone.setphone(tmodelphone.getValueAt(row, 3) +"");

    address.replaceOp_Phone(row, opphone);

}

private void cekOpAddress() throws CodeException {

    int row = jtblAddress.getSelectedRow();
    int col = jtblAddress.getSelectedColumn();


    Op_address opaddress;
    if (row > obj.getOp_Addresss().size() - 1) {
        opaddress = new Op_address();
        obj.getOp_Addresss().add(opaddress);
    }else{
        opaddress = (Op_address) obj.getOp_Addresss().list().get(row);
    }

    long idopaddress = 0 ;
    try{
        idopaddress = Long.parseLong(tmodeladdress.getValueAt(row, 0)+"");
    }catch (Exception e){}

    opaddress.setID(idopaddress);
    opaddress.setaddrcode(tmodeladdress.getValueAt(row, 1)+"");
    opaddress.setaddrtypecode(tmodeladdress.getValueAt(row, 2) +"");
    opaddress.setdscription(tmodeladdress.getValueAt(row, 3)==null ? "" : tmodeladdress.getValueAt(row, 3)+"");
    opaddress.setaddress(tmodeladdress.getValueAt(row, 4)==null? "" : tmodeladdress.getValueAt(row, 4)+"");
    opaddress.setcity(tmodeladdress.getValueAt(row, 5) == null ? "" : tmodeladdress.getValueAt(row, 5)+"");
    opaddress.setstate(tmodeladdress.getValueAt(row, 6) == null?"" : tmodeladdress.getValueAt(row, 6)+"");
    opaddress.setzipcode(tmodeladdress.getValueAt(row, 7) == null ?"" : tmodeladdress.getValueAt(row, 7)+"");


    obj.replaceOp_Address(row, opaddress);

        System.out.println("xxxx");

}
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    if (!onload) {
        try {
            moveLast();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
        onload = true;
    }

    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmAp_vendor().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup btnGrpDistCode;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowseAccountSet;
    private javax.swing.JButton jbtnBrowseCurr;
    private javax.swing.JButton jbtnBrowseDist;
    private javax.swing.JButton jbtnBrowseGrpCode;
    private javax.swing.JButton jbtnBrowseRateType;
    private javax.swing.JButton jbtnBrowseTax;
    private javax.swing.JButton jbtnBrowseTermCode;
    private javax.swing.JButton jbtnFind;
    private javax.swing.JCheckBox jchkActive;
    private javax.swing.JCheckBox jchkHold;
    private javax.swing.JComboBox jcmbDistBy;
    private javax.swing.JComboBox jcmbMonth;
    private javax.swing.JLabel jlblcustmrcode;
    private javax.swing.JLabel jlblregdate;
    private javax.swing.JPanel jpanelProcessing;
    private javax.swing.JTabbedPane jtbAddress;
    private javax.swing.JTable jtblAddress;
    private javax.swing.JTable jtblPhone;
    private javax.swing.JTable jtblStatistic;
    private javax.swing.JTextField jtxtAccountSetDesc;
    private javax.swing.JTextField jtxtAddrDescription;
    private javax.swing.JTextField jtxtAddrType;
    private javax.swing.JTextArea jtxtAddress;
    private javax.swing.JTextField jtxtCity;
    private javax.swing.JTextField jtxtCredLimitAmt;
    private javax.swing.JTextField jtxtCurncdesc;
    private javax.swing.JTextField jtxtDistributedBy;
    private javax.swing.JTextField jtxtDistributedByDesc;
    private javax.swing.JTextField jtxtGrpDescription;
    private javax.swing.JTextField jtxtState;
    private javax.swing.JTextField jtxtTermDesc;
    private javax.swing.JTextField jtxtZipCode;
    private javax.swing.JTextField jtxtaccsetcode;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtcurnccode;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtgrpcode;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtinvosamt;
    private javax.swing.JTextField jtxtinvoscnt;
    private javax.swing.JTextField jtxtppmoamt;
    private javax.swing.JTextField jtxtppmocnt;
    private javax.swing.JTextArea jtxtrNotes;
    private javax.swing.JTextField jtxtratetype;
    private javax.swing.JTextField jtxttaxcode;
    private javax.swing.JTextField jtxttaxdescription;
    private javax.swing.JTextField jtxttermcode;
    private javax.swing.JTextField jtxtvendcode;
    private javax.swing.JTextField jtxtvendorname;
    private javax.swing.JTextField jtxtyop;
    private org.kazao.calendar.KazaoCalendarDate kdateregdate;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Ap_vendor(this.jtxtvendcode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Ap_vendor();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    private void validasi() throws CodeException {



         if(!jtxtgrpcode.getText().equals("")){
             Ap_vendgrp argrp = new Ap_vendgrp(jtxtgrpcode.getText());
             if (argrp.getID() == Ap_vendgrp.NULLID) {
                 throw new CodeException("Vendor Group Code  " + jtxtgrpcode.getText() + " Tidak Diketemukan ");
             }
         }

         if (!jtxtaccsetcode.getText().equals("")) {
             Ap_accset arc = new Ap_accset(jtxtaccsetcode.getText());
             if (arc.getID() == Ap_accset.NULLID) {
                throw new CodeException("Account Set  " + jtxtaccsetcode.getText() + " Tidak Diketemukan");
             }
         } else {
             throw new CodeException("Account Set  Cannot Be Empty");
         }


         if (!jtxttermcode.getText().equals("")){
            Op_paymentterm opp = new Op_paymentterm(jtxttermcode.getText());
            if (opp.getID() == Op_paymentterm.NULLID) {
                throw new CodeException("Term Code " + jtxttermcode.getText() + " Tidak Diketemukan ");                
            }
         } else {
             throw new CodeException("Term Code  Cannot Be Empty");
         }

//         Distribute Set
//

         if (GlobalUtils.churuf(jcmbDistBy.getSelectedItem()).equalsIgnoreCase("Distribute Set")){
             if (!jtxtDistributedBy.getText().equals("")){
                Ap_distseth apds = new Ap_distseth(jtxtDistributedBy.getText().replace("-", ""));
                if (apds.getID() == Ap_distseth.NULLID) {
                    throw new CodeException("Distribute Set " + jtxtDistributedBy.getText() + " Tidak Diketemukan ");
                }
             } else {
                 throw new CodeException("Distribute Set Cannot Be Empty");
             }
        }

         if (GlobalUtils.churuf(jcmbDistBy.getSelectedItem()).equalsIgnoreCase("Distribute Code")){
             if (!jtxtDistributedBy.getText().equals("")){
                Ap_distcode apdc = new Ap_distcode(jtxtDistributedBy.getText().replace("-", ""));
                if (apdc.getID() == Ap_distcode.NULLID) {
                    throw new CodeException("Distribute Code " + jtxtDistributedBy.getText() + " Tidak Diketemukan ");
                }
             } else {
                 throw new CodeException("Distribute Code Cannot Be Empty");
             }
        }

         if (GlobalUtils.churuf(jcmbDistBy.getSelectedItem()).equalsIgnoreCase("GL Account")){
             if (!jtxtDistributedBy.getText().equals("")){
                Gl_account glacc = new Gl_account(jtxtDistributedBy.getText().replace("-", ""));
                if (glacc.getID() == Gl_account.NULLID) {
                    throw new CodeException("Account Code " + jtxtDistributedBy.getText() + " Tidak Diketemukan ");
                }
             } else {
                 throw new CodeException("Account Code Cannot Be Empty");
             }
        }

         if (!jtxtratetype.getText().equals("")){
            Gl_ratetype glrt = new Gl_ratetype(Gl_ratetype.PROPERTY_RATETYPE,jtxtratetype.getText().replace("-", ""));
            if (glrt.getID() == Gl_ratetype.NULLID) {
                throw new CodeException("Rate Type " + jtxtratetype.getText() + " Tidak Diketemukan ");
            }
         } else {
             throw new CodeException("Rate Type Cannot Be Empty");
         }

         if (!jtxtcurnccode.getText().equals("")){
            Gl_currency glcr = new Gl_currency(jtxtcurnccode.getText().replace("-", ""));
            if (glcr.getID() == Gl_currency.NULLID) {
                throw new CodeException("Currency " + jtxtcurnccode.getText() + " Tidak Diketemukan ");
            }
         } else {
             throw new CodeException("Currency Cannot Be Empty");
         }

         if (!jtxttaxcode.getText().equals("")){
            Op_tax opt = new Op_tax(jtxttaxcode.getText().replace("-", ""));
            if (opt.getID() == Op_tax.NULLID) {
                throw new CodeException("Tax Group " + jtxttaxcode.getText() + " Tidak Diketemukan ");
            }
         } else {
             throw new CodeException("Tax Group Cannot Be Empty");
         }
    }



    public void saveData() throws CodeException {
        validasi();


        istatus = 0;
       
        setData();
        obj.save();
        jtxtid.setText(obj.getID()+"");
        jtxtentrydate.setText(obj.toString(Ap_vendor.PROPERTY_ENTRYDATE));
        jtxtauditdate.setText(obj.toString(Ap_vendor.PROPERTY_AUDITDATE));
        jtxtaudituser.setText(obj.toString(Ap_vendor.PROPERTY_AUDITUSER));
        jtxtcmpnyid.setText(obj.toString(Ap_vendor.PROPERTY_CMPNYID));

        
        if (jtbAddress.getSelectedIndex() == 0) {
            for (int i = 0 ; i < tmodeladdress.getRowCount(); i++) {

                try {
                    Op_address address = (Op_address) obj.getOp_Addresss().list().get(i);
                    tmodeladdress.setValueAt(address.getID(), i, 0);
                    tmodeladdress.setValueAt(address.getaddrcode(), i, 1);
                }catch(Exception e) {}
            }

        }else{
            int row = jtblAddress.getSelectedRow();
            Op_address address = (Op_address) obj.getOp_Addresss().list().get(row);

            for (int i=0; i <tmodelphone.getRowCount(); i++) {
                try{
                    Op_phone phone = (Op_phone) address.getOP_Phones().list().get(i);
                    tmodelphone.setValueAt(phone.getID(),  i, 0);
                }catch(Exception e) {}

            }
        }

        //jtbAddress.setSelectedIndex(0);
        
        //showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Ap_vendor.PROPERTY_ID));
             jtxtvendcode.setText(obj.toString(Ap_vendor.PROPERTY_VENDCODE));
             jtxtvendorname.setText(obj.toString(Ap_vendor.PROPERTY_VENDNAME));
             jtxtgrpcode.setText(obj.toString(Ap_vendor.PROPERTY_GRPCODE));
             jtxtGrpDescription.setText(obj.getVendGroupDescription());

             jchkActive.setSelected(obj.getactive() == 1);
             jchkHold.setSelected(obj.gethold() == 1);

             if (obj.getregdate() != null) {
                kdateregdate.setDate(obj.getregdate());  
             }

             jtxtentrydate.setText(obj.toString(Ap_vendor.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Ap_vendor.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Ap_vendor.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Ap_vendor.PROPERTY_CMPNYID));

             jtbAddress.setSelectedIndex(0);


             jtxtaccsetcode.setText(obj.getaccsetcode());


             jtxtAccountSetDesc.setText(obj.getAccountSetDescription());

             
             jtxttermcode.setText(obj.gettermcode());
             jtxtTermDesc.setText(obj.getTermDescription());


             jtxtCredLimitAmt.setText(obj.getcredlimitamt()+"");

             jcmbDistBy.setSelectedIndex( (int) obj.getdistby());

             if (obj.getdistby() == 0) {
                 jtxtDistributedBy.setText(obj.getdistsetcode());
                 jtxtDistributedByDesc.setText(obj.getAp_distsethDesc());
             }else if (obj.getdistby() == 1) {
                 jtxtDistributedBy.setText(obj.getdistcode());
                 jtxtDistributedByDesc.setText(obj.getAp_distDesc());
             }else{
                 jtxtDistributedBy.setText(obj.getglacccodefmt());
                 jtxtDistributedByDesc.setText(obj.getGLAccDesc());
             }


             jtxtratetype.setText(obj.getratetype());
             jtxtcurnccode.setText(obj.getcurnccode());
             jtxtCurncdesc.setText(obj.getCurr_Desc());

             jtxttaxcode.setText(obj.gettaxcode());
             jtxttaxdescription.setText(obj.getOP_TaxDesc());
             
             jtxtppmoamt.setText(obj.getppmoamt()+"");
             jtxtppmocnt.setText(obj.getppmocnt()+"");

             jtxtrNotes.setText(obj.getnotes());

             jtxtinvosamt.setText(obj.getinvosamt()+"");
             jtxtinvoscnt.setText(obj.getinvoscnt()+ "");

             showAddresses();


        setCursor(GlobalUtils.NORMALCURSOR);
    }

    private void showAddresses() throws CodeException {

        GlobalModel.clearRow(tmodeladdress);
        posttableaddress = -1;

        
        for(Object o : obj.getOp_Addresss().list()) {
            Op_address address = (Op_address) o;

            tmodeladdress.addRow(dataaddress);
            tmodeladdress.setValueAt(address.getID(), tmodeladdress.getRowCount() - 1, 0);
            tmodeladdress.setValueAt(address.getaddrcode(), tmodeladdress.getRowCount() - 1, 1);
            tmodeladdress.setValueAt(address.getaddrtypecode() ==null?"":address.getaddrtypecode(), tmodeladdress.getRowCount() - 1, 2);
            tmodeladdress.setValueAt(address.getdscription()==null?"":address.getdscription(), tmodeladdress.getRowCount() - 1, 3);
            tmodeladdress.setValueAt(address.getaddress()==null?"":address.getaddress(), tmodeladdress.getRowCount() - 1, 4);
            tmodeladdress.setValueAt(address.getcity()==null?"":address.getcity(), tmodeladdress.getRowCount() - 1, 5);
            tmodeladdress.setValueAt(address.getstate()==null?"":address.getstate() , tmodeladdress.getRowCount() - 1, 6);
            tmodeladdress.setValueAt(address.getzipcode()==null?"":address.getzipcode(), tmodeladdress.getRowCount() - 1, 7);

        }
        tmodeladdress.addRow(dataaddress);
        tmodeladdress.setValueAt("0", tmodeladdress.getRowCount() - 1, 0);
        GlobalUtils.selectCellTable(jtblAddress, 0, 1);
    }

    private void showPhones() throws CodeException {
        int row = jtblAddress.getSelectedRow();

        GlobalModel.clearRow(tmodelphone);
        posttablephone = -1;

        Op_phones phones = ((Op_address) obj.getOp_Addresss().list().get(row)).getOP_Phones();

        for(Object o : phones.list()) {
            Op_phone phone = (Op_phone) o;

            tmodelphone.addRow(dataphone);

            tmodelphone.setValueAt(phone.getID(), tmodelphone.getRowCount() - 1, 0);
            tmodelphone.setValueAt(phone.getphonetypecode(), tmodelphone.getRowCount() - 1, 1);
            tmodelphone.setValueAt(phone.getOP_PhoneDescription(), tmodelphone.getRowCount() - 1, 2);
            tmodelphone.setValueAt(phone.getphone(), tmodelphone.getRowCount() - 1, 3);


        }
        tmodelphone.addRow(dataphone);
        tmodelphone.setValueAt("0", tmodelphone.getRowCount() - 1, 0);
        GlobalUtils.selectCellTable(jtblPhone, 0, 1);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Ap_vendor.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_VENDCODE, jtxtvendcode.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_VENDNAME, jtxtvendorname.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_GRPCODE, jtxtgrpcode.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Ap_vendor.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

          obj.setaccsetcode(jtxtaccsetcode.getText());
          obj.settermcode(jtxttermcode.getText());

          obj.setactive(jchkActive.isSelected()? 1 : 0);
          obj.sethold(jchkHold.isSelected()? 1 : 0);

          obj.fromString(Ap_vendor.PROPERTY_CREDLIMITAMT, jtxtCredLimitAmt.getText()) ;
          obj.setdistby(jcmbDistBy.getSelectedIndex());
          if (jcmbDistBy.getSelectedIndex() == 0) {
              obj.setdistsetcode(jtxtDistributedBy.getText());
          }else if (jcmbDistBy.getSelectedIndex() == 1) {
              obj.setdistcode(jtxtDistributedBy.getText());
          }else {
              obj.setglacccode(jtxtDistributedBy.getText().replace("-", ""));
          }

          obj.setratetype(jtxtratetype.getText());
          obj.setcurnccode(jtxtcurnccode.getText());

          obj.settaxcode(jtxttaxcode.getText());
          
          obj.fromString(Ap_vendor.PROPERTY_NOTES, jtxtrNotes.getText());
          obj.fromString(Ap_vendor.PROPERTY_INVOSAMT, jtxtinvosamt.getText());
          obj.fromString(Ap_vendor.PROPERTY_INVOSCNT, jtxtinvoscnt.getText());


          
    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        FrmPrintMasterAPVendor fprint = new FrmPrintMasterAPVendor();
        fprint.jtxtVendCodeFr.setText(jtxtvendcode.getText());
        fprint.jtxtVendCodeTo.setText(jtxtvendcode.getText());
        fprint.jtxtyopfr.setText(jtxtyop.getText());
        fprint.setVisible(true);
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
