/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.ap.FrmAp_distcode;
 * 
 * .......
 * 
 * 
 * FrmAp_distcode frmAp_distcode;
 * 
 * .......
 * 
 try {
        if (frmAp_distcode == null) {
            frmmAp_distcode = new FrmAp_distcode(this);
        }
        
        showForm(frmAp_distcode);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.ap;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.ap.Ap_distcode;
import accapp.objectclasses.ap.Ap_distcodes;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_accounts;
import common.print.FrmPrintMasterAPDistributionCode;

/**
 *
 * @author  Generator
 */

public class FrmAp_distcode extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmAp_distcode";
    
    FrmMainFrame mf ;
    
    
    public Ap_distcode obj = new Ap_distcode();
    
   
    /** Creates new form Area */
    public FrmAp_distcode() throws CodeException {
        initComponents();
    }
    
    public FrmAp_distcode(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtid = new javax.swing.JTextField();
        jlbldistcode = new javax.swing.JLabel();
        jtxtdistcode = new javax.swing.JTextField();
        jtxtdscription = new javax.swing.JTextField();
        jlblglacccode = new javax.swing.JLabel();
        jtxtglacccode = new javax.swing.JTextField();
        jtxtobjtype = new javax.swing.JTextField();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jchkActive = new javax.swing.JCheckBox();
        jbtnBrowseGlAccount = new javax.swing.JButton();
        jtxtglaccdesc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ap_distcode");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Ap_distcode");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(180, 30, 80, 16);

        jlbldistcode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldistcode.setText("Distribution Code");
        getContentPane().add(jlbldistcode);
        jlbldistcode.setBounds(70, 100, 140, 14);

        jtxtdistcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdistcode.setText("distcode");
        jtxtdistcode.setNextFocusableComponent(jtxtdscription);
        jtxtdistcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdistcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtdistcode);
        jtxtdistcode.setBounds(260, 100, 80, 20);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdscription.setText("dscription");
        jtxtdscription.setNextFocusableComponent(jchkActive);
        jtxtdscription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdscriptionKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(380, 100, 470, 20);

        jlblglacccode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblglacccode.setText("GL Account Code");
        getContentPane().add(jlblglacccode);
        jlblglacccode.setBounds(70, 150, 140, 14);

        jtxtglacccode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtglacccode.setText("glacccode");
        jtxtglacccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtglacccodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtglacccode);
        jtxtglacccode.setBounds(260, 150, 150, 20);

        jtxtobjtype.setEditable(false);
        jtxtobjtype.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtobjtype.setText("objtype");
        getContentPane().add(jtxtobjtype);
        jtxtobjtype.setBounds(820, 30, 80, 16);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(310, 30, 130, 16);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(450, 30, 110, 16);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(570, 30, 110, 16);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(690, 30, 110, 16);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(350, 100, 20, 20);

        jchkActive.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jchkActive.setText("Active");
        jchkActive.setNextFocusableComponent(jchkActive);
        jchkActive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchkActiveKeyPressed(evt);
            }
        });
        getContentPane().add(jchkActive);
        jchkActive.setBounds(260, 120, 100, 23);

        jbtnBrowseGlAccount.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseGlAccount.setText("...");
        jbtnBrowseGlAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseGlAccountActionPerformed(evt);
            }
        });
        jbtnBrowseGlAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnBrowseGlAccountKeyPressed(evt);
            }
        });
        getContentPane().add(jbtnBrowseGlAccount);
        jbtnBrowseGlAccount.setBounds(420, 150, 20, 17);

        jtxtglaccdesc.setEditable(false);
        jtxtglaccdesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtglaccdesc.setText("jxtglaccdesc");
        getContentPane().add(jtxtglaccdesc);
        jtxtglaccdesc.setBounds(450, 150, 400, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
        try {
	      Ap_distcodes brs = new Ap_distcodes();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtdistcode);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtdistcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdistcodeKeyPressed


    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtdscription.requestFocus();
    }
    
}//GEN-LAST:event_jtxtdistcodeKeyPressed

private void jtxtdscriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdscriptionKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jchkActive.requestFocus();
    }
}//GEN-LAST:event_jtxtdscriptionKeyPressed

private void jchkActiveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkActiveKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtglacccode.requestFocus();
        
    }
}//GEN-LAST:event_jchkActiveKeyPressed

private void jbtnBrowseGlAccountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnBrowseGlAccountKeyPressed

}//GEN-LAST:event_jbtnBrowseGlAccountKeyPressed

private void jbtnBrowseGlAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseGlAccountActionPerformed
        try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse( brs);

	      bd.setFirstValue(jtxtglacccode);
              bd.setSecondValue(jtxtglaccdesc);

              bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowseGlAccountActionPerformed

private void jtxtglacccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtglacccodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        try{
            Gl_account gl = new Gl_account(jtxtglacccode.getText().replace("-", ""));
            jtxtglacccode.setText(gl.getaccfmttd());
            jtxtglaccdesc.setText(gl.getaccdesc());
        }catch(Exception e){}
    }
}//GEN-LAST:event_jtxtglacccodeKeyPressed


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

                                                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmAp_distcode().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowseGlAccount;
    private javax.swing.JCheckBox jchkActive;
    private javax.swing.JLabel jlbldistcode;
    private javax.swing.JLabel jlblglacccode;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtdistcode;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtglacccode;
    private javax.swing.JTextField jtxtglaccdesc;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtobjtype;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Ap_distcode(this.jtxtdistcode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Ap_distcode();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Ap_distcode.PROPERTY_ID));
             jtxtdistcode.setText(obj.toString(Ap_distcode.PROPERTY_DISTCODE));

             jchkActive.setSelected(obj.getactive() == 1 );

             jtxtdscription.setText(obj.toString(Ap_distcode.PROPERTY_DSCRIPTION));

             jtxtglacccode.setText(obj.getglacccodefmt());
             jtxtglaccdesc.setText(obj.getGLAccDesc());

             jtxtobjtype.setText(obj.toString(Ap_distcode.PROPERTY_OBJTYPE));
             jtxtentrydate.setText(obj.toString(Ap_distcode.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Ap_distcode.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Ap_distcode.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Ap_distcode.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Ap_distcode.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Ap_distcode.PROPERTY_DISTCODE, jtxtdistcode.getText()) ;
          obj.setactive(jchkActive.isSelected() ? 1 : 0);
          obj.fromString(Ap_distcode.PROPERTY_DSCRIPTION, jtxtdscription.getText()) ;

          obj.setglacccode(jtxtglacccode.getText());

          obj.fromString(Ap_distcode.PROPERTY_OBJTYPE, jtxtobjtype.getText()) ;
          obj.fromString(Ap_distcode.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Ap_distcode.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Ap_distcode.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Ap_distcode.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        FrmPrintMasterAPDistributionCode fprint = new FrmPrintMasterAPDistributionCode();
        fprint.jtxtDistCode.setText(jtxtdistcode.getText());
        fprint.setVisible(true);
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
