/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.ar.FrmAp_vendor;
 * 
 * .......
 * 
 * 
 * FrmAp_vendor frmAp_vendor;
 * 
 * .......
 * 
 try {
        if (frmAp_vendor == null) {
            frmmAp_vendor = new FrmAp_vendor(this);
        }
        
        showForm(frmAp_vendor);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.ap;

import accapp.component.browse.FrmBrowseAccountActive;
import accapp.objectclasses.ap.Ap_accset;
import accapp.objectclasses.ap.Ap_accsets;
import accapp.objectclasses.ap.Ap_distcode;
import accapp.objectclasses.ap.Ap_distcodes;
import accapp.objectclasses.ap.Ap_distseth;
import accapp.objectclasses.ap.Ap_distseths;
import accapp.objectclasses.ap.Ap_vendgrp;
import accapp.objectclasses.ap.Ap_vendgrps;
import accapp.objectclasses.ap.Ap_vendgrpsts;
import accapp.objectclasses.cashbook.Cb_bank;
import accapp.objectclasses.cashbook.Cb_banks;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_currencys;
import accapp.objectclasses.gl.Gl_ratetype;
import accapp.objectclasses.gl.Gl_ratetypes;
import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.op.Op_paymentterm;
import accapp.objectclasses.op.Op_paymentterms;
import accapp.objectclasses.op.Op_taxs;
import common.classinterface.CodeObjectInt;
import common.classinterface.NavigatorBrowseDataInt;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Generator
 */

public class FrmAp_vendorgrp extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmAp_vendor";
    FrmMainFrame mf ;
    
    int posttableaddress = 0;

    public Ap_vendgrp obj = new Ap_vendgrp();
    



    boolean onload = false;
    private Date date = new Date();
    DefaultTableModel tmodel=null;

    /** Creates new form Area */
    public FrmAp_vendorgrp() throws CodeException {
        initComponents();
    }
    
    public FrmAp_vendorgrp(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        tmodel=(DefaultTableModel) jtblStatistic.getModel();


        setMonth();

        jtxtyop.setText((date.getYear() + 1900)+"");

    }
    private void setMonth() {

        for(int i = 0; i < 12; i++) {
            jcmbMonth.addItem((i+1));
        }

    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpDistCode = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtid = new javax.swing.JTextField();
        jlblcustmrcode = new javax.swing.JLabel();
        jtxtvendgrpcode = new javax.swing.JTextField();
        jtxtDescription = new javax.swing.JTextField();
        jlblregdate = new javax.swing.JLabel();
        kdateregdate = new org.kazao.calendar.KazaoCalendarDate();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jchkActive = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanelProcessing = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jbtnBrowseAccountSet = new javax.swing.JButton();
        jtxtAccountSetDesc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jbtnBrowseTermCode = new javax.swing.JButton();
        jtxtTermDesc = new javax.swing.JTextField();
        jtxtaccsetcode = new javax.swing.JTextField();
        jtxttermcode = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jcmbDistBy = new javax.swing.JComboBox();
        jtxtDistributedBy = new javax.swing.JTextField();
        jbtnBrowseDist = new javax.swing.JButton();
        jtxtDistributedByDesc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtratetype = new javax.swing.JTextField();
        jbtnBrowseRateType = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtxtcurnccode = new javax.swing.JTextField();
        jbtnBrowseCurr = new javax.swing.JButton();
        jtxtRateTypeDesc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtbankcode = new javax.swing.JTextField();
        jbtnBrowseBank = new javax.swing.JButton();
        jtxtBankName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jtxttaxcode = new javax.swing.JTextField();
        jbtnBrowseTax = new javax.swing.JButton();
        jtxttaxdescription = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jcmbMonth = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jtxtyop = new javax.swing.JTextField();
        jbtnFind = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblStatistic = new javax.swing.JTable();
        jbtnBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A/P Vendor Group");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setText(" : : Vendor Group");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(170, 30, 80, 20);

        jlblcustmrcode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblcustmrcode.setText("Vendor  Code");
        getContentPane().add(jlblcustmrcode);
        jlblcustmrcode.setBounds(60, 70, 140, 14);

        jtxtvendgrpcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtvendgrpcode.setText("vendorcode");
        jtxtvendgrpcode.setNextFocusableComponent(jtxtDescription);
        jtxtvendgrpcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtvendgrpcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtvendgrpcode);
        jtxtvendgrpcode.setBounds(250, 70, 80, 20);

        jtxtDescription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtDescription.setText("Description");
        getContentPane().add(jtxtDescription);
        jtxtDescription.setBounds(370, 70, 320, 20);

        jlblregdate.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblregdate.setText("Registration Date");
        getContentPane().add(jlblregdate);
        jlblregdate.setBounds(60, 100, 140, 14);

        kdateregdate.setFont(new java.awt.Font("Dialog", 0, 10));
        kdateregdate.setFontDate(new java.awt.Font("Dialog", 0, 10));
        getContentPane().add(kdateregdate);
        kdateregdate.setBounds(250, 100, 94, 19);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 30, 150, 20);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(420, 30, 150, 20);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(580, 30, 90, 20);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(680, 30, 130, 20);

        jchkActive.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jchkActive.setText("Active");
        getContentPane().add(jchkActive);
        jchkActive.setBounds(380, 100, 120, 23);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jpanelProcessing.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel13.setText("Account Set ");
        jpanelProcessing.add(jLabel13);
        jLabel13.setBounds(30, 40, 120, 14);

        jbtnBrowseAccountSet.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseAccountSet.setText("...");
        jbtnBrowseAccountSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseAccountSetActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseAccountSet);
        jbtnBrowseAccountSet.setBounds(360, 40, 30, 17);

        jtxtAccountSetDesc.setEditable(false);
        jtxtAccountSetDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtAccountSetDesc.setText("jtxtAccountSetDesc");
        jpanelProcessing.add(jtxtAccountSetDesc);
        jtxtAccountSetDesc.setBounds(400, 40, 360, 20);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel16.setText("Term Code");
        jpanelProcessing.add(jLabel16);
        jLabel16.setBounds(30, 70, 110, 14);

        jbtnBrowseTermCode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseTermCode.setText("...");
        jbtnBrowseTermCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseTermCodeActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseTermCode);
        jbtnBrowseTermCode.setBounds(360, 70, 30, 17);

        jtxtTermDesc.setEditable(false);
        jtxtTermDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtTermDesc.setText("jtxtTermCodeDesc");
        jpanelProcessing.add(jtxtTermDesc);
        jtxtTermDesc.setBounds(400, 70, 360, 20);

        jtxtaccsetcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtaccsetcode.setText("jtxtaccsetcode");
        jtxtaccsetcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaccsetcodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtaccsetcode);
        jtxtaccsetcode.setBounds(180, 40, 180, 20);

        jtxttermcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxttermcode.setText("jtxttermcode");
        jtxttermcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttermcodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxttermcode);
        jtxttermcode.setBounds(180, 70, 180, 20);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Distributed By"));
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel2.setLayout(null);

        jcmbDistBy.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbDistBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distribute Set", "Distribute Code", "GL Account" }));
        jcmbDistBy.setSelectedIndex(2);
        jPanel2.add(jcmbDistBy);
        jcmbDistBy.setBounds(10, 30, 160, 20);

        jtxtDistributedBy.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtDistributedBy.setText("jtxtDistributedBy");
        jtxtDistributedBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDistributedByKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtDistributedBy);
        jtxtDistributedBy.setBounds(180, 30, 190, 20);

        jbtnBrowseDist.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseDist.setText("...");
        jbtnBrowseDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseDistActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowseDist);
        jbtnBrowseDist.setBounds(380, 30, 30, 20);

        jtxtDistributedByDesc.setEditable(false);
        jtxtDistributedByDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtDistributedByDesc.setText("jtxtDistributedByDesc");
        jPanel2.add(jtxtDistributedByDesc);
        jtxtDistributedByDesc.setBounds(420, 30, 380, 20);

        jpanelProcessing.add(jPanel2);
        jPanel2.setBounds(30, 140, 810, 70);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel14.setText("Rate Type");
        jpanelProcessing.add(jLabel14);
        jLabel14.setBounds(30, 220, 130, 14);

        jtxtratetype.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtratetype.setText("ratetype");
        jtxtratetype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtratetypeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtratetype);
        jtxtratetype.setBounds(180, 220, 70, 20);

        jbtnBrowseRateType.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseRateType.setText("...");
        jbtnBrowseRateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseRateTypeActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseRateType);
        jbtnBrowseRateType.setBounds(260, 220, 30, 17);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel15.setText("Currency");
        jpanelProcessing.add(jLabel15);
        jLabel15.setBounds(30, 250, 100, 14);

        jtxtcurnccode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtcurnccode.setText("curnccode");
        jtxtcurnccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcurnccodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtcurnccode);
        jtxtcurnccode.setBounds(180, 250, 57, 20);

        jbtnBrowseCurr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseCurr.setText("...");
        jbtnBrowseCurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseCurrActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseCurr);
        jbtnBrowseCurr.setBounds(260, 250, 30, 20);

        jtxtRateTypeDesc.setEditable(false);
        jtxtRateTypeDesc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtRateTypeDesc.setText("jtxtRateTypeDesc");
        jpanelProcessing.add(jtxtRateTypeDesc);
        jtxtRateTypeDesc.setBounds(300, 220, 410, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setText("Bank Code");
        jpanelProcessing.add(jLabel1);
        jLabel1.setBounds(30, 100, 120, 14);

        jtxtbankcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtbankcode.setText("jtxtbankcode");
        jtxtbankcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtbankcodeKeyPressed(evt);
            }
        });
        jpanelProcessing.add(jtxtbankcode);
        jtxtbankcode.setBounds(180, 100, 180, 20);

        jbtnBrowseBank.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseBank.setText("...");
        jbtnBrowseBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseBankActionPerformed(evt);
            }
        });
        jpanelProcessing.add(jbtnBrowseBank);
        jbtnBrowseBank.setBounds(360, 100, 30, 20);

        jtxtBankName.setEditable(false);
        jtxtBankName.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtBankName.setText("jtxtBankName");
        jpanelProcessing.add(jtxtBankName);
        jtxtBankName.setBounds(400, 100, 360, 20);

        jTabbedPane1.addTab("Group", jpanelProcessing);

        jPanel3.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel17.setText("Tax Group");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(20, 20, 100, 14);

        jtxttaxcode.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxttaxcode.setText("jtxttaxcode");
        jPanel3.add(jtxttaxcode);
        jtxttaxcode.setBounds(160, 20, 58, 20);

        jbtnBrowseTax.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowseTax.setText("...");
        jbtnBrowseTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseTaxActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBrowseTax);
        jbtnBrowseTax.setBounds(230, 20, 30, 20);

        jtxttaxdescription.setEditable(false);
        jtxttaxdescription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxttaxdescription.setText("jtxttaxdescription");
        jPanel3.add(jtxttaxdescription);
        jtxttaxdescription.setBounds(270, 20, 380, 20);

        jTabbedPane1.addTab("Taxes", jPanel3);

        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setText("Month");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 10, 80, 14);

        jcmbMonth.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jPanel5.add(jcmbMonth);
        jcmbMonth.setBounds(100, 10, 50, 20);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel12.setText("Year");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(160, 10, 70, 14);

        jtxtyop.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtyop.setText("yop");
        jPanel5.add(jtxtyop);
        jtxtyop.setBounds(230, 10, 70, 20);

        jbtnFind.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnFind.setText("Find");
        jbtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFindActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnFind);
        jbtnFind.setBounds(310, 10, 53, 25);

        jtblStatistic.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtblStatistic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Invoices", null, null},
                {"Reciepts", null, null},
                {"Discounts", null, null},
                {"Credit Notes", null, null},
                {"Debit Notes", null, null},
                {"Adjustments", null, null},
                {"Write Offs", null, null},
                {"Interest Charges", null, null},
                {"Return Checks", null, null},
                {"Total Invoices Paid", null, null}
            },
            new String [] {
                "Transaction Type", "Amount", "Count"
            }
        ));
        jScrollPane4.setViewportView(jtblStatistic);
        jtblStatistic.getColumnModel().getColumn(0).setPreferredWidth(200);

        jPanel5.add(jScrollPane4);
        jScrollPane4.setBounds(20, 50, 830, 300);

        jTabbedPane1.addTab("Statistics", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(60, 130, 870, 390);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(330, 70, 30, 17);

        getAccessibleContext().setAccessibleName("A/P Vendor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveLast();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    try {
	      Ap_vendgrps brs = new Ap_vendgrps();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtvendgrpcode);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowseActionPerformed




private void jtxtvendgrpcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvendgrpcodeKeyPressed

}//GEN-LAST:event_jtxtvendgrpcodeKeyPressed

private void jbtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFindActionPerformed
    findStatistic();
}//GEN-LAST:event_jbtnFindActionPerformed

private void jbtnBrowseTermCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseTermCodeActionPerformed
    try {
        Op_paymentterms brs = new Op_paymentterms();
        FrmBrowse bd = new FrmBrowse(brs);
        bd.setFirstValue(jtxttermcode);
        bd.setSecondValue(jtxtTermDesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseTermCodeActionPerformed

private void jbtnBrowseAccountSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseAccountSetActionPerformed
    try {
        Ap_accsets brs = new Ap_accsets();
        FrmBrowse bd = new FrmBrowse( brs);
        bd.setFirstValue(jtxtaccsetcode);
        bd.setSecondValue(jtxtAccountSetDesc);
        bd.setModal(true);
        bd.setVisible(true);

    } catch (CodeException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_jbtnBrowseAccountSetActionPerformed

private void jbtnBrowseDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseDistActionPerformed
    NavigatorBrowseDataInt brs;
    FrmBrowse bd;

    try {
        if (jcmbDistBy.getSelectedIndex() == 0) {
            brs = new Ap_distseths(0);
            bd = new FrmBrowse(brs);
         }else if (jcmbDistBy.getSelectedIndex() == 0) {
            brs = new Ap_distcodes(0);
            bd = new FrmBrowse(brs);
        }else{
            brs = new Gl_accounts(0);
            bd = new FrmBrowseAccountActive(brs);
        }

      bd.setFirstValue(jtxtDistributedBy);
      bd.setSecondValue(jtxtDistributedByDesc);
      bd.setModal(true);
      bd.setVisible(true);

    }catch (Exception e) {    }
}//GEN-LAST:event_jbtnBrowseDistActionPerformed

private void jbtnBrowseRateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseRateTypeActionPerformed

       try {
	      Gl_ratetypes brs = new Gl_ratetypes();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtratetype);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowseRateTypeActionPerformed

private void jbtnBrowseCurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseCurrActionPerformed
       try {
	      Gl_currencys brs = new Gl_currencys(0);
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtcurnccode);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowseCurrActionPerformed

private void jbtnBrowseTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseTaxActionPerformed
       try {
	      Op_taxs brs = new Op_taxs(0);
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxttaxcode);
	      bd.setSecondValue(jtxttaxdescription);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseTaxActionPerformed

private void jbtnBrowseBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseBankActionPerformed
       try {
	      Cb_banks brs = new Cb_banks(0);
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtbankcode);
	      bd.setSecondValue(jtxtBankName);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowseBankActionPerformed

private void jtxtaccsetcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccsetcodeKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try {
            Ap_accset accset = new Ap_accset(jtxtaccsetcode.getText().replace("-", ""));
            jtxtaccsetcode.setText(accset.getaccsetcodefmt());
            jtxtAccountSetDesc.setText(accset.getdscription());


        }catch(Exception e) {

        }
        jtxttermcode.requestFocus();

    }
}//GEN-LAST:event_jtxtaccsetcodeKeyPressed

private void jtxttermcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttermcodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            Op_paymentterm payment = new Op_paymentterm(jtxttermcode.getText().replace("-", ""));
            jtxtaccsetcode.setText(payment.gettermcodefmt());
            jtxtTermDesc.setText(payment.getdscription());


        }catch (Exception e) {}

        jtxtbankcode.requestFocus();
    }
}//GEN-LAST:event_jtxttermcodeKeyPressed

private void jtxtbankcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbankcodeKeyPressed


    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            Cb_bank brs = new Cb_bank(jtxtbankcode.getText());
            jtxtBankName.setText(brs.getbankname());

            jtxtDistributedBy.requestFocus();
            
        }catch(Exception e) {}
        
    }
}//GEN-LAST:event_jtxtbankcodeKeyPressed

private void jtxtDistributedByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDistributedByKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        CodeObjectInt brs;

        try {

            if (jcmbDistBy.getSelectedIndex() == 0) {
                brs = new Ap_distseth(jtxtDistributedBy.getText());
                jtxtDistributedByDesc.setText(brs.toString(Ap_distseth.PROPERTY_DSCRIPTION));
            }else if (jcmbDistBy.getSelectedIndex() == 0) {
                brs = new Ap_distcode(jtxtDistributedBy.getText());
                jtxtDistributedByDesc.setText(brs.toString(Ap_distcode.PROPERTY_DSCRIPTION));
            }else{
                brs = new Gl_account(jtxtDistributedBy.getText().replace("-", ""));
                jtxtDistributedBy.setText(brs.toString(Gl_account.PROPERTY_ACCFMTTD));
                jtxtDistributedByDesc.setText(brs.toString(Gl_account.PROPERTY_ACCDESC));
            }

        }catch(Exception e) {}
        jtxtratetype.requestFocus();
    }
}//GEN-LAST:event_jtxtDistributedByKeyPressed

private void jtxtratetypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtratetypeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        try{
            Gl_ratetype brs = new Gl_ratetype(jtxtratetype.getText());
            jtxtRateTypeDesc.setText(brs.getdscription());

        }catch(Exception e) {}

        jtxtcurnccode.requestFocus();
    }


}//GEN-LAST:event_jtxtratetypeKeyPressed

private void jtxtcurnccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcurnccodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
     
        jtxttaxcode.requestFocus();
    }
}//GEN-LAST:event_jtxtcurnccodeKeyPressed




private void findStatistic() {
     setCursor(GlobalUtils.HOURGLASSCURSOR);

    try{

        Ap_vendgrpsts vrc = new Ap_vendgrpsts();
        vrc.searchData(jtxtyop.getText(), jcmbMonth.getSelectedItem()+"", jtxtvendgrpcode.getText());


        tmodel.setValueAt(vrc.getinvamt(), 0, 1);
        tmodel.setValueAt(vrc.getinvcnt(), 0, 2);

        tmodel.setValueAt(vrc.getpayamt(), 1, 1);
        tmodel.setValueAt(vrc.getpaycnt(), 1, 2);

        tmodel.setValueAt(vrc.getdiscamt(), 2, 1);
        tmodel.setValueAt(vrc.getdisccnt(), 2, 2);

        tmodel.setValueAt(vrc.getcnamt(), 3, 1);
        tmodel.setValueAt(vrc.getcncnt(), 3, 2);

        tmodel.setValueAt(vrc.getdnamt(), 4, 1);
        tmodel.setValueAt(vrc.getdncnt(), 4, 2);

        tmodel.setValueAt(vrc.getadjamt(), 5, 1);
        tmodel.setValueAt(vrc.getadjcnt(), 5, 2);

        tmodel.setValueAt(vrc.getwroffamt(), 6, 1);
        tmodel.setValueAt(vrc.getwroffcnt(), 6, 2);

        tmodel.setValueAt(vrc.getinttamt(), 7, 1);
        tmodel.setValueAt(vrc.getinttcnt(), 7, 2);

        tmodel.setValueAt(vrc.getrtrchckamt(), 8, 1);
        tmodel.setValueAt(vrc.getrtrchckcnt(), 8, 2);

        tmodel.setValueAt(vrc.getinvpaidamt(), 9, 1);
        tmodel.setValueAt(vrc.getinvpaidcnt(), 9, 2);


    }catch(Exception e) {}
    setCursor(GlobalUtils.NORMALCURSOR);

}


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    if (!onload) {
        try {
            moveLast();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
        onload = true;
    }

    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmAp_vendorgrp().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup btnGrpDistCode;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowseAccountSet;
    private javax.swing.JButton jbtnBrowseBank;
    private javax.swing.JButton jbtnBrowseCurr;
    private javax.swing.JButton jbtnBrowseDist;
    private javax.swing.JButton jbtnBrowseRateType;
    private javax.swing.JButton jbtnBrowseTax;
    private javax.swing.JButton jbtnBrowseTermCode;
    private javax.swing.JButton jbtnFind;
    private javax.swing.JCheckBox jchkActive;
    private javax.swing.JComboBox jcmbDistBy;
    private javax.swing.JComboBox jcmbMonth;
    private javax.swing.JLabel jlblcustmrcode;
    private javax.swing.JLabel jlblregdate;
    private javax.swing.JPanel jpanelProcessing;
    private javax.swing.JTable jtblStatistic;
    private javax.swing.JTextField jtxtAccountSetDesc;
    private javax.swing.JTextField jtxtBankName;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtDistributedBy;
    private javax.swing.JTextField jtxtDistributedByDesc;
    private javax.swing.JTextField jtxtRateTypeDesc;
    private javax.swing.JTextField jtxtTermDesc;
    private javax.swing.JTextField jtxtaccsetcode;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtbankcode;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtcurnccode;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtratetype;
    private javax.swing.JTextField jtxttaxcode;
    private javax.swing.JTextField jtxttaxdescription;
    private javax.swing.JTextField jtxttermcode;
    private javax.swing.JTextField jtxtvendgrpcode;
    private javax.swing.JTextField jtxtyop;
    private org.kazao.calendar.KazaoCalendarDate kdateregdate;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Ap_vendgrp(this.jtxtvendgrpcode.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Ap_vendgrp();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    private void validasi() throws CodeException {

         if (!jtxtaccsetcode.getText().equals("")) {
             Ap_accset arc = new Ap_accset(jtxtaccsetcode.getText());
             if (arc.getID() == Ap_accset.NULLID) {
                throw new CodeException("Account Set  " + jtxtaccsetcode.getText() + " Tidak Diketemukan");
             }
         }


         if (!jtxttermcode.getText().equals("")){
            Op_paymentterm opp = new Op_paymentterm(jtxttermcode.getText());
            if (opp.getID() == Op_paymentterm.NULLID) {
                throw new CodeException("Term Code " + jtxttermcode.getText() + " Tidak Diketemukan ");                
            }
         }


    }



    public void saveData() throws CodeException {
        validasi();


        istatus = 0;
       
        setData();
        obj.save();
        jtxtid.setText(obj.getID()+"");



        //jtbAddress.setSelectedIndex(0);
        
        //showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Ap_vendgrp.PROPERTY_ID));
             jtxtvendgrpcode.setText(obj.toString(Ap_vendgrp.PROPERTY_GRPCODE));
             jtxtDescription.setText(obj.toString(Ap_vendgrp.PROPERTY_DSCRIPTION));

             jtxtentrydate.setText(obj.toString(Ap_vendgrp.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Ap_vendgrp.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Ap_vendgrp.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Ap_vendgrp.PROPERTY_CMPNYID));


             jtxtaccsetcode.setText(obj.getaccsetcode());
             jtxtAccountSetDesc.setText(obj.getAP_accsetDesc());

             jchkActive.setSelected(obj.getactive() == 1);
             
             jtxttermcode.setText(obj.gettermcode());
             jtxtTermDesc.setText(obj.getTermDescription());

             jtxtbankcode.setText(obj.getbankcode());
             jtxtBankName.setText(obj.getCB_BankDesc());

             jcmbDistBy.setSelectedIndex( (int) obj.getdistby());

             if (obj.getdistby() == 0) {
                 jtxtDistributedBy.setText(obj.getdistsetcode());
                 jtxtDistributedByDesc.setText(obj.getAp_distsethDesc());
             }else if (obj.getdistby() == 1) {
                 jtxtDistributedBy.setText(obj.getdistcode());
                 jtxtDistributedByDesc.setText(obj.getAp_distDesc());
             }else{
                 jtxtDistributedBy.setText(obj.getglacccodefmt());
                 jtxtDistributedByDesc.setText(obj.getGL_AccDesc());
             }


             jtxtcurnccode.setText(obj.getcurnccode());
             jtxtratetype.setText(obj.getratetype());
             jtxtRateTypeDesc.setText(obj.getGl_RateTypeDesc());


             jtxttaxcode.setText(obj.gettaxcode());
             jtxttaxdescription.setText(obj.getOP_TaxDesc());
             
  


        setCursor(GlobalUtils.NORMALCURSOR);
    }


    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Ap_vendgrp.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Ap_vendgrp.PROPERTY_GRPCODE, jtxtvendgrpcode.getText()) ;
          obj.fromString(Ap_vendgrp.PROPERTY_DSCRIPTION, jtxtDescription.getText()) ;
          obj.fromString(Ap_vendgrp.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Ap_vendgrp.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Ap_vendgrp.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Ap_vendgrp.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

          obj.setactive(jchkActive.isSelected()?1:0);

          obj.setaccsetcode(jtxtaccsetcode.getText());
          obj.settermcode(jtxttermcode.getText());
          obj.setbankcode(jtxtbankcode.getText());

          obj.setdistby(jcmbDistBy.getSelectedIndex());
          if (jcmbDistBy.getSelectedIndex() == 0) {
              obj.setdistsetcode(jtxtDistributedBy.getText());
          }else if (jcmbDistBy.getSelectedIndex() == 1) {
              obj.setdistcode(jtxtDistributedBy.getText());
          }else {
              obj.setglacccode(jtxtDistributedBy.getText());
          }

          obj.setratetype(jtxtratetype.getText());
          obj.setcurnccode(jtxtcurnccode.getText());

          obj.settaxcode(jtxttaxcode.getText());
          
  
          
    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
