/*
 * FrmLogin.java
 *
 * Created on August 5, 2009, 12:38 PM
 * 
 * FrmLogin is used for user to log in to application
 * 
 * Please see :
 * - FrmMasteruser
 * - FrmMastergroup
 * - FrmMastermodule
 * 
 */

package common.component;

import accapp.objectclasses.gl.Gl_fiscalh;
import common.jdbc.DbBean;
import common.jdbc.DbBeanCommon;
import common.objectclasses.Mastercompany;
import common.objectclasses.Mastercompanys;
import common.objectclasses.Mastergroupdetails;
import common.objectclasses.Masteruser;
import common.utils.GlobalUtils;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author  wgata
 */
public class FrmLogin extends javax.swing.JDialog {

    FrmMainFrame fm;
    /** Creates new form frmLogin */
    public FrmLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FrmLogin() {
        initComponents();

        try {
            Mastercompanys mastercompanys  = new Mastercompanys(0);

            for(Object o : mastercompanys.list()) {
                   Mastercompany m = (Mastercompany) o;
                   jcmbCompany.addItem(m.getCompany());

                   if (m.getSelected()==1) {
                       jcmbCompany.setSelectedIndex(jcmbCompany.getItemCount()-1);
                   }
            }
        }catch(Exception e) {
        
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUser = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jtbnLogin = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jbtnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcmbCompany = new javax.swing.JComboBox();
        kbatchdate = new org.kazao.calendar.KazaoCalendarDate();
        jlblbatchdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setModal(true);
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jlblUser.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblUser.setText("Username");
        getContentPane().add(jlblUser);
        jlblUser.setBounds(20, 20, 90, 14);

        jlblPassword.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblPassword.setText("Password");
        getContentPane().add(jlblPassword);
        jlblPassword.setBounds(20, 50, 90, 20);

        jtxtUser.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtUser.setToolTipText("Username");
        jtxtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUserKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtUser);
        jtxtUser.setBounds(110, 20, 100, 20);

        jtbnLogin.setFont(new java.awt.Font("Dialog", 0, 10));
        jtbnLogin.setText("Login");
        jtbnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnLogin);
        jtbnLogin.setBounds(50, 140, 88, 23);

        jtxtPassword.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtPassword);
        jtxtPassword.setBounds(110, 50, 100, 20);

        jbtnExit.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit);
        jbtnExit.setBounds(150, 140, 90, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setText("Company");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 80, 14);

        jcmbCompany.setFont(new java.awt.Font("Dialog", 0, 10));
        getContentPane().add(jcmbCompany);
        jcmbCompany.setBounds(110, 80, 120, 22);

        kbatchdate.setFont(new java.awt.Font("Dialog", 0, 10));
        kbatchdate.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kbatchdate.setOpaque(false);
        getContentPane().add(kbatchdate);
        kbatchdate.setBounds(110, 110, 100, 20);

        jlblbatchdate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbatchdate.setText("Session Date");
        getContentPane().add(jlblbatchdate);
        jlblbatchdate.setBounds(20, 110, 140, 14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-303)/2, (screenSize.height-184)/2, 303, 184);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed

    System.exit(0);
}//GEN-LAST:event_jbtnExitActionPerformed


private void login() {
    setCursor(GlobalUtils.HOURGLASSCURSOR);

    try {
        Masteruser mu = new Masteruser(Masteruser.PROPERTY_USER, jtxtUser.getText());

        if (mu.getID() != Masteruser.NULLID) {
            if (mu.getPassword().equals(jtxtPassword.getText())) {
                
                
                GlobalUtils.setUserId(mu.getUser());
                GlobalUtils.setAuditUser(mu.getNama());
                GlobalUtils.sessiondate=kbatchdate.getDate();

                setVisible(false); 

                Mastercompany mcps = new Mastercompany(jcmbCompany.getSelectedItem() + "");

                GlobalUtils.mastergroupdetails = new Mastergroupdetails();
                GlobalUtils.mastergroupdetails.loadData(mu.getUser(), jcmbCompany.getSelectedItem() + "") ;
                
                jtxtUser.setText("");
                jtxtPassword.setText("");

                GlobalUtils.company = mcps.getDatabase();
                GlobalUtils.serverip=DbBeanCommon.serverip;
                DbBean.InitConnection(DbBeanCommon.serverip, GlobalUtils.company,"");


                Gl_fiscalh glf=new Gl_fiscalh(Gl_fiscalh.PROPERTY_YOP,GlobalUtils.getYear(GlobalUtils.sessiondate)+"");
                GlobalUtils.periodelocked=glf.getIsperiodelocked(GlobalUtils.getMonth(GlobalUtils.sessiondate));

                GlobalUtils.setNamaPT(mcps.getDescription());
                DbBeanCommon  dbc = DbBeanCommon.connect();
                try {
                        dbc.updateSQL("Update mastercompany set selected = 0;");
                        dbc.updateSQL("Update mastercompany set selected = 1 where company ='" + jcmbCompany.getSelectedItem() + "' ");
                                            
                }catch (Exception e) {
                    e.printStackTrace();
                }finally{
                    dbc.close();
                }


                
            }else {
                JOptionPane.showMessageDialog(null, "Password Incorrect ", "login", JOptionPane.ERROR_MESSAGE);
                jtxtPassword.requestFocus();
                jtxtPassword.setSelectionStart(0);
                jtxtPassword.setSelectionEnd(jtxtPassword.getText().length());

            }
            
        }else {
            JOptionPane.showMessageDialog(null, "User Is Not Found ", "login", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Cannot connect to database");
        System.exit(1);
    }
    setCursor(GlobalUtils.NORMALCURSOR);

}
private void jtbnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnLoginActionPerformed

    login();
    
}//GEN-LAST:event_jtbnLoginActionPerformed

private void jtxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPasswordKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        login();
    }
}//GEN-LAST:event_jtxtPasswordKeyPressed

private void jtxtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtPassword.requestFocus();
    }
}//GEN-LAST:event_jtxtUserKeyPressed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    // TODO add your handling code here:
    jtxtUser.requestFocusInWindow();
    jtxtUser.selectAll();
}//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogin dialog = new FrmLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JComboBox jcmbCompany;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JLabel jlblbatchdate;
    private javax.swing.JButton jtbnLogin;
    private javax.swing.JPasswordField jtxtPassword;
    public javax.swing.JTextField jtxtUser;
    private org.kazao.calendar.KazaoCalendarDate kbatchdate;
    // End of variables declaration//GEN-END:variables

}
