/*
 * FrmResetPassword.java
 *
 * Created on September 3, 2009, 11:24 AM
 * 
 * This Form is Used For Changing Password
 * 
 */

package common.component;

/**
 *
 * @author  wgata
 */

import common.objectclasses.Masteruser;
import javax.swing.JOptionPane;

public class FrmResetPassword extends javax.swing.JDialog {

    Masteruser mu;
    
    /** Creates new form FrmResetPassword */
    public FrmResetPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FrmResetPassword(Masteruser mu) {
        initComponents();
        
        this.mu = mu;
        
        try {
            jtxtUser.setText(mu.getUser());

        }catch (Exception e) {}
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUser = new javax.swing.JLabel();
        jlblOldPassword = new javax.swing.JLabel();
        jlblNewPassword = new javax.swing.JLabel();
        jlblConfirmNewPassword = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtxtUser = new javax.swing.JTextField();
        jpassNewConfirmation = new javax.swing.JPasswordField();
        jpassNew = new javax.swing.JPasswordField();
        jpassOld = new javax.swing.JPasswordField();
        jbtnGanti = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reset Password");
        setResizable(false);
        getContentPane().setLayout(null);

        jlblUser.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblUser.setText("User");
        getContentPane().add(jlblUser);
        jlblUser.setBounds(20, 40, 160, 14);

        jlblOldPassword.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblOldPassword.setText("Password Lama");
        getContentPane().add(jlblOldPassword);
        jlblOldPassword.setBounds(20, 60, 170, 14);

        jlblNewPassword.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblNewPassword.setText("Password Baru ");
        getContentPane().add(jlblNewPassword);
        jlblNewPassword.setBounds(20, 100, 180, 14);

        jlblConfirmNewPassword.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblConfirmNewPassword.setText("Konfirmasi Password Baru ");
        getContentPane().add(jlblConfirmNewPassword);
        jlblConfirmNewPassword.setBounds(20, 120, 180, 14);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 150, 310, 2);

        jtxtUser.setEditable(false);
        jtxtUser.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtUser.setText("jtxtUser");
        jtxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtUser);
        jtxtUser.setBounds(210, 40, 120, 20);

        jpassNewConfirmation.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(jpassNewConfirmation);
        jpassNewConfirmation.setBounds(210, 120, 120, 20);

        jpassNew.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(jpassNew);
        jpassNew.setBounds(210, 100, 120, 20);

        jpassOld.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        getContentPane().add(jpassOld);
        jpassOld.setBounds(210, 60, 120, 20);

        jbtnGanti.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnGanti.setText("Ganti");
        jbtnGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGantiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGanti);
        jbtnGanti.setBounds(20, 160, 59, 23);

        jbtnClose.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClose);
        jbtnClose.setBounds(240, 160, 88, 23);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ganti/Reset Password");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 10, 170, 14);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 90, 310, 2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-352)/2, (screenSize.height-230)/2, 352, 230);
    }// </editor-fold>//GEN-END:initComponents

private void jtxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserActionPerformed

}//GEN-LAST:event_jtxtUserActionPerformed

private void jbtnGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGantiActionPerformed
    try {
        if (!jpassOld.getText().equals(mu.getPassword())) {
            JOptionPane.showMessageDialog(null, "New Password is not the same ", "Problem", JOptionPane.ERROR_MESSAGE);
        }else{
            
            if (!jpassNew.getText().equals(jpassNewConfirmation.getText())) {
                JOptionPane.showMessageDialog(null, "New Password is not the same as confirm password", "Problem", JOptionPane.ERROR_MESSAGE);                
            }else {
                if (jpassNew.getText().length() < 6) {
                    JOptionPane.showMessageDialog(null, "New password must 6 Digit or More ", "Problem", JOptionPane.ERROR_MESSAGE);                                    
                }else{
                    mu.setPassword(jpassNew.getText());
                    mu.save();
                    
                    JOptionPane.showMessageDialog(null, "Password is already changed ", "Pass", JOptionPane.ERROR_MESSAGE);                                                        
                    this.dispose();
                }
            }
        }
        
        
    }catch (Exception e) {
        
    }
}//GEN-LAST:event_jbtnGantiActionPerformed

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
    this.dispose();
}//GEN-LAST:event_jbtnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmResetPassword dialog = new FrmResetPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnGanti;
    private javax.swing.JLabel jlblConfirmNewPassword;
    private javax.swing.JLabel jlblNewPassword;
    private javax.swing.JLabel jlblOldPassword;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JPasswordField jpassNew;
    private javax.swing.JPasswordField jpassNewConfirmation;
    private javax.swing.JPasswordField jpassOld;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables

}
