/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import accapp.component.cashbook.FrmCb_bank;
 * 
 * .......
 * 
 * 
 * FrmCb_bank frmCb_bank;
 * 
 * .......
 * 
 try {
        if (frmCb_bank == null) {
            frmmCb_bank = new FrmCb_bank(this);
        }
        
        showForm(frmCb_bank);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component.cashbook;

import accapp.component.browse.FrmBrowseGl_SourceGr;
import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.cashbook.Cb_bank;
import accapp.objectclasses.cashbook.Cb_banks;
import accapp.objectclasses.cashbook.Cb_option;
import accapp.objectclasses.cashbook.Cb_source;
import accapp.objectclasses.cashbook.Cb_sources;
import accapp.objectclasses.gl.Gl_account;
import accapp.objectclasses.gl.Gl_accounts;
import accapp.objectclasses.gl.Gl_currency;
import accapp.objectclasses.gl.Gl_currencys;
import accapp.objectclasses.gl.Gl_ratetype;
import accapp.objectclasses.gl.Gl_ratetypes;
import accapp.objectclasses.gl.Gl_sourcelgrs;

/**
 *
 * @author  Generator
 */

public class FrmCb_bank extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmCb_bank";
    
    FrmMainFrame mf ;
    
    
    public Cb_bank obj = new Cb_bank();
    Cb_option cbopt;
    
   
    /** Creates new form Area */
    public FrmCb_bank() throws CodeException {
        initComponents();
    }
    
    public FrmCb_bank(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        cbopt=new Cb_option(Cb_option.PROPERTY_CMPNYID,GlobalUtils.company);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtid = new javax.swing.JTextField();
        jlblbankcode = new javax.swing.JLabel();
        jtxtbankcode = new javax.swing.JTextField();
        jtxtbankname = new javax.swing.JTextField();
        jtxtentrydate = new javax.swing.JTextField();
        jtxtauditdate = new javax.swing.JTextField();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtcmpnyid = new javax.swing.JTextField();
        jtabBank = new javax.swing.JTabbedPane();
        jpAddress = new javax.swing.JPanel();
        jlbladdress1 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jlbladdress2 = new javax.swing.JLabel();
        jtxtaddress2 = new javax.swing.JTextField();
        jlblcity = new javax.swing.JLabel();
        jtxtcity = new javax.swing.JTextField();
        jlblstate = new javax.swing.JLabel();
        jtxtstate = new javax.swing.JTextField();
        jlblpostalcode = new javax.swing.JLabel();
        jtxtpostalcode = new javax.swing.JTextField();
        jlblphone1 = new javax.swing.JLabel();
        jtxtphone1 = new javax.swing.JTextField();
        jlblphone2 = new javax.swing.JLabel();
        jtxtphone2 = new javax.swing.JTextField();
        jlblfaxno = new javax.swing.JLabel();
        jtxtfaxno = new javax.swing.JTextField();
        jlblcontact = new javax.swing.JLabel();
        jtxtcontact = new javax.swing.JTextField();
        jlblcomments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtcomments = new javax.swing.JTextArea();
        jpBank = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblbankaccno = new javax.swing.JLabel();
        jtxtbankaccno = new javax.swing.JTextField();
        jtxtsrceledgr = new javax.swing.JTextField();
        jlblsrceledgr = new javax.swing.JLabel();
        jlblrvslsrcecode = new javax.swing.JLabel();
        jtxtrvslsrcecode = new javax.swing.JTextField();
        jtxtvoidsrcecode = new javax.swing.JTextField();
        jlblcurnccode = new javax.swing.JLabel();
        jtxtcurnccode = new javax.swing.JTextField();
        jlblrvslsrcecode1 = new javax.swing.JLabel();
        jlblratetypecode = new javax.swing.JLabel();
        jtxtratetypecode = new javax.swing.JTextField();
        jbtnBrowseCurrnCode = new javax.swing.JButton();
        jtxtcurncdesc = new javax.swing.JTextField();
        jbtnbrowservslsrcecode = new javax.swing.JButton();
        jbtnBrowsevoidsrcecode = new javax.swing.JButton();
        jtxtrvslsrcedesc = new javax.swing.JTextField();
        jtxtvoidsrcedesc = new javax.swing.JTextField();
        jbtnBrowseratetypecode = new javax.swing.JButton();
        jbtnBrowsesrceledgr = new javax.swing.JButton();
        jpOption = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jchkDplctcheck = new javax.swing.JCheckBox();
        jpAccount = new javax.swing.JPanel();
        jlblbankacccode = new javax.swing.JLabel();
        jtxtbankacccode = new javax.swing.JTextField();
        jlblvoidacccode = new javax.swing.JLabel();
        jtxtvoidacccode = new javax.swing.JTextField();
        jlbltrnfclracccode = new javax.swing.JLabel();
        jtxttrnfclracccode = new javax.swing.JTextField();
        jlblcashclracccode = new javax.swing.JLabel();
        jtxtcashclracccode = new javax.swing.JTextField();
        jlblarclracccode = new javax.swing.JLabel();
        jtxtarclracccode = new javax.swing.JTextField();
        jlblapclraccode = new javax.swing.JLabel();
        jtxtapclraccode = new javax.swing.JTextField();
        jlbljcclracccode = new javax.swing.JLabel();
        jtxtjcclracccode = new javax.swing.JTextField();
        jlblprclracccode = new javax.swing.JLabel();
        jtxtprclracccode = new javax.swing.JTextField();
        jlblapbankacccode = new javax.swing.JLabel();
        jtxtapbankacccode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jbtnBrowseApbankacccode = new javax.swing.JButton();
        jbtnBrowseBankAcc = new javax.swing.JButton();
        jbtnBrowseVoidAcccode = new javax.swing.JButton();
        jbtnBrowseTrnfclacccode = new javax.swing.JButton();
        jbtnBrowseCashclracccode = new javax.swing.JButton();
        jbtnBrowseArclracccode = new javax.swing.JButton();
        jbtnBrowseApclraacccode = new javax.swing.JButton();
        jbtnJcclracccode = new javax.swing.JButton();
        jbtnBrowsePrclracccode = new javax.swing.JButton();
        jtxtVoidaccdesc = new javax.swing.JTextField();
        jtxtTrnfaccdesc = new javax.swing.JTextField();
        jtxtCashclraccdesc = new javax.swing.JTextField();
        jtxtArclraccdesc = new javax.swing.JTextField();
        jtxtapclraccdesc = new javax.swing.JTextField();
        jtxtJcclraccdesc = new javax.swing.JTextField();
        jtxtPrclraccdesc = new javax.swing.JTextField();
        jtxtApbankaccdesc = new javax.swing.JTextField();
        jtxtBankacccodedesc = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Bank");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Cb_bank");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jtxtid.setEditable(false);
        jtxtid.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(170, 30, 80, 20);

        jlblbankcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbankcode.setText("bank code");
        getContentPane().add(jlblbankcode);
        jlblbankcode.setBounds(60, 70, 80, 13);

        jtxtbankcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbankcode.setText("bankcode");
        jtxtbankcode.setNextFocusableComponent(jtxtbankname);
        jtxtbankcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtbankcodeKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtbankcode);
        jtxtbankcode.setBounds(160, 70, 110, 20);

        jtxtbankname.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbankname.setText("bankname");
        jtxtbankname.setNextFocusableComponent(jtxtaddress1);
        jtxtbankname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtbanknameKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtbankname);
        jtxtbankname.setBounds(320, 70, 390, 20);

        jtxtentrydate.setEditable(false);
        jtxtentrydate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 30, 150, 20);

        jtxtauditdate.setEditable(false);
        jtxtauditdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(420, 30, 150, 20);

        jtxtaudituser.setEditable(false);
        jtxtaudituser.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(580, 30, 90, 20);

        jtxtcmpnyid.setEditable(false);
        jtxtcmpnyid.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(680, 30, 130, 20);

        jtabBank.setFont(new java.awt.Font("Dialog", 0, 10));

        jpAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpAddress.setLayout(null);

        jlbladdress1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress1.setText("Address1");
        jpAddress.add(jlbladdress1);
        jlbladdress1.setBounds(20, 30, 90, 13);

        jtxtaddress1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress1.setText("address1");
        jtxtaddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaddress1KeyPressed(evt);
            }
        });
        jpAddress.add(jtxtaddress1);
        jtxtaddress1.setBounds(110, 30, 200, 23);

        jlbladdress2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress2.setText("Address2");
        jpAddress.add(jlbladdress2);
        jlbladdress2.setBounds(20, 60, 90, 13);

        jtxtaddress2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress2.setText("address2");
        jtxtaddress2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtaddress2KeyPressed(evt);
            }
        });
        jpAddress.add(jtxtaddress2);
        jtxtaddress2.setBounds(110, 60, 200, 23);

        jlblcity.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcity.setText("City");
        jpAddress.add(jlblcity);
        jlblcity.setBounds(20, 90, 70, 13);

        jtxtcity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcity.setText("city");
        jtxtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcityKeyPressed(evt);
            }
        });
        jpAddress.add(jtxtcity);
        jtxtcity.setBounds(110, 90, 200, 23);

        jlblstate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblstate.setText("State");
        jpAddress.add(jlblstate);
        jlblstate.setBounds(20, 120, 60, 13);

        jtxtstate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtstate.setText("state");
        jtxtstate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtstateKeyPressed(evt);
            }
        });
        jpAddress.add(jtxtstate);
        jtxtstate.setBounds(110, 120, 200, 23);

        jlblpostalcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpostalcode.setText("Postal code");
        jpAddress.add(jlblpostalcode);
        jlblpostalcode.setBounds(20, 160, 90, 13);

        jtxtpostalcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpostalcode.setText("postalcode");
        jtxtpostalcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpostalcodeKeyPressed(evt);
            }
        });
        jpAddress.add(jtxtpostalcode);
        jtxtpostalcode.setBounds(110, 160, 100, 23);

        jlblphone1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone1.setText("Phone 1");
        jpAddress.add(jlblphone1);
        jlblphone1.setBounds(240, 160, 70, 13);

        jtxtphone1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone1.setText("phone1");
        jtxtphone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtphone1KeyPressed(evt);
            }
        });
        jpAddress.add(jtxtphone1);
        jtxtphone1.setBounds(330, 160, 150, 23);

        jlblphone2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone2.setText("Phone2");
        jpAddress.add(jlblphone2);
        jlblphone2.setBounds(240, 190, 80, 13);

        jtxtphone2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone2.setText("phone2");
        jtxtphone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtphone2KeyPressed(evt);
            }
        });
        jpAddress.add(jtxtphone2);
        jtxtphone2.setBounds(330, 190, 150, 23);

        jlblfaxno.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaxno.setText("Fax no");
        jpAddress.add(jlblfaxno);
        jlblfaxno.setBounds(20, 190, 80, 13);

        jtxtfaxno.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtfaxno.setText("faxno");
        jtxtfaxno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfaxnoKeyPressed(evt);
            }
        });
        jpAddress.add(jtxtfaxno);
        jtxtfaxno.setBounds(110, 190, 100, 23);

        jlblcontact.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcontact.setText("Contact");
        jpAddress.add(jlblcontact);
        jlblcontact.setBounds(20, 220, 80, 13);

        jtxtcontact.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcontact.setText("contact");
        jtxtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcontactKeyPressed(evt);
            }
        });
        jpAddress.add(jtxtcontact);
        jtxtcontact.setBounds(110, 220, 100, 23);

        jlblcomments.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcomments.setText("Comments");
        jpAddress.add(jlblcomments);
        jlblcomments.setBounds(20, 260, 80, 13);

        jtxtcomments.setColumns(20);
        jtxtcomments.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcomments.setRows(5);
        jtxtcomments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcommentsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtcomments);

        jpAddress.add(jScrollPane1);
        jScrollPane1.setBounds(110, 260, 490, 130);

        jtabBank.addTab("Address", jpAddress);

        jpBank.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bank Information"));
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel2.setLayout(null);

        jlblbankaccno.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbankaccno.setText("Bank Acc No");
        jPanel2.add(jlblbankaccno);
        jlblbankaccno.setBounds(20, 30, 100, 20);

        jtxtbankaccno.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbankaccno.setText("bankaccno");
        jtxtbankaccno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtbankaccnoKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtbankaccno);
        jtxtbankaccno.setBounds(190, 30, 140, 23);

        jtxtsrceledgr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsrceledgr.setText("CB");
        jtxtsrceledgr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtsrceledgrKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtsrceledgr);
        jtxtsrceledgr.setBounds(490, 30, 50, 23);

        jlblsrceledgr.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsrceledgr.setText("Source Ledger");
        jPanel2.add(jlblsrceledgr);
        jlblsrceledgr.setBounds(370, 30, 120, 20);

        jlblrvslsrcecode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblrvslsrcecode.setText("Void Check Source");
        jPanel2.add(jlblrvslsrcecode);
        jlblrvslsrcecode.setBounds(20, 90, 150, 13);

        jtxtrvslsrcecode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtrvslsrcecode.setText("rvslsrcecode");
        jtxtrvslsrcecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtrvslsrcecodeKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtrvslsrcecode);
        jtxtrvslsrcecode.setBounds(190, 60, 80, 23);

        jtxtvoidsrcecode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtvoidsrcecode.setText("voidsrcecode");
        jtxtvoidsrcecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtvoidsrcecodeKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtvoidsrcecode);
        jtxtvoidsrcecode.setBounds(190, 90, 80, 23);

        jlblcurnccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcurnccode.setForeground(new java.awt.Color(251, 8, 8));
        jlblcurnccode.setText("Currency Code*");
        jPanel2.add(jlblcurnccode);
        jlblcurnccode.setBounds(20, 120, 140, 13);

        jtxtcurnccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcurnccode.setText("curnccode");
        jtxtcurnccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcurnccodeKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtcurnccode);
        jtxtcurnccode.setBounds(190, 120, 80, 23);

        jlblrvslsrcecode1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblrvslsrcecode1.setText("Reversal Source Code");
        jPanel2.add(jlblrvslsrcecode1);
        jlblrvslsrcecode1.setBounds(20, 60, 160, 13);

        jlblratetypecode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblratetypecode.setForeground(new java.awt.Color(251, 8, 8));
        jlblratetypecode.setText("Rate Type Code*");
        jPanel2.add(jlblratetypecode);
        jlblratetypecode.setBounds(20, 150, 140, 13);

        jtxtratetypecode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtratetypecode.setText("ratetypecode");
        jtxtratetypecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtratetypecodeKeyPressed(evt);
            }
        });
        jPanel2.add(jtxtratetypecode);
        jtxtratetypecode.setBounds(190, 150, 80, 23);

        jbtnBrowseCurrnCode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseCurrnCode.setText("...");
        jbtnBrowseCurrnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseCurrnCodeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowseCurrnCode);
        jbtnBrowseCurrnCode.setBounds(280, 120, 30, 17);

        jtxtcurncdesc.setEditable(false);
        jtxtcurncdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcurncdesc.setText("jtxtcurncdesc");
        jPanel2.add(jtxtcurncdesc);
        jtxtcurncdesc.setBounds(330, 120, 260, 23);

        jbtnbrowservslsrcecode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnbrowservslsrcecode.setText("...");
        jbtnbrowservslsrcecode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnbrowservslsrcecodeMouseClicked(evt);
            }
        });
        jbtnbrowservslsrcecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbrowservslsrcecodeActionPerformed(evt);
            }
        });
        jbtnbrowservslsrcecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnbrowservslsrcecodeKeyPressed(evt);
            }
        });
        jPanel2.add(jbtnbrowservslsrcecode);
        jbtnbrowservslsrcecode.setBounds(280, 60, 30, 20);

        jbtnBrowsevoidsrcecode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowsevoidsrcecode.setText("...");
        jbtnBrowsevoidsrcecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowsevoidsrcecodeActionPerformed(evt);
            }
        });
        jbtnBrowsevoidsrcecode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnBrowsevoidsrcecodeKeyPressed(evt);
            }
        });
        jPanel2.add(jbtnBrowsevoidsrcecode);
        jbtnBrowsevoidsrcecode.setBounds(280, 90, 30, 20);

        jtxtrvslsrcedesc.setEditable(false);
        jtxtrvslsrcedesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtrvslsrcedesc.setText("jtxtrvslsrcedesc");
        jPanel2.add(jtxtrvslsrcedesc);
        jtxtrvslsrcedesc.setBounds(330, 60, 260, 23);

        jtxtvoidsrcedesc.setEditable(false);
        jtxtvoidsrcedesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtvoidsrcedesc.setText("jtxtvoidsrcedesc");
        jPanel2.add(jtxtvoidsrcedesc);
        jtxtvoidsrcedesc.setBounds(330, 90, 260, 23);

        jbtnBrowseratetypecode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseratetypecode.setText("...");
        jbtnBrowseratetypecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseratetypecodeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowseratetypecode);
        jbtnBrowseratetypecode.setBounds(280, 150, 30, 20);

        jbtnBrowsesrceledgr.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowsesrceledgr.setText("...");
        jbtnBrowsesrceledgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowsesrceledgrActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowsesrceledgr);
        jbtnBrowsesrceledgr.setBounds(550, 30, 20, 20);

        jpBank.add(jPanel2);
        jPanel2.setBounds(10, 20, 720, 210);

        jtabBank.addTab("Bank", jpBank);

        jpOption.setLayout(null);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        jchkDplctcheck.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkDplctcheck.setText("Duplicate Cheque/Reference Numbers");
        jchkDplctcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkDplctcheckActionPerformed(evt);
            }
        });
        jchkDplctcheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchkDplctcheckKeyPressed(evt);
            }
        });
        jPanel5.add(jchkDplctcheck);
        jchkDplctcheck.setBounds(20, 40, 330, 24);

        jpOption.add(jPanel5);
        jPanel5.setBounds(10, 10, 720, 370);

        jtabBank.addTab("Option", jpOption);

        jpAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("GL Account"));
        jpAccount.setFont(new java.awt.Font("Dialog", 0, 10));
        jpAccount.setLayout(null);

        jlblbankacccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbankacccode.setForeground(new java.awt.Color(251, 12, 12));
        jlblbankacccode.setText("Bank*");
        jpAccount.add(jlblbankacccode);
        jlblbankacccode.setBounds(20, 40, 140, 13);

        jtxtbankacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbankacccode.setText("bankacccode");
        jtxtbankacccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbankacccodeActionPerformed(evt);
            }
        });
        jtxtbankacccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtbankacccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtbankacccode);
        jtxtbankacccode.setBounds(170, 40, 140, 23);

        jlblvoidacccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblvoidacccode.setText("Void Cheques");
        jpAccount.add(jlblvoidacccode);
        jlblvoidacccode.setBounds(20, 70, 140, 13);

        jtxtvoidacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtvoidacccode.setText("voidacccode");
        jtxtvoidacccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtvoidacccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtvoidacccode);
        jtxtvoidacccode.setBounds(170, 70, 140, 23);

        jlbltrnfclracccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltrnfclracccode.setForeground(new java.awt.Color(251, 12, 12));
        jlbltrnfclracccode.setText("Bank Transfer*");
        jpAccount.add(jlbltrnfclracccode);
        jlbltrnfclracccode.setBounds(20, 160, 140, 20);

        jtxttrnfclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttrnfclracccode.setText("trnfclracccode");
        jtxttrnfclracccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttrnfclracccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxttrnfclracccode);
        jtxttrnfclracccode.setBounds(170, 160, 140, 23);

        jlblcashclracccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcashclracccode.setText("Cash Accounting");
        jpAccount.add(jlblcashclracccode);
        jlblcashclracccode.setBounds(20, 190, 140, 13);

        jtxtcashclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcashclracccode.setText("cashclracccode");
        jtxtcashclracccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcashclracccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtcashclracccode);
        jtxtcashclracccode.setBounds(170, 190, 140, 23);

        jlblarclracccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblarclracccode.setForeground(new java.awt.Color(251, 12, 12));
        jlblarclracccode.setText("Account Receivable*");
        jpAccount.add(jlblarclracccode);
        jlblarclracccode.setBounds(20, 220, 140, 20);

        jtxtarclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtarclracccode.setText("arclracccode");
        jtxtarclracccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtarclracccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtarclracccode);
        jtxtarclracccode.setBounds(170, 220, 140, 23);

        jlblapclraccode.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblapclraccode.setForeground(new java.awt.Color(251, 12, 12));
        jlblapclraccode.setText("Account Payable*");
        jpAccount.add(jlblapclraccode);
        jlblapclraccode.setBounds(20, 250, 140, 13);

        jtxtapclraccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtapclraccode.setText("apclraccode");
        jtxtapclraccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtapclraccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtapclraccode);
        jtxtapclraccode.setBounds(170, 250, 140, 23);

        jlbljcclracccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljcclracccode.setText("Job Costing");
        jpAccount.add(jlbljcclracccode);
        jlbljcclracccode.setBounds(20, 280, 140, 13);

        jtxtjcclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjcclracccode.setText("jcclracccode");
        jtxtjcclracccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtjcclracccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtjcclracccode);
        jtxtjcclracccode.setBounds(170, 280, 140, 23);

        jlblprclracccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblprclracccode.setText("Payroll");
        jpAccount.add(jlblprclracccode);
        jlblprclracccode.setBounds(20, 310, 140, 13);

        jtxtprclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtprclracccode.setText("prclracccode");
        jtxtprclracccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtprclracccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtprclracccode);
        jtxtprclracccode.setBounds(170, 310, 140, 23);

        jlblapbankacccode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblapbankacccode.setText("AP Bank");
        jpAccount.add(jlblapbankacccode);
        jlblapbankacccode.setBounds(20, 340, 140, 13);

        jtxtapbankacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtapbankacccode.setText("apbankacccode");
        jtxtapbankacccode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtapbankacccodeKeyPressed(evt);
            }
        });
        jpAccount.add(jtxtapbankacccode);
        jtxtapbankacccode.setBounds(170, 340, 140, 23);
        jpAccount.add(jSeparator1);
        jSeparator1.setBounds(180, 120, 540, 10);

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Clearing Accounts");
        jpAccount.add(jLabel1);
        jLabel1.setBounds(20, 110, 170, 22);

        jbtnBrowseApbankacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseApbankacccode.setText("...");
        jbtnBrowseApbankacccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseApbankacccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseApbankacccode);
        jbtnBrowseApbankacccode.setBounds(310, 340, 30, 17);

        jbtnBrowseBankAcc.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseBankAcc.setText("...");
        jbtnBrowseBankAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseBankAccActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseBankAcc);
        jbtnBrowseBankAcc.setBounds(310, 40, 30, 17);

        jbtnBrowseVoidAcccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseVoidAcccode.setText("...");
        jbtnBrowseVoidAcccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseVoidAcccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseVoidAcccode);
        jbtnBrowseVoidAcccode.setBounds(310, 70, 30, 17);

        jbtnBrowseTrnfclacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseTrnfclacccode.setText("...");
        jbtnBrowseTrnfclacccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseTrnfclacccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseTrnfclacccode);
        jbtnBrowseTrnfclacccode.setBounds(310, 160, 30, 17);

        jbtnBrowseCashclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseCashclracccode.setText("...");
        jbtnBrowseCashclracccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseCashclracccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseCashclracccode);
        jbtnBrowseCashclracccode.setBounds(310, 190, 30, 17);

        jbtnBrowseArclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseArclracccode.setText("...");
        jbtnBrowseArclracccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseArclracccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseArclracccode);
        jbtnBrowseArclracccode.setBounds(310, 220, 30, 17);

        jbtnBrowseApclraacccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseApclraacccode.setText("...");
        jbtnBrowseApclraacccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseApclraacccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowseApclraacccode);
        jbtnBrowseApclraacccode.setBounds(310, 250, 30, 17);

        jbtnJcclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnJcclracccode.setText("...");
        jbtnJcclracccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJcclracccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnJcclracccode);
        jbtnJcclracccode.setBounds(310, 280, 30, 17);

        jbtnBrowsePrclracccode.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowsePrclracccode.setText("...");
        jbtnBrowsePrclracccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowsePrclracccodeActionPerformed(evt);
            }
        });
        jpAccount.add(jbtnBrowsePrclracccode);
        jbtnBrowsePrclracccode.setBounds(310, 310, 30, 17);

        jtxtVoidaccdesc.setEditable(false);
        jtxtVoidaccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtVoidaccdesc.setText("voidacccodedesc");
        jpAccount.add(jtxtVoidaccdesc);
        jtxtVoidaccdesc.setBounds(350, 70, 350, 23);

        jtxtTrnfaccdesc.setEditable(false);
        jtxtTrnfaccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtTrnfaccdesc.setText("Trnfacccodedesc");
        jpAccount.add(jtxtTrnfaccdesc);
        jtxtTrnfaccdesc.setBounds(350, 160, 350, 23);

        jtxtCashclraccdesc.setEditable(false);
        jtxtCashclraccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtCashclraccdesc.setText("Cashclracccodedesc");
        jpAccount.add(jtxtCashclraccdesc);
        jtxtCashclraccdesc.setBounds(350, 190, 350, 23);

        jtxtArclraccdesc.setEditable(false);
        jtxtArclraccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtArclraccdesc.setText("arclracccodedesc");
        jpAccount.add(jtxtArclraccdesc);
        jtxtArclraccdesc.setBounds(350, 220, 350, 23);

        jtxtapclraccdesc.setEditable(false);
        jtxtapclraccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtapclraccdesc.setText("apclracccodedesc");
        jpAccount.add(jtxtapclraccdesc);
        jtxtapclraccdesc.setBounds(350, 250, 350, 23);

        jtxtJcclraccdesc.setEditable(false);
        jtxtJcclraccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtJcclraccdesc.setText("jcclaracccodedesc");
        jpAccount.add(jtxtJcclraccdesc);
        jtxtJcclraccdesc.setBounds(350, 280, 350, 23);

        jtxtPrclraccdesc.setEditable(false);
        jtxtPrclraccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtPrclraccdesc.setText("prclracccodedesc");
        jpAccount.add(jtxtPrclraccdesc);
        jtxtPrclraccdesc.setBounds(350, 310, 350, 23);

        jtxtApbankaccdesc.setEditable(false);
        jtxtApbankaccdesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtApbankaccdesc.setText("apbankacccodedesc");
        jpAccount.add(jtxtApbankaccdesc);
        jtxtApbankaccdesc.setBounds(350, 340, 350, 23);

        jtxtBankacccodedesc.setEditable(false);
        jtxtBankacccodedesc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtBankacccodedesc.setText("Bankacccodedesc");
        jpAccount.add(jtxtBankacccodedesc);
        jtxtBankacccodedesc.setBounds(350, 40, 350, 23);

        jtabBank.addTab("Account Code", jpAccount);

        getContentPane().add(jtabBank);
        jtabBank.setBounds(50, 110, 750, 440);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(270, 70, 40, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveLast();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseCurrnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseCurrnCodeActionPerformed
      try {
	      Gl_currencys brs = new Gl_currencys();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtcurnccode);
              bd.setSecondValue(jtxtcurncdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseCurrnCodeActionPerformed

private void jbtnBrowseBankAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseBankAccActionPerformed

          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtbankacccode);
              bd.setSecondValue(jtxtBankacccodedesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }



}//GEN-LAST:event_jbtnBrowseBankAccActionPerformed

private void jbtnBrowseVoidAcccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseVoidAcccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtvoidacccode);
              bd.setSecondValue(jtxtVoidaccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseVoidAcccodeActionPerformed

private void jbtnBrowseTrnfclacccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseTrnfclacccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxttrnfclracccode);
              bd.setSecondValue(jtxtTrnfaccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseTrnfclacccodeActionPerformed

private void jbtnBrowseCashclracccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseCashclracccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtcashclracccode);
              bd.setSecondValue(jtxtCashclraccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowseCashclracccodeActionPerformed

private void jbtnBrowseArclracccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseArclracccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtarclracccode);
              bd.setSecondValue(jtxtArclraccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseArclracccodeActionPerformed

private void jbtnBrowseApclraacccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseApclraacccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtapclraccode);
              bd.setSecondValue(jtxtapclraccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseApclraacccodeActionPerformed

private void jbtnJcclracccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJcclracccodeActionPerformed

          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtjcclracccode);
              bd.setSecondValue(jtxtJcclraccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnJcclracccodeActionPerformed

private void jbtnBrowsePrclracccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowsePrclracccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtprclracccode);
              bd.setSecondValue(jtxtPrclraccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowsePrclracccodeActionPerformed

private void jbtnBrowseApbankacccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseApbankacccodeActionPerformed
          try {
	      Gl_accounts brs = new Gl_accounts();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtapbankacccode);
              bd.setSecondValue(jtxtApbankaccdesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }


}//GEN-LAST:event_jbtnBrowseApbankacccodeActionPerformed

private void jchkDplctcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkDplctcheckActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jchkDplctcheckActionPerformed

private void jtxtbankacccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbankacccodeActionPerformed



}//GEN-LAST:event_jtxtbankacccodeActionPerformed

private void jtxtbankacccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbankacccodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setbankacccode(jtxtbankacccode.getText());
            jtxtBankacccodedesc.setText(obj.getBankAccDesc());

            jtxtvoidacccode.requestFocus();
        }catch(Exception e) {}
    }
}//GEN-LAST:event_jtxtbankacccodeKeyPressed

private void jtxtvoidacccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvoidacccodeKeyPressed


    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setvoidacccode(jtxtvoidacccode.getText());
            jtxtVoidaccdesc.setText(obj.getVoidAccDesc());
        }catch(Exception e) {}
        jtxttrnfclracccode.requestFocus();

    }


}//GEN-LAST:event_jtxtvoidacccodeKeyPressed

private void jtxttrnfclracccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttrnfclracccodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.settrnfclracccode(jtxttrnfclracccode.getText());
            jtxtTrnfaccdesc.setText(obj.getTrnfAccDesc());

        }catch(Exception e) {}
        jtxtcashclracccode.requestFocus();
    }


}//GEN-LAST:event_jtxttrnfclracccodeKeyPressed

private void jtxtcashclracccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcashclracccodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setcashclracccode(jtxtcashclracccode.getText());
            jtxtCashclraccdesc.setText(obj.getCashclrAccDesc());

        }catch(Exception e) {}
        jtxtarclracccode.requestFocus();
    }
}//GEN-LAST:event_jtxtcashclracccodeKeyPressed

private void jtxtarclracccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtarclracccodeKeyPressed


    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setarclracccode(jtxtarclracccode.getText());
            jtxtArclraccdesc.setText(obj.getArclAccDesc());

        }catch(Exception e) {}
        jtxtapclraccode.requestFocus();
    }
}//GEN-LAST:event_jtxtarclracccodeKeyPressed

private void jtxtapclraccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtapclraccodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setapclraccode(jtxtapclraccode.getText());
            jtxtapclraccdesc.setText(obj.getApclrAccDesc());

        }catch(Exception e) {}
        jtxtjcclracccode.requestFocus();
    }
}//GEN-LAST:event_jtxtapclraccodeKeyPressed

private void jtxtjcclracccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjcclracccodeKeyPressed

     if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setjcclracccode(jtxtjcclracccode.getText());
            jtxtJcclraccdesc.setText(obj.getJcclrAccDesc());

        }catch(Exception e) {}
        jtxtprclracccode.requestFocus();
     }
}//GEN-LAST:event_jtxtjcclracccodeKeyPressed

private void jtxtprclracccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtprclracccodeKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setprclracccode(jtxtprclracccode.getText());
            jtxtPrclraccdesc.setText(obj.getPrclrAccDesc());

        }catch(Exception e) {}
        jtxtapbankacccode.requestFocus();
    }
}//GEN-LAST:event_jtxtprclracccodeKeyPressed

private void jtxtapbankacccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtapbankacccodeKeyPressed


    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        try{
            obj.setapbankacccode(jtxtapbankacccode.getText());
            jtxtApbankaccdesc.setText(obj.getAPBankAccDesc());

        }catch(Exception e) {}
    }
}//GEN-LAST:event_jtxtapbankacccodeKeyPressed

private void jtxtbankcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbankcodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtbankname.requestFocus();
    }
}//GEN-LAST:event_jtxtbankcodeKeyPressed

private void jtxtbanknameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbanknameKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtaddress1.requestFocus();
    }
}//GEN-LAST:event_jtxtbanknameKeyPressed

private void jtxtaddress1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaddress1KeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtaddress2.requestFocus();
    }
    
}//GEN-LAST:event_jtxtaddress1KeyPressed

private void jtxtaddress2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaddress2KeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtcity.requestFocus();
    }
}//GEN-LAST:event_jtxtaddress2KeyPressed

private void jtxtcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcityKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtstate.requestFocus();
    }
}//GEN-LAST:event_jtxtcityKeyPressed

private void jtxtstateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtstateKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtpostalcode.requestFocus();
    }
}//GEN-LAST:event_jtxtstateKeyPressed

private void jtxtpostalcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpostalcodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtfaxno.requestFocus();
    }
}//GEN-LAST:event_jtxtpostalcodeKeyPressed

private void jtxtfaxnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfaxnoKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtcontact.requestFocus();
    }
}//GEN-LAST:event_jtxtfaxnoKeyPressed

private void jtxtcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcontactKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtphone1.requestFocus();
    }
}//GEN-LAST:event_jtxtcontactKeyPressed

private void jtxtphone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtphone1KeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtphone2.requestFocus();
    }
}//GEN-LAST:event_jtxtphone1KeyPressed

private void jtxtphone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtphone2KeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtcomments.requestFocus();
    }
}//GEN-LAST:event_jtxtphone2KeyPressed

private void jtxtcommentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcommentsKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtbankaccno.requestFocus();
    }
}//GEN-LAST:event_jtxtcommentsKeyPressed

private void jtxtbankaccnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbankaccnoKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtsrceledgr.requestFocus();
    }
}//GEN-LAST:event_jtxtbankaccnoKeyPressed

private void jtxtsrceledgrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsrceledgrKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtrvslsrcecode.requestFocus();
    }
}//GEN-LAST:event_jtxtsrceledgrKeyPressed

private void jtxtrvslsrcecodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtrvslsrcecodeKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        try{
            Cb_source cb = new Cb_source(jtxtrvslsrcecode.getText());
            jtxtrvslsrcedesc.setText(cb.getdscription());

        }catch(Exception e){}
        jtxtvoidsrcecode.requestFocus();
    }
}//GEN-LAST:event_jtxtrvslsrcecodeKeyPressed

private void jtxtvoidsrcecodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvoidsrcecodeKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        try{
            Cb_source cb = new Cb_source(jtxtvoidsrcecode.getText());
            jtxtvoidsrcedesc.setText(cb.getdscription());

        }catch(Exception e){}
        jtxtcurnccode.requestFocus();
    }

}//GEN-LAST:event_jtxtvoidsrcecodeKeyPressed

private void jtxtcurnccodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcurnccodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        try{
            Gl_currency curr = new Gl_currency(jtxtcurnccode.getText());
            jtxtcurncdesc.setText(curr.getcurncdesc());
        }catch(Exception e){}
        jtxtratetypecode.requestFocus();
    }
    
}//GEN-LAST:event_jtxtcurnccodeKeyPressed

private void jtxtratetypecodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtratetypecodeKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jchkDplctcheck.requestFocus();
    }
}//GEN-LAST:event_jtxtratetypecodeKeyPressed

private void jchkDplctcheckKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkDplctcheckKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jtxtbankacccode.requestFocus();
    }
    
}//GEN-LAST:event_jchkDplctcheckKeyPressed

private void jbtnbrowservslsrcecodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnbrowservslsrcecodeKeyPressed

    try{
        obj.setrvslsrcecode(jtxtrvslsrcecode.getText());
        jtxtrvslsrcedesc.setText(obj.getrvslsrceDescription());
    }catch(Exception e){}
}//GEN-LAST:event_jbtnbrowservslsrcecodeKeyPressed

private void jbtnbrowservslsrcecodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnbrowservslsrcecodeMouseClicked
    // TODO add your handling code here:
}//GEN-LAST:event_jbtnbrowservslsrcecodeMouseClicked

private void jbtnbrowservslsrcecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbrowservslsrcecodeActionPerformed
      try {
	      Cb_sources brs = new Cb_sources();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtrvslsrcecode);
              bd.setSecondValue(jtxtrvslsrcedesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnbrowservslsrcecodeActionPerformed

private void jbtnBrowsevoidsrcecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowsevoidsrcecodeActionPerformed

          try {
	      Cb_sources brs = new Cb_sources();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtvoidsrcecode);
              bd.setSecondValue(jtxtvoidsrcedesc);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowsevoidsrcecodeActionPerformed

private void jbtnBrowsevoidsrcecodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnBrowsevoidsrcecodeKeyPressed

    try{
        obj.setvoidsrcecode(jtxtvoidsrcecode.getText());
        jtxtvoidsrcedesc.setText(obj.getvoidsrceDescription());
        
    }catch(Exception e){}
}//GEN-LAST:event_jbtnBrowsevoidsrcecodeKeyPressed

private void jbtnBrowseratetypecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseratetypecodeActionPerformed
          try {
	      Gl_ratetypes brs = new Gl_ratetypes();
	      FrmBrowse bd = new FrmBrowse(brs);
	      bd.setFirstValue(jtxtratetypecode);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowseratetypecodeActionPerformed

private void jbtnBrowsesrceledgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowsesrceledgrActionPerformed
          try {
	      Gl_sourcelgrs brs = new Gl_sourcelgrs();
	      FrmBrowseGl_SourceGr bd = new FrmBrowseGl_SourceGr(brs);
              bd.sSrcelgrcode = "CB";
	      bd.setFirstValue(jtxtsrceledgr);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }

}//GEN-LAST:event_jbtnBrowsesrceledgrActionPerformed

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
      try {
	      Cb_banks brs = new Cb_banks();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtid);
	      bd.setModal(true);
	      bd.setVisible(true);

	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}//GEN-LAST:event_jbtnBrowseActionPerformed


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCb_bank().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowseApbankacccode;
    private javax.swing.JButton jbtnBrowseApclraacccode;
    private javax.swing.JButton jbtnBrowseArclracccode;
    private javax.swing.JButton jbtnBrowseBankAcc;
    private javax.swing.JButton jbtnBrowseCashclracccode;
    private javax.swing.JButton jbtnBrowseCurrnCode;
    private javax.swing.JButton jbtnBrowsePrclracccode;
    private javax.swing.JButton jbtnBrowseTrnfclacccode;
    private javax.swing.JButton jbtnBrowseVoidAcccode;
    private javax.swing.JButton jbtnBrowseratetypecode;
    private javax.swing.JButton jbtnBrowsesrceledgr;
    private javax.swing.JButton jbtnBrowsevoidsrcecode;
    private javax.swing.JButton jbtnJcclracccode;
    private javax.swing.JButton jbtnbrowservslsrcecode;
    private javax.swing.JCheckBox jchkDplctcheck;
    private javax.swing.JLabel jlbladdress1;
    private javax.swing.JLabel jlbladdress2;
    private javax.swing.JLabel jlblapbankacccode;
    private javax.swing.JLabel jlblapclraccode;
    private javax.swing.JLabel jlblarclracccode;
    private javax.swing.JLabel jlblbankacccode;
    private javax.swing.JLabel jlblbankaccno;
    private javax.swing.JLabel jlblbankcode;
    private javax.swing.JLabel jlblcashclracccode;
    private javax.swing.JLabel jlblcity;
    private javax.swing.JLabel jlblcomments;
    private javax.swing.JLabel jlblcontact;
    private javax.swing.JLabel jlblcurnccode;
    private javax.swing.JLabel jlblfaxno;
    private javax.swing.JLabel jlbljcclracccode;
    private javax.swing.JLabel jlblphone1;
    private javax.swing.JLabel jlblphone2;
    private javax.swing.JLabel jlblpostalcode;
    private javax.swing.JLabel jlblprclracccode;
    private javax.swing.JLabel jlblratetypecode;
    private javax.swing.JLabel jlblrvslsrcecode;
    private javax.swing.JLabel jlblrvslsrcecode1;
    private javax.swing.JLabel jlblsrceledgr;
    private javax.swing.JLabel jlblstate;
    private javax.swing.JLabel jlbltrnfclracccode;
    private javax.swing.JLabel jlblvoidacccode;
    private javax.swing.JPanel jpAccount;
    private javax.swing.JPanel jpAddress;
    private javax.swing.JPanel jpBank;
    private javax.swing.JPanel jpOption;
    private javax.swing.JTabbedPane jtabBank;
    private javax.swing.JTextField jtxtApbankaccdesc;
    private javax.swing.JTextField jtxtArclraccdesc;
    private javax.swing.JTextField jtxtBankacccodedesc;
    private javax.swing.JTextField jtxtCashclraccdesc;
    private javax.swing.JTextField jtxtJcclraccdesc;
    private javax.swing.JTextField jtxtPrclraccdesc;
    private javax.swing.JTextField jtxtTrnfaccdesc;
    private javax.swing.JTextField jtxtVoidaccdesc;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtaddress2;
    private javax.swing.JTextField jtxtapbankacccode;
    private javax.swing.JTextField jtxtapclraccdesc;
    private javax.swing.JTextField jtxtapclraccode;
    private javax.swing.JTextField jtxtarclracccode;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtbankacccode;
    private javax.swing.JTextField jtxtbankaccno;
    private javax.swing.JTextField jtxtbankcode;
    private javax.swing.JTextField jtxtbankname;
    private javax.swing.JTextField jtxtcashclracccode;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextArea jtxtcomments;
    private javax.swing.JTextField jtxtcontact;
    private javax.swing.JTextField jtxtcurnccode;
    private javax.swing.JTextField jtxtcurncdesc;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtfaxno;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtjcclracccode;
    private javax.swing.JTextField jtxtphone1;
    private javax.swing.JTextField jtxtphone2;
    private javax.swing.JTextField jtxtpostalcode;
    private javax.swing.JTextField jtxtprclracccode;
    private javax.swing.JTextField jtxtratetypecode;
    private javax.swing.JTextField jtxtrvslsrcecode;
    private javax.swing.JTextField jtxtrvslsrcedesc;
    private javax.swing.JTextField jtxtsrceledgr;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxttrnfclracccode;
    private javax.swing.JTextField jtxtvoidacccode;
    private javax.swing.JTextField jtxtvoidsrcecode;
    private javax.swing.JTextField jtxtvoidsrcedesc;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Cb_bank(this.jtxtid.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Cb_bank();
        istatus=1;
        showData();

        jtxtsrceledgr.setText(cbopt.getsrcelgrcode());
        
        setToolBar(iformtype,istatus);
    }

    private void validasi() throws CodeException {

        if (!jtxtrvslsrcecode.getText().equals("")) {

            Cb_source cb = new Cb_source(jtxtrvslsrcecode.getText());
            if(cb.getID() == Cb_source.NULLID) {
                throw new CodeException("RVS  " + jtxtrvslsrcecode.getText() + " Tidak Diketemukan ");
            }
        }
        if (!jtxtvoidsrcecode.getText().equals("")) {

            Cb_source cb = new Cb_source(jtxtvoidsrcecode.getText());
            if(cb.getID() == Cb_source.NULLID) {
                throw new CodeException("Void " + jtxtvoidsrcecode.getText() + " Tidak Diketemukan ");
            }
        }

        if(!jtxtcurnccode.getText().equals("")){
            Gl_currency glc = new Gl_currency(jtxtcurnccode.getText().replace("-", ""));
            if(glc.getID() == Gl_currency.NULLID) {
                throw new CodeException("Currency " + jtxtcurnccode.getText() + " Tidak Diketemukan ");
            }
        } else {
            throw new CodeException("Currency Cannot be emtpy ");
        }

        if(!jtxtratetypecode.getText().equals("")){
            Gl_ratetype glrt = new Gl_ratetype(Gl_ratetype.PROPERTY_RATETYPE,jtxtratetypecode.getText().replace("-", ""));
            if(glrt.getID() == Gl_ratetype.NULLID) {
                throw new CodeException("Rate Type Code " + jtxtratetypecode.getText() + " Tidak Diketemukan ");
            }
        } else {
            throw new CodeException("Rate Type Code Cannot be emtpy ");
        }


        if(!jtxtbankacccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtbankacccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Bank Account Code " + jtxtbankacccode.getText() + " Tidak Diketemukan ");
            }
        }else {
            throw new CodeException("Bank Account Code Cannot be emtpy ");
        }


        if(!jtxtvoidacccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtvoidacccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Void Cheques " + jtxtvoidacccode.getText() + " Tidak Diketemukan ");
            }
        }

        if(!jtxttrnfclracccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxttrnfclracccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Bank Transfer " + jtxttrnfclracccode.getText() + " Tidak Diketemukan ");
            }
        }else {
            throw new CodeException("Bank Transfer Account Code Cannot be emtpy ");
        }

       if(!jtxtcashclracccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtcashclracccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Cash Accounting " + jtxtcashclracccode.getText() + " Tidak Diketemukan ");
            }
        }

       if(!jtxtarclracccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtarclracccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Account Receivable " + jtxtarclracccode.getText() + " Tidak Diketemukan ");
            }
        }else {
            throw new CodeException("Account Receivable Account Code Cannot be emtpy ");
        }


       if(!jtxtapclraccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtapclraccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Account Payable " + jtxtapclraccode.getText() + " Tidak Diketemukan ");
            }
        }else {
            throw new CodeException("Account Payable Account Code Cannot be emtpy ");
        }


       if(!jtxtjcclracccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtjcclracccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Job Costing " + jtxtjcclracccode.getText() + " Tidak Diketemukan ");
            }
        }

       if(!jtxtjcclracccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtjcclracccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Job Costing " + jtxtjcclracccode.getText() + " Tidak Diketemukan ");
            }
        }

       if(!jtxtprclracccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtprclracccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("Payroll " + jtxtprclracccode.getText() + " Tidak Diketemukan ");
            }
        }


        if(!jtxtapbankacccode.getText().equals("")) {
            Gl_account glc = new Gl_account(jtxtapbankacccode.getText().replace("-", ""));
            if(glc.getID() == Gl_account.NULLID) {
                throw new CodeException("AP Bank " + jtxtapbankacccode.getText() + " Tidak Diketemukan ");
            }
        }




    }

    public void saveData() throws CodeException {

        validasi();
        
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Cb_bank.PROPERTY_ID));
             jtxtbankcode.setText(obj.toString(Cb_bank.PROPERTY_BANKCODE));
             jtxtbankname.setText(obj.toString(Cb_bank.PROPERTY_BANKNAME));
             jtxtaddress1.setText(obj.toString(Cb_bank.PROPERTY_ADDRESS1));
             jtxtaddress2.setText(obj.toString(Cb_bank.PROPERTY_ADDRESS2));
             jtxtcity.setText(obj.toString(Cb_bank.PROPERTY_CITY));
             jtxtstate.setText(obj.toString(Cb_bank.PROPERTY_STATE));
             jtxtpostalcode.setText(obj.toString(Cb_bank.PROPERTY_POSTALCODE));
             jtxtphone1.setText(obj.toString(Cb_bank.PROPERTY_PHONE1));
             jtxtphone2.setText(obj.toString(Cb_bank.PROPERTY_PHONE2));
             jtxtfaxno.setText(obj.toString(Cb_bank.PROPERTY_FAXNO));
             jtxtcontact.setText(obj.toString(Cb_bank.PROPERTY_CONTACT));
             jtxtcomments.setText(obj.toString(Cb_bank.PROPERTY_COMMENTS));
             jtxtbankaccno.setText(obj.toString(Cb_bank.PROPERTY_BANKACCNO));
             jtxtsrceledgr.setText(obj.toString(Cb_bank.PROPERTY_SRCELEDGR));
             
             jtxtrvslsrcecode.setText(obj.toString(Cb_bank.PROPERTY_RVSLSRCECODE));
             jtxtrvslsrcedesc.setText(obj.getrvslsrceDescription());
             
             jtxtvoidsrcecode.setText(obj.toString(Cb_bank.PROPERTY_VOIDSRCECODE));
             jtxtvoidsrcedesc.setText(obj.getvoidsrceDescription());

             jtxtcurnccode.setText(obj.toString(Cb_bank.PROPERTY_CURNCCODE));
             jtxtcurncdesc.setText(obj.getCurrencyDescription());
             jtxtratetypecode.setText(obj.toString(Cb_bank.PROPERTY_RATETYPECODE));

             jchkDplctcheck.setSelected(obj.getdplctcheck() == 1);
             
             jtxtbankacccode.setText(GlobalUtils.churuf(obj.getbankacccodefmt()));
             jtxtBankacccodedesc.setText(obj.getBankAccDesc());

             jtxtvoidacccode.setText(GlobalUtils.churuf(obj.getvoidacccodefmt()));
             jtxtVoidaccdesc.setText(obj.getVoidAccDesc());

             jtxttrnfclracccode.setText(GlobalUtils.churuf(obj.gettrnfclracccodefmt()));
             jtxtTrnfaccdesc.setText(obj.getTrnfAccDesc());

             jtxtcashclracccode.setText(GlobalUtils.churuf(obj.getcashclracccodefmt()));
             jtxtCashclraccdesc.setText(obj.getCashclrAccDesc());

             jtxtarclracccode.setText(GlobalUtils.churuf(obj.getarclracccodefmt()));
             jtxtArclraccdesc.setText(obj.getArclAccDesc());


             jtxtapclraccode.setText(GlobalUtils.churuf(obj.getapclraccodefmt()));
             jtxtapclraccdesc.setText(obj.getApclrAccDesc());

             jtxtjcclracccode.setText(GlobalUtils.churuf(obj.getjcclracccodefmt()));
             jtxtJcclraccdesc.setText(obj.getJcclrAccDesc());

             jtxtprclracccode.setText(GlobalUtils.churuf(obj.getprclracccodefmt()));
             jtxtPrclraccdesc.setText(obj.getPrclrAccDesc());

             jtxtapbankacccode.setText(GlobalUtils.churuf(obj.getapbankacccodefmt()));
             jtxtApbankaccdesc.setText(obj.getAPBankAccDesc());

             jtxtentrydate.setText(obj.toString(Cb_bank.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Cb_bank.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Cb_bank.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Cb_bank.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Cb_bank.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_BANKCODE, jtxtbankcode.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_BANKNAME, jtxtbankname.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_ADDRESS1, jtxtaddress1.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_ADDRESS2, jtxtaddress2.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_CITY, jtxtcity.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_STATE, jtxtstate.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_POSTALCODE, jtxtpostalcode.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_PHONE1, jtxtphone1.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_PHONE2, jtxtphone2.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_FAXNO, jtxtfaxno.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_CONTACT, jtxtcontact.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_COMMENTS, jtxtcomments.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_BANKACCNO, jtxtbankaccno.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_SRCELEDGR, jtxtsrceledgr.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_RVSLSRCECODE, jtxtrvslsrcecode.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_VOIDSRCECODE, jtxtvoidsrcecode.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_CURNCCODE, jtxtcurnccode.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_RATETYPECODE, jtxtratetypecode.getText()) ;
          obj.fromString(Cb_bank.PROPERTY_DPLCTCHECK, jchkDplctcheck.isSelected()?"1":"0");

          
          obj.setbankacccode(jtxtbankacccode.getText()) ;
          obj.setvoidacccode(jtxtvoidacccode.getText()) ;
          obj.settrnfclracccode(jtxttrnfclracccode.getText()) ;
          obj.setcashclracccode(jtxtcashclracccode.getText()) ;
          obj.setarclracccode(jtxtarclracccode.getText()) ;
          obj.setapclraccode(jtxtapclraccode.getText()) ;
          obj.setjcclracccode(jtxtjcclracccode.getText()) ;
          obj.setprclracccode(jtxtprclracccode.getText()) ;
          obj.setapbankacccode(jtxtapbankacccode.getText()) ;
          obj.setentrydate(jtxtentrydate.getText()) ;
          obj.setauditdate(jtxtauditdate.getText()) ;
          obj.setaudituser(jtxtaudituser.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
