/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import test.FrmCb_cash_advance;
 * 
 * .......
 * 
 * 
 * FrmCb_cash_advance frmCb_cash_advance;
 * 
 * .......
 * 
 try {
        if (frmCb_cash_advance == null) {
            frmmCb_cash_advance = new FrmCb_cash_advance(this);
        }
        
        showForm(frmCb_cash_advance);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package accapp.component;

import common.component.FrmBrowse;
import common.classinterface.NavigatorFormInt;
import common.classinterface.NavigatorObjectInt;
import common.component.FrmMainFrame;

import common.utils.CodeException;
import common.utils.GlobalUtils;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import common.utils.ExtFileChooserFilter;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import accapp.objectclasses.cashbook.Cb_cash_advance;
import accapp.objectclasses.cashbook.Cb_cash_advances;

/**
 *
 * @author  Generator
 */

public class FrmCb_cash_advance extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="FrmCb_cash_advance";
    
    FrmMainFrame mf ;
    
    
    public Cb_cash_advance obj = new Cb_cash_advance();
    
   
    /** Creates new form Area */
    public FrmCb_cash_advance() throws CodeException {
        initComponents();
    }
    
    public FrmCb_cash_advance(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblid = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jlblbase_batchno = new javax.swing.JLabel();
        jtxtbase_batchno = new javax.swing.JTextField();
        jlblbase_entryno = new javax.swing.JLabel();
        jtxtbase_entryno = new javax.swing.JTextField();
        jlblbase_detailno = new javax.swing.JLabel();
        jtxtbase_detailno = new javax.swing.JTextField();
        jlbladvance_no = new javax.swing.JLabel();
        jtxtadvance_no = new javax.swing.JTextField();
        jlbladvance_ref_no = new javax.swing.JLabel();
        jtxtadvance_ref_no = new javax.swing.JTextField();
        jlblyop = new javax.swing.JLabel();
        jtxtyop = new javax.swing.JTextField();
        jlblmop = new javax.swing.JLabel();
        jtxtmop = new javax.swing.JTextField();
        jlbladvance_date = new javax.swing.JLabel();
        jtxtadvance_date = new javax.swing.JTextField();
        jlbladvance_status = new javax.swing.JLabel();
        jtxtadvance_status = new javax.swing.JTextField();
        jlbladvance_pic = new javax.swing.JLabel();
        jtxtadvance_pic = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlbladvance_amount = new javax.swing.JLabel();
        jtxtadvance_amount = new javax.swing.JTextField();
        jlbladvance_apply = new javax.swing.JLabel();
        jtxtadvance_apply = new javax.swing.JTextField();
        jlbladvance_balance = new javax.swing.JLabel();
        jtxtadvance_balance = new javax.swing.JTextField();
        jlblobjtype = new javax.swing.JLabel();
        jtxtobjtype = new javax.swing.JTextField();
        jlblentrydate = new javax.swing.JLabel();
        jtxtentrydate = new javax.swing.JTextField();
        jlblauditdate = new javax.swing.JLabel();
        jtxtauditdate = new javax.swing.JTextField();
        jlblaudituser = new javax.swing.JLabel();
        jtxtaudituser = new javax.swing.JTextField();
        jlblcmpnyid = new javax.swing.JLabel();
        jtxtcmpnyid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cb_cash_advance");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Cb_cash_advance");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 12);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 12, 400);

        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(430, 80, 30, 17);

        jlblid.setText("id");
        getContentPane().add(jlblid);
        jlblid.setBounds(70, 80, 140, 16);

        jtxtid.setText("id");
        getContentPane().add(jtxtid);
        jtxtid.setBounds(260, 80, 80, 28);

        jlblbase_batchno.setText("base_batchno");
        getContentPane().add(jlblbase_batchno);
        jlblbase_batchno.setBounds(70, 100, 140, 16);

        jtxtbase_batchno.setText("base_batchno");
        getContentPane().add(jtxtbase_batchno);
        jtxtbase_batchno.setBounds(260, 100, 80, 28);

        jlblbase_entryno.setText("base_entryno");
        getContentPane().add(jlblbase_entryno);
        jlblbase_entryno.setBounds(70, 120, 140, 16);

        jtxtbase_entryno.setText("base_entryno");
        getContentPane().add(jtxtbase_entryno);
        jtxtbase_entryno.setBounds(260, 120, 80, 28);

        jlblbase_detailno.setText("base_detailno");
        getContentPane().add(jlblbase_detailno);
        jlblbase_detailno.setBounds(70, 140, 140, 16);

        jtxtbase_detailno.setText("base_detailno");
        getContentPane().add(jtxtbase_detailno);
        jtxtbase_detailno.setBounds(260, 140, 80, 28);

        jlbladvance_no.setText("advance_no");
        getContentPane().add(jlbladvance_no);
        jlbladvance_no.setBounds(70, 160, 140, 16);

        jtxtadvance_no.setText("advance_no");
        getContentPane().add(jtxtadvance_no);
        jtxtadvance_no.setBounds(260, 160, 80, 28);

        jlbladvance_ref_no.setText("advance_ref_no");
        getContentPane().add(jlbladvance_ref_no);
        jlbladvance_ref_no.setBounds(70, 180, 140, 16);

        jtxtadvance_ref_no.setText("advance_ref_no");
        getContentPane().add(jtxtadvance_ref_no);
        jtxtadvance_ref_no.setBounds(260, 180, 80, 28);

        jlblyop.setText("yop");
        getContentPane().add(jlblyop);
        jlblyop.setBounds(70, 200, 140, 16);

        jtxtyop.setText("yop");
        getContentPane().add(jtxtyop);
        jtxtyop.setBounds(260, 200, 80, 28);

        jlblmop.setText("mop");
        getContentPane().add(jlblmop);
        jlblmop.setBounds(70, 220, 140, 16);

        jtxtmop.setText("mop");
        getContentPane().add(jtxtmop);
        jtxtmop.setBounds(260, 220, 80, 28);

        jlbladvance_date.setText("advance_date");
        getContentPane().add(jlbladvance_date);
        jlbladvance_date.setBounds(70, 240, 140, 16);

        jtxtadvance_date.setText("advance_date");
        getContentPane().add(jtxtadvance_date);
        jtxtadvance_date.setBounds(260, 240, 80, 28);

        jlbladvance_status.setText("advance_status");
        getContentPane().add(jlbladvance_status);
        jlbladvance_status.setBounds(70, 260, 140, 16);

        jtxtadvance_status.setText("advance_status");
        getContentPane().add(jtxtadvance_status);
        jtxtadvance_status.setBounds(260, 260, 80, 28);

        jlbladvance_pic.setText("advance_pic");
        getContentPane().add(jlbladvance_pic);
        jlbladvance_pic.setBounds(70, 280, 140, 16);

        jtxtadvance_pic.setText("advance_pic");
        getContentPane().add(jtxtadvance_pic);
        jtxtadvance_pic.setBounds(260, 280, 80, 28);

        jlbldscription.setText("dscription");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 300, 140, 16);

        jtxtdscription.setText("dscription");
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 300, 80, 28);

        jlbladvance_amount.setText("advance_amount");
        getContentPane().add(jlbladvance_amount);
        jlbladvance_amount.setBounds(70, 320, 140, 16);

        jtxtadvance_amount.setText("advance_amount");
        getContentPane().add(jtxtadvance_amount);
        jtxtadvance_amount.setBounds(260, 320, 80, 28);

        jlbladvance_apply.setText("advance_apply");
        getContentPane().add(jlbladvance_apply);
        jlbladvance_apply.setBounds(70, 340, 140, 16);

        jtxtadvance_apply.setText("advance_apply");
        getContentPane().add(jtxtadvance_apply);
        jtxtadvance_apply.setBounds(260, 340, 80, 28);

        jlbladvance_balance.setText("advance_balance");
        getContentPane().add(jlbladvance_balance);
        jlbladvance_balance.setBounds(70, 360, 140, 16);

        jtxtadvance_balance.setText("advance_balance");
        getContentPane().add(jtxtadvance_balance);
        jtxtadvance_balance.setBounds(260, 360, 80, 28);

        jlblobjtype.setText("objtype");
        getContentPane().add(jlblobjtype);
        jlblobjtype.setBounds(70, 380, 140, 16);

        jtxtobjtype.setText("objtype");
        getContentPane().add(jtxtobjtype);
        jtxtobjtype.setBounds(260, 380, 80, 28);

        jlblentrydate.setText("entrydate");
        getContentPane().add(jlblentrydate);
        jlblentrydate.setBounds(70, 400, 140, 16);

        jtxtentrydate.setText("entrydate");
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 400, 80, 28);

        jlblauditdate.setText("auditdate");
        getContentPane().add(jlblauditdate);
        jlblauditdate.setBounds(70, 420, 140, 16);

        jtxtauditdate.setText("auditdate");
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(260, 420, 80, 28);

        jlblaudituser.setText("audituser");
        getContentPane().add(jlblaudituser);
        jlblaudituser.setBounds(70, 440, 140, 16);

        jtxtaudituser.setText("audituser");
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(260, 440, 80, 28);

        jlblcmpnyid.setText("cmpnyid");
        getContentPane().add(jlblcmpnyid);
        jlblcmpnyid.setBounds(70, 460, 140, 16);

        jtxtcmpnyid.setText("cmpnyid");
        getContentPane().add(jtxtcmpnyid);
        jtxtcmpnyid.setBounds(260, 460, 80, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
      try {
	      Cb_cash_advances brs = new Cb_cash_advances();
	      FrmBrowse bd = new FrmBrowse(this, brs);
	      bd.setFirstValue(jtxtid);
	      bd.setModal(true);
	      bd.setVisible(true);            
	      
	  } catch (CodeException ex) {
	      ex.printStackTrace();
	  }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCb_cash_advance().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlbladvance_amount;
    private javax.swing.JLabel jlbladvance_apply;
    private javax.swing.JLabel jlbladvance_balance;
    private javax.swing.JLabel jlbladvance_date;
    private javax.swing.JLabel jlbladvance_no;
    private javax.swing.JLabel jlbladvance_pic;
    private javax.swing.JLabel jlbladvance_ref_no;
    private javax.swing.JLabel jlbladvance_status;
    private javax.swing.JLabel jlblauditdate;
    private javax.swing.JLabel jlblaudituser;
    private javax.swing.JLabel jlblbase_batchno;
    private javax.swing.JLabel jlblbase_detailno;
    private javax.swing.JLabel jlblbase_entryno;
    private javax.swing.JLabel jlblcmpnyid;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlblentrydate;
    private javax.swing.JLabel jlblid;
    private javax.swing.JLabel jlblmop;
    private javax.swing.JLabel jlblobjtype;
    private javax.swing.JLabel jlblyop;
    private javax.swing.JTextField jtxtadvance_amount;
    private javax.swing.JTextField jtxtadvance_apply;
    private javax.swing.JTextField jtxtadvance_balance;
    private javax.swing.JTextField jtxtadvance_date;
    private javax.swing.JTextField jtxtadvance_no;
    private javax.swing.JTextField jtxtadvance_pic;
    private javax.swing.JTextField jtxtadvance_ref_no;
    private javax.swing.JTextField jtxtadvance_status;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtbase_batchno;
    private javax.swing.JTextField jtxtbase_detailno;
    private javax.swing.JTextField jtxtbase_entryno;
    private javax.swing.JTextField jtxtcmpnyid;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtmop;
    private javax.swing.JTextField jtxtobjtype;
    private javax.swing.JTextField jtxtyop;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        obj = new Cb_cash_advance(this.jtxtid.getText());
        showData();
        mf.setIcon(CLASSNAME);

    }
    public void newData() throws CodeException {
        obj = new Cb_cash_advance();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        istatus = 0;
        setData();
        obj.save();
        
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtid.setText(obj.toString(Cb_cash_advance.PROPERTY_ID));
             jtxtbase_batchno.setText(obj.toString(Cb_cash_advance.PROPERTY_BASE_BATCHNO));
             jtxtbase_entryno.setText(obj.toString(Cb_cash_advance.PROPERTY_BASE_ENTRYNO));
             jtxtbase_detailno.setText(obj.toString(Cb_cash_advance.PROPERTY_BASE_DETAILNO));
             jtxtadvance_no.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_NO));
             jtxtadvance_ref_no.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_REF_NO));
             jtxtyop.setText(obj.toString(Cb_cash_advance.PROPERTY_YOP));
             jtxtmop.setText(obj.toString(Cb_cash_advance.PROPERTY_MOP));
             jtxtadvance_date.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_DATE));
             jtxtadvance_status.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_STATUS));
             jtxtadvance_pic.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_PIC));
             jtxtdscription.setText(obj.toString(Cb_cash_advance.PROPERTY_DSCRIPTION));
             jtxtadvance_amount.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_AMOUNT));
             jtxtadvance_apply.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_APPLY));
             jtxtadvance_balance.setText(obj.toString(Cb_cash_advance.PROPERTY_ADVANCE_BALANCE));
             jtxtobjtype.setText(obj.toString(Cb_cash_advance.PROPERTY_OBJTYPE));
             jtxtentrydate.setText(obj.toString(Cb_cash_advance.PROPERTY_ENTRYDATE));
             jtxtauditdate.setText(obj.toString(Cb_cash_advance.PROPERTY_AUDITDATE));
             jtxtaudituser.setText(obj.toString(Cb_cash_advance.PROPERTY_AUDITUSER));
             jtxtcmpnyid.setText(obj.toString(Cb_cash_advance.PROPERTY_CMPNYID));
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
	
          obj.fromString(Cb_cash_advance.PROPERTY_ID, jtxtid.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_BASE_BATCHNO, jtxtbase_batchno.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_BASE_ENTRYNO, jtxtbase_entryno.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_BASE_DETAILNO, jtxtbase_detailno.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_NO, jtxtadvance_no.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_REF_NO, jtxtadvance_ref_no.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_YOP, jtxtyop.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_MOP, jtxtmop.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_DATE, jtxtadvance_date.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_STATUS, jtxtadvance_status.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_PIC, jtxtadvance_pic.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_DSCRIPTION, jtxtdscription.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_AMOUNT, jtxtadvance_amount.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_APPLY, jtxtadvance_apply.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ADVANCE_BALANCE, jtxtadvance_balance.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_OBJTYPE, jtxtobjtype.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_ENTRYDATE, jtxtentrydate.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_AUDITDATE, jtxtauditdate.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_AUDITUSER, jtxtaudituser.getText()) ;
          obj.fromString(Cb_cash_advance.PROPERTY_CMPNYID, jtxtcmpnyid.getText()) ;

    }

    public void undo() throws CodeException {
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();
        NavigatorObjectInt noi = (NavigatorObjectInt) obj;        
        String file   = GlobalUtils.getCurrentDir() +"/Reports/" + noi.getClassName() + ".jrxml";
        GlobalUtils.printReport(file,  false);    
    }

    public void importCsv() throws CodeException {
            
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("CSV", new String[] { "CSV"});
        chooser.setFileFilter(filter1);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }

    }

    public void exportCsv() throws CodeException {
        
    
        if (obj.exportCsv()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".csv";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".csv";
                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        }
        
    }

    public void importText() throws CodeException {
        String file1 = "";
        String file2 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
        
        JFileChooser chooser = new JFileChooser(".");
        chooser.setDialogTitle("Pilih File ");
        FileFilter filter1 = new ExtFileChooserFilter("txt", new String[] { "txt"});
        chooser.setFileFilter(filter1);


        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            
            try {
                file1 = selectedFile.getCanonicalPath();
            
            }catch (Exception e) {}

            GlobalUtils.copyfile(file1, file2 );                

            obj.importCsv();
            
        }else {
          JOptionPane.showMessageDialog(null,"No Selection ");
        }
    }

    public void exportText() throws CodeException {
        if (obj.exportText()) {
            
            String file1 = GlobalUtils.getCurrentDir() + GlobalUtils.temp + obj.TABLEPROCESS + ".txt";   
            String file2 = "";
            
            JFileChooser chooser = new JFileChooser(".");
            chooser.setDialogTitle("Pilih Directory ");
    
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                try {
                    file2 = chooser.getSelectedFile().getCanonicalPath() + ".txt";                        
                    JOptionPane.showMessageDialog(null, GlobalUtils.copyfile(file1, file2 ));                    
                    
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());                    
                }
                
            }else {
              JOptionPane.showMessageDialog(null,"No Selection ");
            }
    
        } 
    }

    
}
